import {test,expect,type Page} from '@playwright/test';
import {createMatch,applyCommand,getView,defaultLoadout} from '../../src/game/index';
import {createTutorial,getTutorialView} from '../../src/game/tutorial';
import {mkdir} from 'node:fs/promises';

function tableFixture(tutorial=false){
 const initial=tutorial?createTutorial('L02',{matchId:'layout-lesson'}):{state:createMatch([defaultLoadout('p1','排版检查',5),defaultLoadout('p2','布局导师',5)],177,{skipSetup:true,matchId:'layout-full'}),progress:null};let s=initial.state;
 if(!tutorial){s.round=8;for(const playerId of ['p1','p2']){let p=s.players.find(x=>x.id===playerId)!;p.ownTurn=8;p.board=[];p.hand=[];s.activePlayerId=playerId;for(const [i,id]of ['N01','N02','N03','N05'].entries()){p=s.players.find(x=>x.id===playerId)!;const card={id:`layout-${playerId}-${i}`,definitionId:id,kind:'card' as const,taxes:[],knownTo:[]};p.hand.push(card);p.timeRemaining=8;const result=applyCommand(s,playerId,{type:'PLAY_CARD',cardId:card.id});if(result.error)throw Error(result.error);s=result.state;}
  p=s.players.find(x=>x.id===playerId)!;p.hand=['N07','N08','N09','N10','N15','N16','N17','F03'].map((id,i)=>({id:`layout-hand-${playerId}-${i}`,definitionId:id,kind:'card' as const,taxes:[],knownTo:[]}));p.timeRemaining=8;
 }s.activePlayerId='p1';s.events=[];s.eventSequence=0;s.version=0;}
 const view=getView(s,'p1');const lesson=initial.progress?getTutorialView(s,initial.progress):undefined;if(lesson)view.legalActions=lesson.allowedCommands;
 const room={id:'layout-room',code:'VIEW88',status:'playing',mode:'bot',players:[{id:'p1',name:'排版检查',ready:true,connected:true,isBot:false},{id:'p2',name:'布局导师',ready:true,connected:true,isBot:true}],deadline:null,version:s.version,...(lesson?{tutorial:lesson}:{})};return {room,view,playerId:'p1',roomId:room.id};
}
async function fullscreenMock(page:Page,deny=false){await page.addInitScript(({deny})=>{let active:Element|null=null;Object.defineProperty(document,'fullscreenElement',{configurable:true,get:()=>active});(window as any).__fullscreenCalls=[];Element.prototype.requestFullscreen=async function(){(window as any).__fullscreenCalls.push({active:navigator.userActivation.isActive,at:performance.now()});if(deny)throw new Error('Fullscreen disabled by embedding host');active=this;document.dispatchEvent(new Event('fullscreenchange'));};document.exitFullscreen=async()=>{active=null;document.dispatchEvent(new Event('fullscreenchange'));};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)void document.exitFullscreen();});},{deny});}
async function wire(page:Page,tutorial=false,autoFullscreen=true){const table=tableFixture(tutorial);await page.route('**/api/session',route=>route.fulfill({json:{token:'layout-token',profile:{id:'layout-profile',nickname:'排版检查',offers:[]}}}));await page.route('**/api/rooms',route=>route.fulfill({json:table}));await page.route('**/api/rooms/layout-room',route=>route.fulfill({json:table}));await page.routeWebSocket('**/ws?*',socket=>socket.send(JSON.stringify({type:'state',...table})));await page.goto('/');await page.getByRole('button',{name:/先打一局/}).click();const auto=page.getByRole('checkbox',{name:'开始时进入全屏（记住我的选择）'});await expect(auto).not.toBeChecked();if(autoFullscreen)await auto.check();if(tutorial){await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:/练一招/}).click();await page.getByRole('button',{name:'开始第一课',exact:true}).click();}else await page.getByRole('button',{name:'就用这套，开始对局',exact:true}).click();await expect(page.locator('.battle-fit')).toBeVisible();await page.evaluate(()=>document.fonts.ready);return table;}
async function withinScreen(page:Page){
 // 2.2 keeps readable card sizes inside an independent horizontal hand tray.
 // Check the whole table first, then every card at its reachable scroll position.
 const report=await page.evaluate(()=>{const selectors=['.battle-page','.arena','.hand-dock','.hand-cards','.battle-unit','.hero-avatar','.offer-hand .offer-card','.education-controls','.end-turn','.tutorial-coach','.opponent-skills','.opponent-skill','.opponent-skill-effect'];const boxes=selectors.flatMap(selector=>[...document.querySelectorAll<HTMLElement>(selector)].map((el,index)=>{const r=el.getBoundingClientRect();return {selector,index,x:r.left,y:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height}}));return {width:innerWidth,height:innerHeight,scrollHeight:document.documentElement.scrollHeight,scrollWidth:document.documentElement.scrollWidth,boxes}});
 expect(report.scrollHeight,JSON.stringify(report)).toBeLessThanOrEqual(report.height+2);expect(report.scrollWidth).toBeLessThanOrEqual(report.width+2);
 for(const b of report.boxes){expect(b.y,`${b.selector}[${b.index}] top`).toBeGreaterThanOrEqual(-2);expect(b.x,`${b.selector}[${b.index}] left`).toBeGreaterThanOrEqual(-2);expect(b.right,`${b.selector}[${b.index}] right`).toBeLessThanOrEqual(report.width+2);expect(b.bottom,`${b.selector}[${b.index}] bottom`).toBeLessThanOrEqual(report.height+2);}
 for(const card of await page.locator('.hand-card-wrapper .common-card').all()){
  await card.scrollIntoViewIfNeeded();const box=await card.boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(-2);expect(box!.x+box!.width).toBeLessThanOrEqual(report.width+2);expect(box!.y).toBeGreaterThanOrEqual(-2);expect(box!.y+box!.height).toBeLessThanOrEqual(report.height+2);
  const text=await card.evaluate(el=>({title:parseFloat(getComputedStyle(el.querySelector('.card-ribbon')!).fontSize),summary:parseFloat(getComputedStyle(el.querySelector(':scope > p')!).fontSize),scrollX,scrollY}));expect(text.title).toBeGreaterThanOrEqual(13);expect(text.summary).toBeGreaterThanOrEqual(12);expect(text.scrollX).toBe(0);expect(text.scrollY).toBe(0);
 }
 return report;
}

for(const [width,height,tutorial]of [[1440,900,false],[1366,768,false],[1024,768,false],[1366,768,true],[1024,768,true]] as const)test(`fullscreen ${width}x${height}${tutorial?' tutorial':''}: user gesture and whole table stays in one viewport`,async({page})=>{
 await page.setViewportSize({width,height});await fullscreenMock(page);await wire(page,tutorial);await expect(page.getByRole('button',{name:'退出全屏',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).__fullscreenCalls[0].active)).toBe(true);await withinScreen(page);if(tutorial){const arenaBefore=await page.locator('.arena').boundingBox();await page.getByRole('button',{name:'给我提示',exact:true}).click();await expect(page.locator('.coach-hint')).toBeVisible();await withinScreen(page);expect(await page.locator('.arena').boundingBox()).toEqual(arenaBefore);const sizes=await page.locator('.tutorial-coach').evaluate(el=>({line:parseFloat(getComputedStyle(el.querySelector('.coach-message>p')!).fontSize),goal:parseFloat(getComputedStyle(el.querySelector('.coach-message>strong')!).fontSize)}));expect(sizes.line).toBeGreaterThanOrEqual(14);expect(sizes.goal).toBeGreaterThanOrEqual(13);await page.getByRole('button',{name:'收起提示',exact:true}).click();}const skillBottom=await page.locator('.opponent-skills').evaluate(el=>el.getBoundingClientRect().bottom),enemyTop=await page.locator('.enemy-row').evaluate(el=>Math.min(...[...el.children].map(n=>n.getBoundingClientRect().top)));expect(skillBottom).toBeLessThanOrEqual(enemyTop+2);if(!tutorial){if(!await page.locator('.offer-hand').count())await page.getByRole('button',{name:/我的 Offer/}).click();await expect(page.locator('.battle-unit')).toHaveCount(8);await expect(page.locator('.offer-hand .offer-card')).toHaveCount(3);await expect(page.locator('.hand-card-wrapper')).toHaveCount(8);}
 await mkdir('evidence/screenshots/fullscreen',{recursive:true});await page.screenshot({path:`evidence/screenshots/fullscreen/table-${width}-${height}${tutorial?'-tutorial':''}.png`});await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'进入全屏',exact:true})).toBeVisible();await withinScreen(page);await page.getByRole('button',{name:'进入全屏',exact:true}).click();await expect(page.getByRole('button',{name:'退出全屏',exact:true})).toBeVisible();
});
test('fullscreen rejection gracefully keeps a complete immersive table and no uncaught error',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1366,height:768});await fullscreenMock(page,true);await wire(page);await expect(page.getByRole('button',{name:'进入全屏',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).__fullscreenCalls)).toEqual([{active:true,at:expect.any(Number)}]);await withinScreen(page);await page.getByRole('button',{name:'进入全屏',exact:true}).click();expect(await page.evaluate(()=>(window as any).__fullscreenCalls.length)).toBe(2);await withinScreen(page);expect(errors).toEqual([]);});

test('default start keeps fullscreen optional and the explicit button uses a real user gesture',async({page})=>{await fullscreenMock(page);await wire(page,false,false);expect(await page.evaluate(()=>(window as any).__fullscreenCalls)).toHaveLength(0);await expect(page.getByRole('button',{name:'进入全屏',exact:true})).toBeVisible();await page.getByRole('button',{name:'进入全屏',exact:true}).click();await expect(page.getByRole('button',{name:'退出全屏',exact:true})).toBeVisible();expect(await page.evaluate(()=>(window as any).__fullscreenCalls[0].active)).toBe(true);await withinScreen(page);});

test('portrait tutorial keeps natural vertical scrolling and an independent readable hand tray',async({page})=>{
 await page.setViewportSize({width:390,height:844});await fullscreenMock(page);await wire(page,true,false);
 for(const selector of ['.end-turn','.hand-cards']){const target=page.locator(selector);await target.scrollIntoViewIfNeeded();const box=await target.boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(-2);expect(box!.x+box!.width).toBeLessThanOrEqual(392);expect(box!.y+box!.height).toBeLessThanOrEqual(846);}
 const metrics=await page.evaluate(()=>({scrollHeight:document.documentElement.scrollHeight,scrollWidth:document.documentElement.scrollWidth,handOverflow:getComputedStyle(document.querySelector('.hand-cards')!).overflowX,bodyOverflow:getComputedStyle(document.body).overflowY}));expect(metrics.scrollHeight).toBeGreaterThan(844);expect(metrics.scrollWidth).toBeLessThanOrEqual(392);expect(metrics.handOverflow).toBe('auto');expect(metrics.bodyOverflow).not.toBe('hidden');
});
