import{test,expect}from'@playwright/test';
import{getStarterDecks}from'../../src/game/starterDecks';
test('new visitors receive an editable starter, preview is harmless and applying changes the full loadout',async({page})=>{
 await page.goto('/');await page.locator('.hotspot-play').click();const picker=page.getByRole('region',{name:'预设卡组'});await expect(picker).toContainText('5 套可选');const select=page.getByLabel('选择预设卡组');await expect(select.locator('option')).toHaveCount(5);const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('offer-loadout')!));expect([before.primaryId,before.secondaryId]).toEqual(['H05','S05']);
 const next=getStarterDecks(false)[2];await select.selectOption(next.id);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('offer-loadout')!).primaryId)).toBe(before.primaryId);await picker.getByRole('button',{name:'应用这套预设'}).click();await expect(picker.getByRole('button',{name:'正在使用'})).toBeDisabled();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('offer-loadout')!));expect([after.primaryId,after.secondaryId]).toEqual([next.primaryId,next.secondaryId]);expect(after.baseDeck).toEqual(next.loadout.baseDeck);expect(after.flexDeck).toEqual(next.loadout.flexDeck);expect(after.offers.map((o:any)=>o.id)).toEqual(next.loadout.offers.map(o=>o.id));
});
test('sixth starter stays absent until the school input unlocks it',async({page})=>{
 await page.goto('/');await page.locator('.hotspot-loadout').click();await expect(page.locator('.starter-choices>button')).toHaveCount(5);const hidden=getStarterDecks(true).at(-1)!;await expect(page.getByText(hidden.title,{exact:true})).toHaveCount(0);await page.getByLabel('你的学校',{exact:true}).fill(String.fromCodePoint(0x5409,0x5927));await expect(page.locator('.starter-choices>button')).toHaveCount(6);await page.locator('.starter-choices>button').last().click();await page.getByRole('button',{name:'应用这套预设'}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('offer-loadout')!));expect([saved.primaryId,saved.secondaryId]).toEqual(['H10','S07']);await page.reload();await page.locator('.hotspot-loadout').click();await expect(page.locator('.starter-choices>button')).toHaveCount(6);
});
