import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CueCursor,groupBattleCues,boundedQueue,flightPoint} from '../src/components/battle-motion';
import type {BattleCue} from '../src/game/types';
const cue=(sequence:number,kind:BattleCue['kind']='damage'):BattleCue=>({id:`m:${sequence}`,sequence,kind} as BattleCue);
test('motion cursor skips history and repeated/out-of-order snapshots, then accepts only new events',()=>{const cursor=new CueCursor();assert.deepEqual(cursor.consume('m',[cue(3),cue(4)]),[]);assert.deepEqual(cursor.consume('m',[cue(4),cue(6),cue(5)]).map(c=>c.sequence),[5,6]);assert.deepEqual(cursor.consume('m',[cue(2),cue(5)]),[]);assert.equal(cursor.sequence,6);assert.deepEqual(cursor.consume('m',[cue(6),cue(7)]).map(c=>c.sequence),[7]);});
test('new match resets the event cursor without replaying its initial history',()=>{const cursor=new CueCursor();cursor.consume('old',[cue(40)]);assert.deepEqual(cursor.consume('new',[cue(0)]),[]);assert.deepEqual(cursor.consume('new',[cue(1)]).map(c=>c.sequence),[1]);});
test('simultaneous attack damage and retirement stay in one animation group',()=>{const groups=groupBattleCues([cue(1,'attack'),cue(2,'damage'),cue(3,'damage'),cue(4,'retire'),cue(5,'turn')]);assert.equal(groups.length,1);assert.deepEqual(groups[0].cues.map(c=>c.kind),['attack','damage','damage','retire']);assert.equal(groups[0].duration,1180);assert.equal(groupBattleCues([cue(1,'attack')],true)[0].duration,100);});
test('a burst of catch-up events keeps at most three recent animation groups',()=>{const all=groupBattleCues([1,2,3,4,5].map(n=>cue(n,'card')));assert.deepEqual(boundedQueue(all.slice(0,2),all.slice(2)).map(g=>g.id),['m:3','m:4','m:5']);});
test('flight follows the actual source and target centers and clamps progress',()=>{const from={x:13,y:240},to={x:231,y:45};assert.deepEqual(flightPoint(from,to,-1),from);const end=flightPoint(from,to,2);assert.ok(Math.abs(end.x-to.x)<1e-9);assert.equal(end.y,to.y);assert.notEqual(flightPoint(from,to,.5).x,(from.x+to.x)/2);});
test('ending is a separate final group after lethal damage and retirement, including catch-up',()=>{
 const result={...cue(6,'result'),effectId:'winner'};
 const groups=groupBattleCues([cue(1,'card'),cue(2,'deploy'),cue(3,'attack'),cue(4,'damage'),cue(5,'retire'),result]);
 assert.deepEqual(groups.at(-2)?.cues.map(c=>c.kind),['attack','damage','retire']);
 assert.equal(groups.at(-2)?.duration,1180);
 assert.deepEqual(groups.at(-1)?.cues,[result]);assert.equal(groups.at(-1)?.duration,650);
 assert.equal(boundedQueue([],groups).at(-1)?.cues[0].kind,'result');
 assert.equal(groupBattleCues([result],true)[0].duration,100);
 assert.equal(groupBattleCues([{...result,effectId:'draw'}])[0].duration,650);
});
