import {test} from 'node:test';import assert from 'node:assert/strict';
import {createMatch,defaultLoadout,getView,applyCommand,decideBotCommand,createBotKnowledge,updateBotKnowledge} from '../src/game/index';
import {sampleObservation,stateKey} from '../src/game/ai/belief';
import {arena,unit,hand,offer,observe} from './bot-fixtures';

test('setup enumerates 20 flex sets and 7/11 complete mulligan choices',()=>{let s=createMatch([defaultLoadout('a','甲'),defaultLoadout('b','乙')],91);for(const p of s.players){const view=getView(s,p.id);assert.equal(view.legalActions.length,20);assert.equal(new Set(view.legalActions.map(c=>JSON.stringify(c.flexIds))).size,20);const d=decideBotCommand({view,difficulty:'normal',style:'control',botSeed:1,requestId:'setup'});const r=applyCommand(s,p.id,d.command);assert.equal(r.error,undefined);s=r.state}for(const p of s.players)assert.equal(getView(s,p.id).legalActions.length,p.hand.length===3?7:11)});
test('fixed legal observations, node budgets and bot seed yield identical root decisions',()=>{const s=arena();unit(s);unit(s,'b',4,7);hand(s,'N07');s.players[1].retort={id:'secret',definitionId:'F04',kind:'card',taxes:[],knownTo:[]};hand(s,'N10','b');const hidden=structuredClone(s);hidden.rngState=987654321;hidden.players[0].deck.reverse();hidden.players[1].deck.reverse();hidden.players[1].hand[0].definitionId='N21';hidden.players[1].retort!.definitionId='N23';const a=observe(s),b=observe(hidden);assert.deepEqual(a,b);for(const difficulty of ['easy','normal','hard','expert'] as const){const req={difficulty,style:'growth' as const,botSeed:90,requestId:'same',budget:{maxMs:Infinity}};const x=decideBotCommand({...req,view:a}),y=decideBotCommand({...req,view:b});assert.deepEqual(x.command,y.command);assert.equal(x.nodesVisited,y.nodesVisited);assert.deepEqual(x.principalVariation,y.principalVariation)}});
test('all simulations including responses and beliefs share one fixed node budget',()=>{const s=arena();s.players[0].education.usedThisOwnTurn=false;for(let i=0;i<3;i++){unit(s,'a',3,4);unit(s,'b',2,5)}for(const id of ['N07','N10','N16','N18'])hand(s,id);offer(s,'T07');for(const maxNodes of [1,10,80,300]){const d=decideBotCommand({view:observe(s),difficulty:'expert',style:'control',botSeed:19,requestId:'budget',budget:{maxNodes,maxMs:Infinity}});assert.ok(d.nodesVisited<=maxNodes,JSON.stringify(d));assert.equal(applyCommand(s,'a',d.command).error,undefined)}});
test('simulation stops at unknown draws and newly revealed hand choices',()=>{const s=arena('H01');s.players[0].education.usedThisOwnTurn=false;hand(s,'N07','b');hand(s,'N04');const d=decideBotCommand({view:observe(s),difficulty:'expert',style:'control',botSeed:1,requestId:'boundary',budget:{maxMs:Infinity}});const drawIndex=d.principalVariation.findIndex(c=>c.cardId===s.players[0].hand[0].id||c.type==='USE_PRIMARY');if(drawIndex>=0)assert.equal(drawIndex,d.principalVariation.length-1)});
test('full simulation key distinguishes notifications, attack use, deck order and choices',()=>{const s=arena();unit(s);const initial=stateKey(s);for(const change of [(x:typeof s)=>x.players[0].board[0].attacked=true,(x:typeof s)=>x.players[0].board[0].notice={by:'b',turn:4},(x:typeof s)=>x.players[0].deck.reverse(),(x:typeof s)=>x.rngState++]){const x=structuredClone(s);change(x);assert.notEqual(stateKey(x),initial)}});
test('knowledge uses only legitimately visible hand and conservatively invalidates sorted cards',()=>{const s=arena();hand(s,'N07','b');let view=observe(s);let k=createBotKnowledge(view);assert.deepEqual(updateBotKnowledge(k,view).knownEnemyHand,[]);s.players[1].hand[0].knownTo=['a'];view=observe(s);k=updateBotKnowledge(k,view);assert.equal(k.knownEnemyHand.length,1);k.knownTop=[s.players[0].deck[0]];s.version++;s.players[1].hand[0].knownTo=[];k=updateBotKnowledge(k,observe(s));assert.deepEqual(k.knownTop,[]);assert.deepEqual(k.knownEnemyHand,[])});
test('belief reconstruction is detached from input and contains no battle RNG or true deck order',()=>{const s=arena();const view=observe(s),copy=structuredClone(view);const simulated=sampleObservation(view,undefined,717);assert.notEqual(simulated.rngState,s.rngState);assert.notDeepEqual(simulated.players[0].deck,s.players[0].deck);simulated.players[0].mind=1;assert.deepEqual(view,copy)});
test('safe initial action wins ties against an immediate loss even when every future line loses',()=>{const s=arena();s.players[0].mind=1;s.players[0].deck=[];s.firstPlayerId='b';s.round=12;s.players[1].mind=30;unit(s,'a',1,10);const d=decideBotCommand({view:observe(s),difficulty:'normal',style:'control',botSeed:1,requestId:'avoid',budget:{maxMs:Infinity}});assert.equal(d.command.type,'ATTACK');assert.equal(applyCommand(s,'a',d.command).state.result,null)});
