import {test} from 'node:test';import assert from 'node:assert/strict';
import {chooseLegacyBotCommand,decideBotCommand,applyCommand} from '../src/game/index';
import {arena,unit,hand,offer,run,observe} from './bot-fixtures';
import type {MatchState} from '../src/game/types';
import type {BotDifficulty} from '../src/game/ai';
const decide=(s:MatchState,difficulty:BotDifficulty='normal')=>decideBotCommand({view:observe(s),difficulty,style:'control',botSeed:113,requestId:'regression',budget:{maxMs:Infinity}});
const safe=(s:MatchState)=>{for(const difficulty of ['easy','normal','hard','expert'] as const){const d=decide(s,difficulty);const result=run(s,d.command);assert.notEqual(result.result?.winnerId,'b',difficulty+' '+JSON.stringify(d));}};

test('P01 legacy drops T07 target; upgraded policy resolves actual enter damage',()=>{const s=arena();s.players[0].timeRemaining=4;const target=unit(s,'b',6,2);offer(s,'T07');assert.equal(chooseLegacyBotCommand(observe(s),'control').targetId,undefined);const d=decide(s);assert.equal(d.command.type,'DEPLOY_OFFER');assert.equal(d.command.targetId,target.id);assert.equal(run(s,d.command).players[1].board.length,0)});
test('P02 legacy drops T05 target; upgraded policy reinforces an existing unit',()=>{const s=arena();const target=unit(s,'a',4,4,{attacked:true});offer(s,'T05');s.players[0].timeRemaining=4;assert.equal(chooseLegacyBotCommand(observe(s),'control').targetId,undefined);const d=decide(s);assert.equal(d.command.type,'DEPLOY_OFFER');assert.equal(d.command.targetId,target.id)});
test('P03 legacy chooses one S08 target; upgraded policy evaluates both selected units',()=>{const s=arena('H03','S08');s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=2;unit(s,'a',2,4,{attacked:true});unit(s,'a',3,4,{attacked:true});assert.equal(chooseLegacyBotCommand(observe(s),'control').targetIds,undefined);const d=decide(s);assert.equal(d.command.type,'USE_SECONDARY');assert.equal(d.command.targetIds?.length,2)});
test('P04 985 skill then 5+2 attack is a real lethal combo',()=>{const s=arena();s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=1;s.players[1].mind=7;unit(s);assert.equal(chooseLegacyBotCommand(observe(s),'control').type,'ATTACK');const d=decide(s);assert.equal(d.command.type,'USE_PRIMARY');assert.equal(d.reasonCode,'LETHAL_COMBO');let state=s;for(const c of d.principalVariation)state=run(state,c);assert.equal(state.result?.winnerId,'a')});
test('P05 N15, P06 S03 and frontline attacks never choose avoidable immediate self defeat',()=>{let s=arena();s.players[0].mind=2;unit(s,'a',3,4,{attacked:true});hand(s,'N15');assert.equal(chooseLegacyBotCommand(observe(s),'control').type,'PLAY_CARD');safe(s);s=arena('H03','S03');s.players[0].mind=1;s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=2;unit(s,'a',3,4,{attacked:true});assert.equal(chooseLegacyBotCommand(observe(s),'control').type,'USE_SECONDARY');safe(s);s=arena();s.players[0].mind=1;unit(s,'a',4,4,{tags:['frontline']});safe(s)});
test('P07 N04, T09, B05 and draw actions account for fatal empty-deck fatigue',()=>{for(const kind of ['N04','T09','B05','N09']){const s=arena();s.players[0].mind=1;s.players[0].deck=[];if(kind==='T09')offer(s,kind);else if(kind==='B05')offer(s,'T05',4,'a','B05');else hand(s,kind);if(kind==='N04')assert.equal(chooseLegacyBotCommand(observe(s),'control').type,'PLAY_CARD');safe(s)}});
test('T08 freezes the real threatening enemy target',()=>{const s=arena();const t=unit(s,'b',8,8);offer(s,'T08');const d=decide(s);assert.equal(d.command.targetId,t.id);assert.equal(run(s,d.command).players[1].board[0].frozenUntilTurn,4)});
test('T03 and N06 can skip a harmful friendly return',()=>{for(const def of ['T03','N06']){const s=arena();unit(s,'a',7,9,{attacked:true});if(def==='T03')offer(s,def);else hand(s,def);const d=decide(s);assert.equal(d.command.targetId,undefined,JSON.stringify(d));assert.ok(['DEPLOY_OFFER','PLAY_CARD'].includes(d.command.type))}});
test('two damage cards remove a blocking unit before lethal face damage',()=>{const s=arena();unit(s,'a',7,8);unit(s,'b',1,4,{taunt:true});s.players[1].mind=7;hand(s,'N07');hand(s,'N07');const d=decide(s);assert.equal(d.reasonCode,'LETHAL_COMBO',JSON.stringify(d));let state=s;for(const c of d.principalVariation)state=run(state,c);assert.equal(state.result?.winnerId,'a');assert.equal(d.principalVariation.filter(c=>c.type==='PLAY_CARD').length,2)});
test('Offer death loses 2 mind and can complete a winning trade',()=>{let s=arena();const id=offer(s,'T05',2,'b');s=run(s,{type:'END_TURN'});s=run(s,{type:'DEPLOY_OFFER',offerId:id},'b');s=run(s,{type:'END_TURN'},'b');s.players[1].mind=2;unit(s,'a',5,8);const d=decide(s);assert.equal(d.command.type,'ATTACK');assert.equal(run(s,d.command).result?.winnerId,'a')});
test('covered retorts prevent false unconditional lethal claims',()=>{const s=arena();unit(s,'a',5,8);s.players[1].mind=5;s.players[1].retort={id:'hidden-retort',definitionId:'F06',kind:'card',taxes:[],knownTo:[]};const d=decide(s,'expert');assert.notEqual(d.reasonCode,'IMMEDIATE_WIN');assert.notEqual(d.reasonCode,'LETHAL_COMBO');assert.ok(d.sampleCount>=3)});
test('round twelve uses real end-turn mind adjudication',()=>{const s=arena();s.round=12;s.firstPlayerId='b';s.players[0].mind=25;s.players[1].mind=20;unit(s,'b',15,15);const d=decide(s);assert.equal(d.command.type,'END_TURN');assert.equal(run(s,d.command).result?.winnerId,'a')});
test('attack first, then return a noticed Offer instead of losing its available attack',()=>{let s=arena();const id=offer(s,'T05',2);s=run(s,{type:'DEPLOY_OFFER',offerId:id});const u=s.players[0].board[0];u.deployedTurn=1;u.ageStage=3;u.tags=['frontline'];u.notice={by:'b',turn:4};s.players[0].offerZone[0].ageStage=3;s.players[0].timeRemaining=2;s.players[0].mind=3;hand(s,'N13');const d=decide(s);assert.equal(d.command.type,'ATTACK',JSON.stringify(d));assert.ok(d.principalVariation.some(c=>c.type==='PLAY_CARD'));const after=run(run(s,d.command),d.principalVariation[1]);assert.equal(after.players[0].board.length,0);assert.ok(after.players[0].hand.some(c=>c.kind==='offer'))});
test('clear friendly space before deploying an enter-damage winning Offer',()=>{const s=arena();for(let i=0;i<4;i++)unit(s,'a',1,2,{attacked:true});const foe=offer(s,'T05',2,'b');s.players[1].offerZone[0].status='board';unit(s,'b',1,5,{kind:'offer',offerId:foe,templateId:'T05'});s.players[1].mind=2;s.players[0].timeRemaining=5;hand(s,'N19');offer(s,'T07',1);const d=decide(s);assert.equal(d.command.type,'PLAY_CARD');assert.equal(d.reasonCode,'LETHAL_COMBO',JSON.stringify(d));let end=s;for(const c of d.principalVariation)end=run(end,c);assert.equal(end.result?.winnerId,'a')});
test('negotiation can save time for a necessary defensive second card even when full price is affordable',()=>{const s=arena();s.players[0].timeRemaining=4;s.players[0].mind=5;unit(s,'b',8,2);unit(s,'b',8,8);offer(s,'T07',4);offer(s,'T05',6);hand(s,'N11');const d=decide(s,'hard');assert.ok(d.principalVariation.some(c=>c.type==='NEGOTIATE'),JSON.stringify(d));assert.ok(d.principalVariation.some(c=>c.type==='PLAY_CARD'),JSON.stringify(d))});
test('topic changes evaluate both sides instead of always preferring future',()=>{const s=arena();s.topic='salary';const self=offer(s,'T05',2),enemy=offer(s,'T05',6,'b');s.players[0].offerZone[0].status='board';s.players[1].offerZone[0].status='board';unit(s,'a',3,4,{kind:'offer',offerId:self,templateId:'T05',attacked:true});unit(s,'b',5,5,{kind:'offer',offerId:enemy,templateId:'T05',originalTime:6});hand(s,'F05');s.players[0].timeRemaining=1;const d=decide(s);assert.equal(d.command.type,'PLAY_CARD');assert.notEqual(d.command.topic,'salary')});
test('tax choice targets an affordable lethal card instead of blindly selecting the highest cost',()=>{let s=arena('H01');s.round=2;s.players[0].education.usedThisOwnTurn=false;s.players[0].mind=3;s.players[0].timeRemaining=2;hand(s,'N21','b');const lethal=hand(s,'N22','b');s=run(s,{type:'USE_PRIMARY'});const d=decide(s);assert.equal(d.command.type,'RESOLVE_CHOICE');assert.equal(d.command.optionId,lethal)});
test('consult choice takes a cheap answer that immediately removes a fatal Offer',()=>{const s=arena();const foe=offer(s,'T05',2,'b');s.players[1].offerZone[0].status='board';unit(s,'b',8,2,{kind:'offer',offerId:foe,templateId:'T05'});s.players[1].mind=2;s.players[0].timeRemaining=1;const cards=['N21','N07'].map((definitionId,i)=>({id:`consult-${i}`,definitionId,kind:'card' as const,taxes:[],knownTo:[]}));s.players[0].deck=cards;s.pendingChoice={id:'consult',ownerId:'a',kind:'consult',options:cards.map(card=>({id:card.id,label:card.definitionId,card}))};const d=decide(s);assert.equal(d.command.optionId,'consult-1');assert.equal(d.reasonCode,'LETHAL_COMBO')});
test('management cancels the pending frontline retirement at the actual turn boundary',()=>{let s=arena();const id=offer(s,'T05',2);s=run(s,{type:'DEPLOY_OFFER',offerId:id});const u=s.players[0].board[0];u.ageStage=3;u.tags=['frontline'];u.attacked=true;u.notice={by:'b',turn:4};s.players[0].mind=2;s.players[0].timeRemaining=2;hand(s,'F03');const d=decide(s);assert.equal(d.command.type,'PLAY_CARD');s=run(s,d.command);s=run(s,{type:'END_TURN'});assert.equal(s.players[0].board.length,1);assert.equal(s.players[0].board[0].notice,undefined);assert.equal(s.players[0].board[0].managed,true);assert.equal(s.result,null)});
test('all seven supplied legacy defects reproduce across all three original styles (21 probes)',()=>{
 const probes=[
  ()=>{const s=arena();s.players[0].timeRemaining=4;unit(s,'b',6,2);offer(s,'T07');return {s,bad:(c:any)=>c.type==='DEPLOY_OFFER'&&!c.targetId}},
  ()=>{const s=arena();unit(s,'a',4,4,{attacked:true});offer(s,'T05');s.players[0].timeRemaining=4;return {s,bad:(c:any)=>c.type==='DEPLOY_OFFER'&&!c.targetId}},
  ()=>{const s=arena('H03','S08');s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=2;unit(s,'a',2,4,{attacked:true});unit(s,'a',3,4,{attacked:true});return {s,bad:(c:any)=>c.type==='USE_SECONDARY'&&!c.targetIds}},
  ()=>{const s=arena();s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=1;s.players[1].mind=7;unit(s);return {s,bad:(c:any)=>c.type==='ATTACK'}},
  ()=>{const s=arena();s.players[0].mind=2;unit(s,'a',3,4,{attacked:true});hand(s,'N15');return {s,bad:(c:any)=>c.type==='PLAY_CARD'}},
  ()=>{const s=arena('H03','S03');s.players[0].mind=1;s.players[0].education.usedThisOwnTurn=false;s.players[0].timeRemaining=2;unit(s,'a',3,4,{attacked:true});return {s,bad:(c:any)=>c.type==='USE_SECONDARY'}},
  ()=>{const s=arena();s.players[0].mind=1;s.players[0].deck=[];hand(s,'N04');return {s,bad:(c:any)=>c.type==='PLAY_CARD'}},
 ];
 for(const [index,probe]of probes.entries())for(const style of ['aggressive','control','growth'] as const){const {s,bad}=probe(),view=observe(s);assert.equal(bad(chooseLegacyBotCommand(view,style)),true,`P0${index+1} ${style} legacy`);const upgraded=decideBotCommand({view,difficulty:'normal',style,botSeed:113,requestId:'all-probes',budget:{maxMs:Infinity}});assert.equal(bad(upgraded.command),false,`P0${index+1} ${style} upgraded ${JSON.stringify(upgraded.command)}`);assert.equal(applyCommand(s,'a',upgraded.command).error,undefined)}
});
