import {test} from 'node:test';import assert from 'node:assert/strict';
import {BotWorkerClient,type BotWorkerPort} from '../src/workers/bot-client';
import {createNodeBotRunner} from '../server/bot-runner';
import {decideBotCommand} from '../src/game/ai';
import {arena,observe} from './bot-fixtures';
const request=(id:string)=>({view:observe(arena()),difficulty:'normal' as const,style:'control' as const,botSeed:1,requestId:id});
test('worker cancellation terminates CPU and drops the abandoned request',async()=>{const ports:(BotWorkerPort&{terminated:boolean})[]=[];const c=new BotWorkerClient(()=>{const p={onmessage:null,onerror:null,postMessage(){},terminate(){p.terminated=true},terminated:false};ports.push(p);return p});const old=request('old'),fresh=request('new');const a=c.request(old),b=c.request(fresh);assert.equal(await a,null);assert.equal(ports[0].terminated,true);ports[0].onmessage?.({data:{ok:true,decision:decideBotCommand(old)}} as MessageEvent);ports[1].onmessage?.({data:{ok:true,decision:decideBotCommand(fresh)}} as MessageEvent);assert.equal((await b)?.requestId,'new');assert.equal(ports[1].terminated,true);c.cancel()});
test('bad worker versions and exceptions fall back with explicit diagnostics',async()=>{let port:BotWorkerPort;const c=new BotWorkerClient(()=>port={onmessage:null,onerror:null,postMessage(){},terminate(){}});const r=request('version');const p=c.request(r);port!.onmessage?.({data:{ok:true,decision:{...decideBotCommand(r),stateVersion:999}}} as MessageEvent);const d=await p;assert.equal(d?.fallbackReason,'worker-error');assert.equal(d?.stateVersion,r.view.version);c.cancel()});
test('Node worker executes the same strategy contract off the main thread',async()=>{const c=createNodeBotRunner();try{const r=request('node-worker'),decision=await c.request(r);assert.equal(decision?.requestId,'node-worker');assert.notEqual(decision?.fallbackReason,'worker-error');assert.deepEqual(decision?.command,decideBotCommand(r).command)}finally{c.cancel()}});
