import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MotionDirector,type MotionContext} from '../src/motion/MotionDirector';
import {MOTION_CUES} from '../src/motion/cues';
const defaults={preference:'system' as const,reduced:false,ambientPaused:false,quality:'full' as const,hidden:false};
function clock(){let now=0,id=0;const tasks=new Map<number,{at:number;fn:()=>void}>();return {scheduler:{now:()=>now,set:(fn:()=>void,ms:number)=>{tasks.set(++id,{at:now+ms,fn});return id},clear:(key:unknown)=>{tasks.delete(key as number)}},advance(ms:number){const end=now+ms;for(;;){const next=[...tasks].filter(([,task])=>task.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;now=next[1].at;tasks.delete(next[0]);next[1].fn()}now=end},pending:()=>tasks.size}}
test('motion catalog defines exactly forty original planned cues across five channels',()=>{assert.equal(MOTION_CUES.length,40);assert.equal(new Set(MOTION_CUES.map(cue=>cue.key)).size,40);assert.equal(new Set(MOTION_CUES.map(cue=>cue.channel)).size,5)});
test('director deduplicates accepted event/channel keys without repeating their visual work',async()=>{const time=clock(),director=new MotionDirector(time.scheduler);let starts=0;const request={cue:'attack' as const,id:'match:42',scope:'battle:m',confirmed:true,run:()=>{starts++}};const first=director.play(request),duplicate=director.play(request);assert.equal(await duplicate.finished,'duplicate');assert.equal(starts,1);time.advance(1180);assert.equal(await first.finished,'finished');assert.equal(director.diagnostics().active,0);assert.equal(time.pending(),0)});
test('formal motion waits for confirmation and performs no speculative visual change',async()=>{const director=new MotionDirector(clock().scheduler);let touched=false;const handle=director.play({cue:'deploy',id:'42',scope:'m',run:()=>{touched=true}});assert.equal(await handle.finished,'unconfirmed');assert.equal(touched,false)});
test('latest navigation cancels delayed callbacks, animations and previous cleanup exactly once',async()=>{const time=clock(),director=new MotionDirector(time.scheduler);let stale=0,cleanup=0;const first=director.play({cue:'panelOpen',id:'one',scope:'page1',run:ctx=>{ctx.later(()=>stale++,150);return()=>{cleanup++}}});director.play({cue:'creatorUnfold',id:'two',scope:'page2',run:()=>{}});assert.equal(await first.finished,'superseded');time.advance(500);assert.equal(stale,0);assert.equal(cleanup,1);assert.equal(time.pending(),0)});
test('battle backlogs play every blow, speed up after 5200ms instead of flashing, and catch up after 9000ms without rule work',async()=>{const time=clock(),director=new MotionDirector(time.scheduler),durations:number[]=[];for(let i=0;i<6;i++)director.play({cue:'attack',id:String(i),scope:'m',confirmed:true,durationMs:960,run:ctx=>{durations.push(ctx.durationMs)}});assert.equal(director.diagnostics().compressed,1);time.advance(4000);assert.deepEqual(durations,[960,576,576,576,576,576]);let start=false;director.play({cue:'attack',id:'long1',scope:'late',confirmed:true,durationMs:5000,run:()=>{}});const next=director.play({cue:'attack',id:'long2',scope:'late',confirmed:true,durationMs:4500,run:()=>{start=true}});assert.equal(await next.finished,'catch-up');assert.equal(start,false);assert.equal(director.diagnostics().caughtUp,1);assert.equal(time.pending(),0)});
test('visibility and reduced preference cancel resources while keeping the user preference authoritative',async()=>{const time=clock(),director=new MotionDirector(time.scheduler);let duration=0;const first=director.play({cue:'idleSway',id:'idle',scope:'home',run:ctx=>ctx.later(()=>{},1000)});director.setPreferences({...defaults,hidden:true});assert.equal(await first.finished,'hidden');assert.equal(time.pending(),0);director.setPreferences({...defaults,preference:'reduced',reduced:true,quality:'compact'});const reduced=director.play({cue:'attack',id:'hit',scope:'m',confirmed:true,run:ctx=>{duration=ctx.durationMs;assert.equal(ctx.reduced,true)}});assert.equal(duration,100);time.advance(100);assert.equal(await reduced.finished,'finished');const idle=director.play({cue:'idleSway',id:'idle2',scope:'home',run:()=>assert.fail('Reduced mode must not start ambient movement')});assert.equal(await idle.finished,'hidden')});
test('a failed visual callback always settles its channel and lets later navigation run',async()=>{const time=clock(),director=new MotionDirector(time.scheduler);const bad=director.play({cue:'panelOpen',id:'bad',scope:'a',run:ctx=>ctx.later(()=>{throw Error('asset rejected')},20)});time.advance(20);assert.equal(await bad.finished,'error');let worked=false;director.play({cue:'panelOpen',id:'next',scope:'b',run:()=>{worked=true}});time.advance(300);assert.equal(worked,true);assert.equal(director.diagnostics().errors,1);assert.equal(time.pending(),0)});
test('ten independent match scopes release all delayed callbacks and active resources',()=>{const time=clock(),director=new MotionDirector(time.scheduler);for(let i=0;i<10;i++){director.play({cue:'attack',id:'1',scope:`match:${i}`,confirmed:true,run:ctx=>ctx.later(()=>{},200)});director.cancelScope(`match:${i}`);assert.equal(director.diagnostics().active,0);assert.equal(director.diagnostics().queued,0);assert.equal(director.diagnostics().timers,0);assert.equal(time.pending(),0)}director.dispose()});
test('direct pointer drag stays owned until release even when reduced, then releases resources on hidden',async()=>{const time=clock(),director=new MotionDirector(time.scheduler,{...defaults,reduced:true,preference:'reduced'});let clean=0;const drag=director.play({cue:'dragFollow',id:'pointer',scope:'drag',hold:true,run:ctx=>ctx.addCleanup(()=>clean++)});time.advance(1000);assert.equal(director.diagnostics().active,1);director.setPreferences({...defaults,hidden:true,reduced:true});assert.equal(await drag.finished,'hidden');assert.equal(clean,1);assert.equal(time.pending(),0);assert.equal(director.diagnostics().active,0)});
