import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {currentLoadout,historicalLoadout,upgradeOfferCollection} from '../src/game/offer-compat';
import {compileOffer,createMatch,applyCommand,getView} from '../src/game/index';
import type {MatchState,Loadout,Command} from '../src/game/types';

interface RecordInput {initialState:MatchState;loadouts:[Loadout,Loadout];seed:number;journal:{actorId:string;command:Command}[]}

// Captured using the committed 2.0 compiler, not generated by the implementation under test.
const golden=JSON.parse(readFileSync(new URL('./fixtures/legacy-offer-record.json',import.meta.url),'utf8')) as RecordInput;

test('historical compiler reconstructs the original 2.0 snapshot and 48-command golden replay',()=>{
  const loadouts=golden.loadouts!.map(historicalLoadout) as NonNullable<RecordInput['loadouts']>;
  assert.deepEqual(loadouts,golden.loadouts);
  assert.equal(loadouts[0].offers[0].definitionHash,'59535cef');
  assert.deepEqual(createMatch(loadouts,golden.seed,{skipSetup:true,matchId:golden.initialState.matchId}),golden.initialState);
  let state=golden.initialState;
  for(const entry of golden.journal){const next=applyCommand(state,entry.actorId,entry.command);assert.equal(next.error,undefined);state=next.state;}
  assert.equal(state.phase,'finished');assert.equal(golden.journal.length,48);
});

test('new matches recompile legacy and forged definitions without changing historical snapshots',()=>{
  const old=structuredClone(golden.loadouts![0]);old.offers[0].artId='/api/art/legacy.webp';
  const frozen=structuredClone(old),profile={offers:[structuredClone(old.offers[0])],loadout:old};
  assert.equal(upgradeOfferCollection(profile),true);
  assert.equal(upgradeOfferCollection(profile),false,'migration is idempotent');
  assert.equal(profile.offers[0].id,frozen.offers[0].id);assert.equal(profile.offers[0].name,frozen.offers[0].name);
  assert.equal(profile.offers[0].artId,'/api/art/legacy.webp');assert.equal(profile.offers[0].rulesVersion,'2.1.0');
  assert.notEqual(profile.offers[0].definitionHash,frozen.offers[0].definitionHash);
  assert.equal(profile.loadout.offers.every(offer=>offer.rulesVersion==='2.1.0'),true);
  const forged=structuredClone(frozen);for(const offer of forged.offers){offer.baseAttack=999;offer.baseHealth=999;offer.rulesVersion='2.0.0';}
  const current=currentLoadout(forged);assert.deepEqual(current,profile.loadout);
  assert.deepEqual(golden.loadouts![0].offers[0].baseAttack,7,'old record has not been mutated');
});

test('historical loadouts reject unknown versions and reserved IDs and recompile forged stats',()=>{
  for(const mutate of [
    (loadout:Loadout)=>{loadout.offers[0].rulesVersion='999.0.0';},
    (loadout:Loadout)=>{loadout.offers[0].id='E999';},
    (loadout:Loadout)=>{loadout.offers[0].id='invalid/id';},
    (loadout:Loadout)=>{loadout.offers[0].profile!.guaranteed_months=100;},
  ]){const value=structuredClone(golden.loadouts[0]);mutate(value);assert.throws(()=>historicalLoadout(value));}
  const forged=structuredClone(golden.loadouts[0]);forged.offers[0].baseAttack=999;
  assert.deepEqual(historicalLoadout(forged),golden.loadouts[0]);
  const noVersion=structuredClone(golden.loadouts![0]);delete (noVersion.offers[0] as any).rulesVersion;
  assert.deepEqual(historicalLoadout(noVersion),golden.loadouts![0]);
});

test('incomplete legacy collections are retained but cannot supply unverified numbers to a new match',()=>{
  const old=structuredClone(golden.loadouts![0]);delete old.offers[0].profile;
  const profile={offers:[structuredClone(old.offers[0])],loadout:old};upgradeOfferCollection(profile);
  assert.equal(profile.offers.length,1);assert.equal(profile.offers[0].rulesVersion,'2.0.0');
  assert.throws(()=>currentLoadout(profile.loadout),/缺少原始资料/);
});

test('public tuning exposes fixed categories while hiding precise cities, raw profiles and signing bonuses',()=>{
  const loadout=currentLoadout(golden.loadouts![0]),source={...loadout.offers[0].profile!,city:'私密城市测试',city_cost_level:'low' as const,one_time_signing_cny:987654};
  loadout.offers[0]=compileOffer(source,null,'private_city');
  const view=getView(createMatch([loadout,currentLoadout(golden.loadouts![1])],15,{skipSetup:true}),'p1');
  const definition=view.players[0].offerZone[0].definition,raw=JSON.stringify(definition);
  assert.equal(definition.tuning?.cityLevel,'low');assert.equal(definition.profile,undefined);assert.equal(definition.definitionHash,undefined);
  assert.equal(raw.includes('私密城市测试'),false);assert.equal(raw.includes('987654'),false);
});
