import {chromium,webkit,type Browser,type BrowserContext,type Page} from '@playwright/test';
import net from 'node:net';
import {appendFile,chmod,mkdir,readFile,realpath,writeFile} from 'node:fs/promises';
import {join,resolve,relative,sep} from 'node:path';
import {randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {allowedTools,assertTool,navigationAllowed,publicInvite,redact,type RoleId} from './policy';
const exec=promisify(execFile);
type Json=Record<string,any>;
export interface GatewayConfig {role:RoleId;target:string;root:string;privateDir:string;socketPath:string;browser:'chromium'|'webkit';viewport:{width:number;height:number};touch:boolean;origins:string[];headless?:boolean;pairPath?:string;account?:{username:string;password:string;registered?:boolean};seededStorage?:Record<string,string>;seededSessionStorage?:Record<string,string>;references?:{id:string;path:string;kind:'reference'|'capture';label?:string;scene?:string}[]}
const json=(value:any)=>({type:'text',text:JSON.stringify(value)});
const object=(properties:Json={},required:string[]=[])=>({type:'object',additionalProperties:false,properties,required});
const schemas:Record<string,any>={screenshot:object(),currentUrl:object(),click:object({x:{type:'number'},y:{type:'number'}},['x','y']),tap:object({x:{type:'number'},y:{type:'number'}},['x','y']),scroll:object({deltaX:{type:'number'},deltaY:{type:'number'}},['deltaY']),touchScroll:object({deltaX:{type:'number'},deltaY:{type:'number'}},['deltaY']),keyboard:object({text:{type:'string'},key:{type:'string'}}),browser:object({action:{type:'string',enum:['screenshot','click','scroll','keyboard','reload','back','goto']},x:{type:'number'},y:{type:'number'},deltaY:{type:'number'},text:{type:'string'},key:{type:'string'},url:{type:'string'}},['action']),accessibilityTree:object(),ownAccount:object(),ownSeededStorage:object({action:{type:'string',enum:['restore','clear']}},['action']),syntheticFixture:object(),sandboxFaults:object({kind:{type:'string',enum:['offline','api-abort','api-delay','storage-quota']},enabled:{type:'boolean'},delayMs:{type:'integer',minimum:0,maximum:3000}},['kind','enabled']),publicInviteOutbox:object({invitation:{type:'string'}},['invitation']),publicInviteInbox:object(),repoRead:object({path:{type:'string'}},['path']),engineFixtures:object({id:{type:'string',enum:['CH01','CH02','CH03','CH04','CH05']}},['id']),testRunner:object({suite:{type:'string',enum:['rules','ai','privacy','backend','deployment']}},['suite']),approvedReferences:object({id:{type:'string'}}),blindedCaptures:object({label:{type:'string'}}),video:object({durationMs:{type:'integer',minimum:100,maximum:3000}}),timelineFrames:object({ids:{type:'array',items:{type:'string'},maxItems:12}}),eventTiming:object(),performanceTrace:object(),networkTrace:object(),touchEmulation:object({orientation:{type:'string',enum:['portrait','landscape']}},['orientation']),mediaEmulation:object({reducedMotion:{type:'boolean'},zoom:{type:'number',enum:[1,2]}})};
const descriptions:Record<string,string>={browser:'Operate only your tested page by visible coordinates or keyboard; no DOM selectors, JavaScript or developer APIs.',screenshot:'Observe the current viewport as an image. No DOM, source, or hidden state.',video:'Record a real normal-speed segment and return timestamped still frames. This tool cannot give the model native video perception; normal-speed review remains blocked.',timelineFrames:'Read only this run’s captured timestamped frames.',testRunner:'Execute one fixed read-only developer test suite; arbitrary commands and arguments are forbidden.',repoRead:'Read an allowlisted source file; cannot read secrets, run logs, other sessions or repository metadata.'};
export async function createGateway(config:GatewayConfig){
 await mkdir(config.privateDir,{recursive:true,mode:0o700});await mkdir(join(config.privateDir,'screenshots'),{recursive:true});await mkdir(join(config.privateDir,'video'),{recursive:true});
 const browser:Browser=await (config.browser==='webkit'?webkit:chromium).launch({headless:config.headless!==false});
 const context:BrowserContext=await browser.newContext({viewport:config.viewport,hasTouch:config.touch,isMobile:config.touch,acceptDownloads:false,recordVideo:{dir:join(config.privateDir,'video'),size:config.viewport}}),contextId=randomUUID();
 const started=performance.now(),network:any[]=[],frames:{id:string;path:string;timeMs:number}[]=[],actions:any[]=[];let serial=Promise.resolve(),sequence=0,closed=false;const faults={apiAbort:false,apiDelay:0};
 await context.tracing.start({screenshots:true,snapshots:true,sources:false});
 const allowedOrigins=new Set([new URL(config.target).origin,...config.origins]);
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(!allowedOrigins.has(u.origin)){await route.abort();return;}if(u.pathname.startsWith('/api/')){if(faults.apiAbort){await route.abort();return;}if(faults.apiDelay)await new Promise(r=>setTimeout(r,faults.apiDelay));}await route.continue()});
 await context.routeWebSocket('**/*',ws=>{const u=new URL(ws.url());u.protocol=u.protocol==='wss:'?'https:':'http:';if(allowedOrigins.has(u.origin))ws.connectToServer();else ws.close()});
 await context.addInitScript(()=>{const qa={frames:[] as number[],longTasks:[] as number[],last:0};Object.defineProperty(window,'__qaPerformance',{value:qa});const step=(now:number)=>{if(qa.last)qa.frames.push(now-qa.last);qa.last=now;if(qa.frames.length>20000)qa.frames.shift();requestAnimationFrame(step)};requestAnimationFrame(step);try{new PerformanceObserver(list=>{for(const e of list.getEntries())qa.longTasks.push(e.duration)}).observe({type:'longtask',buffered:true})}catch{}});
 if(config.seededStorage)await context.addInitScript(({storage,session})=>{if(!sessionStorage.getItem('__qaSeedApplied')){for(const [k,v] of Object.entries(storage))localStorage.setItem(k,v);for(const [k,v] of Object.entries(session))sessionStorage.setItem(k,v);sessionStorage.setItem('__qaSeedApplied','1');}},{storage:config.seededStorage,session:config.seededSessionStorage??{}});
 const page:Page=await context.newPage();page.setDefaultTimeout(8000);context.on('page',p=>{if(p!==page)void p.close()});
 page.on('requestfailed',r=>network.push({atMs:performance.now()-started,type:'failure',method:r.method(),url:r.url(),error:r.failure()?.errorText}));page.on('response',r=>network.push({atMs:performance.now()-started,type:'response',status:r.status(),url:r.url()}));
 if(config.role==='A08')await page.setContent('<html><body style="background:#efebe4;font-family:sans-serif;padding:40px"><h1>Anonymous visual review</h1><p>Use approvedReferences and blindedCaptures to inspect the supplied real browser images. The live candidate is hidden to preserve blinding.</p></body></html>');
 else await page.goto(config.target,{waitUntil:'domcontentloaded',timeout:20000});
 const shot=async()=>{const id=`frame-${String(++sequence).padStart(5,'0')}`,path=join(config.privateDir,'screenshots',id+'.jpg'),data=await page.screenshot({type:'jpeg',quality:82});await writeFile(path,data);const frame={id,path:relative(config.privateDir,path),timeMs:performance.now()-started};frames.push(frame);return {frame,image:{type:'image',mimeType:'image/jpeg',data:data.toString('base64')}}};
 const imageFile=async(path:string)=>({type:'image',mimeType:path.endsWith('.webp')?'image/webp':path.endsWith('.jpg')||path.endsWith('.jpeg')?'image/jpeg':'image/png',data:(await readFile(path)).toString('base64')});
 const pointer=async(a:Json,touch=false)=>{if(!Number.isFinite(a.x)||!Number.isFinite(a.y)||a.x<0||a.y<0||a.x>page.viewportSize()!.width||a.y>page.viewportSize()!.height)throw Error('Coordinates must lie in this viewport');if(touch)await page.touchscreen.tap(a.x,a.y);else await page.mouse.click(a.x,a.y)};
 const keyboard=async(a:Json)=>{if(a.text!==undefined){if(typeof a.text!=='string'||a.text.length>4000)throw Error('Text too long');await page.keyboard.insertText(a.text)}else if(typeof a.key==='string'&&a.key.length<60)await page.keyboard.press(a.key);else throw Error('Provide text or a key')};
 const metrics=()=>page.evaluate(()=>{const qa=(window as any).__qaPerformance;return {frameIntervals:qa?.frames??[],longTasks:qa?.longTasks??[],timeOrigin:performance.timeOrigin,userAgent:navigator.userAgent,devicePixelRatio:devicePixelRatio,visibility:document.visibilityState}});
 async function operate(name:string,a:Json):Promise<any[]>{
  assertTool(config.role,name);
  if(name==='screenshot')return [];
  if(name==='currentUrl')return [json({url:page.url()})];
  if(name==='click'||name==='tap'){await pointer(a,name==='tap');return []}
  if(name==='scroll'||name==='touchScroll'){if(!Number.isFinite(a.deltaY)||Math.abs(a.deltaY)>3000||a.deltaX!==undefined&&!Number.isFinite(a.deltaX))throw Error('Invalid scroll');await page.mouse.wheel(a.deltaX??0,a.deltaY);return []}
  if(name==='keyboard'){await keyboard(a);return []}
  if(name==='browser'){
   if(a.action==='click')await pointer(a,config.touch);else if(a.action==='scroll')await page.mouse.wheel(0,Math.max(-3000,Math.min(3000,Number(a.deltaY)||0)));else if(a.action==='keyboard')await keyboard(a);else if(a.action==='reload')await page.reload({waitUntil:'domcontentloaded'});else if(a.action==='back')await page.goBack({waitUntil:'domcontentloaded'});else if(a.action==='goto')await page.goto(navigationAllowed(a.url,config.target),{waitUntil:'domcontentloaded'});else if(a.action!=='screenshot')throw Error('Unknown browser action');return [];
  }
  if(name==='accessibilityTree')return [json({tree:await page.locator('body').ariaSnapshot()})];
  if(name==='ownAccount'){if(!config.account)throw Error('No isolated sandbox account configured for this run');return [json(config.account)]}
  if(name==='publicInviteOutbox'){if(!config.pairPath)throw Error('No paired recipient');const value=publicInvite(a.invitation,config.target);await mkdir(resolve(config.pairPath,'..'),{recursive:true});await writeFile(config.pairPath,JSON.stringify(value),{mode:0o600});return [json({delivered:true})]}
  if(name==='publicInviteInbox'){if(!config.pairPath)throw Error('No paired sender');const deadline=performance.now()+25000;do{try{return [json(JSON.parse(await readFile(config.pairPath,'utf8')))]}catch{}await new Promise(r=>setTimeout(r,500))}while(performance.now()<deadline);return [json({status:'waiting',message:'No public invitation has arrived yet; checked for 25 seconds.'})]}
  if(name==='syntheticFixture')return [json({company:'纸桥研发',role:'硬件研发',monthlyFixed:10000,salaryMonths:12,otherIncome:'explicitly zero',benefit:'双休',alternateRole:'销售',annualOnlyText:'年包 30 万，未提供月薪与薪数。'})];
  if(name==='ownSeededStorage'){await page.evaluate(({action,storage,session})=>{localStorage.clear();sessionStorage.clear();if(action==='restore'){for(const [k,v]of Object.entries(storage))localStorage.setItem(k,v);for(const [k,v]of Object.entries(session))sessionStorage.setItem(k,v);}sessionStorage.setItem('__qaSeedApplied','1')},{action:a.action,storage:config.seededStorage??{},session:config.seededSessionStorage??{}});await page.reload({waitUntil:'domcontentloaded'});return [json({seeded:!!config.seededStorage,scope:'only this browser context'})]}
  if(name==='sandboxFaults'){
   if(a.kind==='offline')await context.setOffline(a.enabled===true);else if(a.kind==='api-abort')faults.apiAbort=a.enabled===true;else if(a.kind==='api-delay')faults.apiDelay=a.enabled?Math.max(0,Math.min(3000,a.delayMs??1000)):0;else if(a.kind==='storage-quota')await page.evaluate(enabled=>{const w=window as any;if(!w.__qaStorageSet)w.__qaStorageSet=Storage.prototype.setItem;Storage.prototype.setItem=enabled?function(){throw new DOMException('Synthetic quota failure','QuotaExceededError')}:w.__qaStorageSet},a.enabled===true);else throw Error('Unknown fault');return [json({fault:a.kind,enabled:a.enabled})];
  }
  if(name==='repoRead'){
   if(typeof a.path!=='string'||! /^(src|server|cloudflare|tests)\/[A-Za-z0-9_./-]+\.(ts|tsx|json|css)$/.test(a.path))throw Error('Source path not allowlisted');const file=await realpath(resolve(config.root,a.path));if(!file.startsWith(config.root+sep))throw Error('Path escapes source root');const content=await readFile(file,'utf8');if(content.length>160000)throw Error('Source file too large');return [json({path:a.path,content})];
  }
  if(name==='engineFixtures'){const {createChallenge,validateChallengeSolution,experimentFlags}=await import('../../src/game/experiments');const fixture=createChallenge(a.id,experimentFlags({challenges:true})),result=validateChallengeSolution(fixture);return [json({fixture:fixture.descriptor,initialState:fixture.state,solution:fixture.solution,verified:result.solved})]}
  if(name==='testRunner'){
   const suites:Record<string,string[]>={rules:['tests/rules.test.ts','tests/tutorial.test.ts'],ai:['tests/bot-regressions.test.ts','tests/bot-search.test.ts'],privacy:['tests/share-privacy.test.ts','tests/profile-data.test.ts'],backend:['tests/server-draft.test.ts','tests/server-storage.test.ts'],deployment:['tests/deployment.test.ts']};if(!suites[a.suite])throw Error('Unknown suite');if(config.role==='A10'&&!['deployment'].includes(a.suite))throw Error('Performance role cannot read white-box tactical answers');const output=await exec(process.execPath,['--import','tsx','--test',...suites[a.suite]],{cwd:config.root,timeout:90000,maxBuffer:2_000_000}).then(r=>({exitCode:0,stdout:r.stdout,stderr:r.stderr}),e=>({exitCode:e.code??1,stdout:e.stdout??'',stderr:e.stderr??''}));await writeFile(join(config.privateDir,`suite-${a.suite}-${Date.now()}.txt`),output.stdout+'\n'+output.stderr);return [json(redact(output))];
  }
  if(name==='approvedReferences'||name==='blindedCaptures'){
   const refs=(config.references??[]).filter(r=>r.kind===(name==='approvedReferences'?'reference':'capture')),key=name==='approvedReferences'?a.id:a.label;if(!key)return [json({available:refs.map(r=>({id:r.id,...(r.label?{label:r.label}:{}),...(r.scene?{scene:r.scene}:{})})),missing:refs.length===0})];const ref=refs.find(r=>r.id===key||r.label===key);if(!ref)throw Error('No approved image with this ID');return [json({evidenceImage:ref.id,scene:ref.scene??null}),await imageFile(ref.path)];
  }
  if(name==='video'){const duration=Math.max(100,Math.min(3000,Number(a.durationMs)||1800)),until=performance.now()+duration,result:any[]=[json({nativeVideoObservation:false,scope:'timestamped still-frame review only; continuous video is separately recorded',normalSpeedReview:'blocked'})];while(performance.now()<until&&result.length<12){const captured=await shot();result.push(json(captured.frame),captured.image);await new Promise(r=>setTimeout(r,160))}return result}
  if(name==='timelineFrames'){if(!a.ids)return [json({frames})];return Promise.all((a.ids as string[]).map(async(id)=>{const frame=frames.find(f=>f.id===id);if(!frame)throw Error('Unknown frame');return imageFile(join(config.privateDir,frame.path))}))}
  if(name==='eventTiming')return [json({metrics:await metrics(),visibleTimeline:await page.locator('[data-motion-id],.battle-event-log,.battle-log').allTextContents()})];
  if(name==='performanceTrace')return [json({source:'actual browser instrumentation; trace saved privately',metrics:await metrics()})];
  if(name==='networkTrace')return [json(redact(network.slice(-250)))];
  if(name==='touchEmulation'){const {width,height}=config.viewport;await page.setViewportSize(a.orientation==='landscape'?{width:Math.max(width,height),height:Math.min(width,height)}:{width:Math.min(width,height),height:Math.max(width,height)});return [json({deviceMode:config.touch?'emulated-touch':'desktop',viewport:page.viewportSize()})]}
  if(name==='mediaEmulation'){if(a.reducedMotion!==undefined)await page.emulateMedia({reducedMotion:a.reducedMotion?'reduce':'no-preference'});if(a.zoom!==undefined){if(![1,2].includes(a.zoom))throw Error('Only 100% or 200%');await page.evaluate(zoom=>{document.documentElement.style.zoom=String(zoom)},a.zoom)}return []}
  throw Error('Unsupported tool');
 }
 async function call(name:string,args:Json){try{assertTool(config.role,name)}catch(error){await appendFile(join(config.privateDir,'security-denials.jsonl'),JSON.stringify({tool:String(name).slice(0,100),atMs:performance.now()-started,reason:'ROLE_TOOL_DENIED'})+'\n');throw error;}const start=performance.now(),id=`action-${actions.length+1}`,before=frames.at(-1)?.id??null;let content:any[],error:string|undefined;try{content=await operate(name,args)}catch(e){error=String((e as Error).message);content=[json({error:redact(error),scope:'tool failed; do not claim task completion'})]};const actionMs=performance.now()-start;const after=await shot();content.push(json({evidenceId:id,frame:after.frame,url:page.url()}),after.image);const row={id,tool:name,args,startedMs:start-started,actionDurationMs:actionMs,elapsedMs:performance.now()-started,beforeFrame:before,afterFrame:after.frame.id,ok:!error,error};actions.push(row);await appendFile(join(config.privateDir,'actions.jsonl'),JSON.stringify(row)+'\n');return {content,isError:!!error}}
 await shot();
 const server=net.createServer(socket=>{socket.setEncoding('utf8');let buffer='';socket.on('data',data=>{buffer+=data;if(buffer.length>100000){socket.destroy();return;}for(let newline;(newline=buffer.indexOf('\n'))>=0;){const line=buffer.slice(0,newline);buffer=buffer.slice(newline+1);if(line.length>100000){socket.destroy();return}let request:any;try{request=JSON.parse(line)}catch{continue}if(request.id===undefined)continue;serial=serial.then(async()=>{let result:any,error:any;try{if(request.method==='initialize')result={protocolVersion:request.params?.protocolVersion??'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'role-browser-gateway',version:'2.2.0'}};else if(request.method==='tools/list')result={tools:allowedTools(config.role).map(name=>({name,description:descriptions[name]??`Role-authorized ${name}; limited to this isolated test run.`,inputSchema:schemas[name]}))};else if(request.method==='tools/call')result=await call(request.params.name,request.params.arguments??{});else if(['resources/list','resources/templates/list','prompts/list'].includes(request.method))result=request.method==='prompts/list'?{prompts:[]}:request.method==='resources/list'?{resources:[]}:{resourceTemplates:[]};else if(request.method==='ping')result={};else throw Error('METHOD_DENIED')}catch(e){error={code:-32601,message:String((e as Error).message)}}socket.write(JSON.stringify({jsonrpc:'2.0',id:request.id,...(error?{error}:{result})})+'\n')}).catch(()=>{});}})});
 await new Promise<void>((done,reject)=>{server.once('error',reject);server.listen(config.socketPath,done)});await chmod(config.socketPath,0o600);
 return {contextId,browserVersion:browser.version(),tools:allowedTools(config.role),async close(){if(closed)return;closed=true;await serial;const measurement=await metrics().catch(()=>null);await writeFile(join(config.privateDir,'browser-metrics.json'),JSON.stringify({measurement,network,frames,actions:actions.length},null,2));await context.tracing.stop({path:join(config.privateDir,'trace.zip')});await context.close();await browser.close();server.close();await writeFile(join(config.privateDir,'gateway-session.json'),JSON.stringify({contextId,browser:config.browser,browserVersion:browser.version(),viewport:config.viewport,deviceMode:config.touch?'emulated-touch':'desktop',role:config.role,tools:allowedTools(config.role),actions:actions.length,frames:frames.length,nativeVideoObservation:false,durationMs:performance.now()-started},null,2));}};
}
