import {readFile,mkdir,writeFile,readdir,stat,access,chmod,copyFile} from 'node:fs/promises';
import {existsSync,createWriteStream} from 'node:fs';
import {resolve,join,relative,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,randomBytes} from 'node:crypto';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {createGateway,type GatewayConfig} from './gateway';
import {rolePreflight} from './preflight';
import {ROLES,allowedTools,codexArgs,hashFile,RESULT_SCHEMA,redact,safeTarget,type RoleId,type AgentResult} from './policy';
const exec=promisify(execFile),root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),publicRoot=join(root,'reports/agent-runs'),privateRoot=join(root,'work/agent-runs');
const get=(name:string,fallback?:string)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1]};
const flag=(name:string)=>process.argv.includes(name),json=async(path:string)=>JSON.parse(await readFile(path,'utf8')),save=async(path:string,value:any)=>{await mkdir(dirname(path),{recursive:true});await writeFile(path,JSON.stringify(value,null,2)+'\n',{mode:0o600})};
const cli=get('--cli',process.env.CODEX_QA_CLI??'/Applications/ChatGPT.app/Contents/Resources/codex-cli/CodexCLI.app/Contents/MacOS/codex')!,model=get('--model',process.env.QA_MODEL);
const originArgs=process.argv.flatMap((arg,i)=>arg==='--allow-origin'?[process.argv[i+1]]:[]);
const loadPlan=()=>json(join(root,'agents/run-plan.json'));
const getCommit=async()=>(await exec('git',['rev-parse','HEAD'],{cwd:root})).stdout.trim();
async function walk(folder:string):Promise<string[]>{if(!existsSync(folder))return [];const entries=await readdir(folder,{withFileTypes:true});return (await Promise.all(entries.map(e=>e.isDirectory()?walk(join(folder,e.name)):[join(folder,e.name)]))).flat()}
function publicSession(session:any){return {runId:session.runId,agentRole:session.agentRole,agentSessionId:session.agentSessionId,browserContextId:session.browserContextId,commit:session.commit,model:session.model,requestedModel:session.requestedModel,actualModel:session.actualModel,modelProvenance:session.modelProvenance,preflight:session.preflight,browser:session.browser,viewport:session.viewport,deviceMode:session.deviceMode,status:session.status,attempt:session.attempt,scope:session.scope,toolPolicy:session.toolPolicy,observedMcpTools:session.observedMcpTools,startedAt:session.startedAt,finishedAt:session.finishedAt,agentTaskCompletion:session.status==='passed'?1:null,normalSpeedMotionReview:session.agentRole==='A09'?'blocked-native-video-observation-unavailable':null,findings:session.result?.findings?.map((f:any)=>({id:f.id,severity:f.severity,evidenceIds:f.evidenceIds}))??[],completedTaskCount:session.result?.completedTasks?.length??0,artifacts:session.artifacts,limitations:session.limitations,realUserRetention:null,sharingRate:null,rawEvidenceVisibility:'restricted-local-work-directory',credentialsPublished:false};}
const policyPath=join(root,'scripts/agent-testing/policy.ts');
async function readiness(entry:any,inputs:{references?:any[];accounts?:any[];smoke?:boolean}={}){
 const {chromium,webkit}=await import('@playwright/test');let proof:any;
 try{proof=await json(join(publicRoot,'toolchain.json'))}catch{}
 const version=existsSync(cli)?(await exec(cli,['--version'])).stdout.trim():null;
 const isolationVerified=proof?.status==='passed'&&proof.policyHash===hashFile(policyPath)&&proof.cliVersion===version;
 return rolePreflight({role:entry.roleId,browser:entry.browserProject,cliAvailable:existsSync(cli),browserAvailable:existsSync((entry.browserProject==='webkit'?webkit:chromium).executablePath()),isolationVerified:!!inputs.smoke||isolationVerified,hasStorageFixture:!!get('--storage-fixture'),hasAccount:!!inputs.accounts?.find((a:any)=>a.runId===entry.runId),hasReferences:!!inputs.references?.some(r=>r.kind==='reference'),captureCount:inputs.references?.filter(r=>r.kind==='capture').length??0});
}
async function fixtures(){
 const references=get('--references')?await json(resolve(get('--references')!)):undefined;
 if(references&&(!Array.isArray(references)||references.some((r:any)=>!['reference','capture'].includes(r.kind)||typeof r.path!=='string'||!existsSync(resolve(root,r.path)))))throw Error('Reference manifest must contain existing approved reference/capture images.');
 const accountInput=get('--accounts')?await json(resolve(get('--accounts')!)):undefined;
 if(accountInput&&(accountInput.synthetic!==true||!Array.isArray(accountInput.accounts)))throw Error('Account fixture requires synthetic:true and an accounts array.');
 const accounts=accountInput?.accounts;
 if(accounts){const names=new Set(),runs=new Set();for(const a of accounts){if(!/^A0[56]-R0[1-4]$/.test(a.runId)||typeof a.username!=='string'||typeof a.password!=='string'||a.password.length<8||names.has(a.username)||runs.has(a.runId))throw Error('Each friend run needs a distinct valid synthetic account.');names.add(a.username);runs.add(a.runId);}}
 if(get('--storage-fixture')){const fixture=await json(resolve(get('--storage-fixture')!));if(fixture.synthetic!==true||!fixture.storage||[...Object.entries(fixture.storage),...Object.entries(fixture.sessionStorage??{})].some(([key,value])=>typeof value!=='string'||/account|auth|token|password|cookie/i.test(key)))throw Error('Return-visit fixture must contain synthetic local storage only, without account credentials.');}
 return {references,accounts};
}
async function plan(){const manifest=await loadPlan();if(manifest.runs.length!==48)throw Error('Plan must contain 48 runs');for(const role of ROLES){const rows=manifest.runs.filter((r:any)=>r.roleId===role);if(rows.length!==4)throw Error('Each role needs four runs');for(const row of rows){allowedTools(row.roleId);if(!['chromium','webkit'].includes(row.browserProject))throw Error('Unsupported browser');if(row.agentSessionId||row.browserContextId)throw Error('Template plan must not fabricate executed identities');}}
 const inputs=await fixtures(),preflight=await Promise.all(manifest.runs.map(async(entry:any)=>({runId:entry.runId,...await readiness(entry,inputs)})));const target=get('--url');if(target)safeTarget(target,originArgs);const {chromium,webkit}=await import('@playwright/test');const result={...manifest,status:'not-run',createdAt:new Date().toISOString(),scope:'execution plan only; no agent sessions launched',target:target??null,configuredModel:model??null,cliAvailable:existsSync(cli),browsers:{chromium:existsSync(chromium.executablePath()),webkit:existsSync(webkit.executablePath())},tools:Object.fromEntries(ROLES.map(role=>[role,allowedTools(role)])),preflight,requirements:['Run only after the initial source commit has been pushed; --published-commit is mandatory.','Each formal run requires --model or QA_MODEL so its actual requested model is recorded.','A05/A06 launch together; only their public invitation is shared.','A08 needs --references manifest with approved reference and blinded image inputs.','A09 can review timed frames, but native normal-speed model video observation is unavailable and must stay blocked.'],sourcePlanHash:hashFile(join(root,'agents/run-plan.json'))};await save(join(publicRoot,'plan.json'),result);console.log(JSON.stringify({plan:'reports/agent-runs/plan.json',runs:48,status:'not-run',cliAvailable:result.cliAvailable,browsers:result.browsers},null,2));}
async function published(commit:string){if(!/^[a-f0-9]{40}$/.test(commit)||await getCommit()!==commit)throw Error('--published-commit must equal the checked-out HEAD');const branch=(await exec('git',['branch','--show-current'],{cwd:root})).stdout.trim();const remote=(await exec('git',['ls-remote','--heads','origin',branch],{cwd:root,timeout:20000})).stdout.trim().split(/\s/)[0];if(remote!==commit)throw Error('Current source commit has not been verified at origin; formal agent runs are blocked');const changed=(await exec('git',['diff','HEAD','--name-only'],{cwd:root})).stdout.trim().split('\n').filter(Boolean).filter(p=>!p.startsWith('reports/'));const untracked=(await exec('git',['ls-files','--others','--exclude-standard'],{cwd:root})).stdout.trim().split('\n').filter(Boolean).filter(p=>!p.startsWith('reports/')&&!p.startsWith('work/'));if(changed.length||untracked.length)throw Error('Tested source differs from the published commit');}
async function runOne(entry:any,target:string,options:{smoke:boolean;commit:string;references?:any[];accounts?:any[];pairPath?:string}){
 const runId=options.smoke?'SMOKE-'+randomUUID():entry.runId,role=entry.roleId as RoleId,runDir=join(privateRoot,runId);await mkdir(runDir,{recursive:true,mode:0o700});await chmod(runDir,0o700);const attempt=(await readdir(runDir)).filter(x=>/^attempt-\d+$/.test(x)).length+1;
 if(attempt>1&&!flag('--retry')&&!options.smoke)throw Error(`${runId} already has an attempt; use --retry to retain its original sample ID`);
 const privateDir=join(runDir,'attempt-'+attempt),sandbox=join(privateDir,'isolated-cwd');await mkdir(sandbox,{recursive:true,mode:0o700});const socketPath=join(tmpdir(),'obqa-'+randomBytes(10).toString('hex')+'.sock');
 const fixtureAccount=options.accounts?.find(a=>a.runId===entry.runId),account=fixtureAccount?{username:fixtureAccount.username,password:fixtureAccount.password,registered:fixtureAccount.registered===true}:undefined;
 const references=(options.references??[]).map((ref:any)=>({...ref,path:resolve(root,ref.path)}));const captures=references.filter(r=>r.kind==='capture'),flip=randomBytes(1)[0]%2===0;const versions=[...new Set(captures.map(r=>r.version))];captures.forEach((ref,index)=>{const versionIndex=versions.indexOf(ref.version),version=versionIndex<2?(flip?['X','Y']:['Y','X'])[versionIndex]:'?';ref.id=ref.label=version+'-'+(ref.scene??String(index+1));});

 for(let i=0;i<references.length;i++){const ref=references[i],extension=/\.(png|jpe?g|webp)$/i.exec(ref.path)?.[1];if(!extension)throw Error('Reference inputs must be PNG, JPEG or WebP images');const destination=join(privateDir,'review-inputs',String(i)+'.'+extension);await mkdir(dirname(destination),{recursive:true});await copyFile(ref.path,destination);ref.originalPath=ref.path;ref.path=destination;}
 const config:GatewayConfig={role,target,root,privateDir,socketPath,browser:entry.browserProject,viewport:entry.viewport,touch:entry.deviceMode==='emulated-touch',origins:originArgs,headless:!flag('--headed'),pairPath:options.pairPath,account,references};
 if(role==='A03'&&get('--storage-fixture')){const seed=await json(resolve(get('--storage-fixture')!));config.seededStorage=seed.storage;config.seededSessionStorage=seed.sessionStorage;}
 const session:any={runId,agentRole:role,agentSessionId:null,browserContextId:null,commit:options.commit,model:model??null,requestedModel:model??null,actualModel:null,modelProvenance:'explicit-cli-argument; ephemeral JSON events do not expose a resolved model unless supplied by the CLI',preflight:await readiness(entry,{...options}),browser:{name:entry.browserProject,version:null},viewport:entry.viewport,deviceMode:entry.deviceMode,status:'running',attempt,scope:options.smoke?'toolchain-smoke-excluded-from-acceptance':'independent-agent-acceptance',toolPolicy:allowedTools(role),observedMcpTools:[],startedAt:new Date().toISOString(),limitations:[]};await save(join(privateDir,'session.json'),session);
 const prompt=options.smoke?'This is a read-only toolchain smoke test, not a game acceptance sample. If tools are wrapped in code mode, first inspect ALL_TOOLS metadata (names only) and include all available underlying tool names in visibleTools. Do not include the orchestration wrappers in visibleTools when they merely call those underlying tools. Never call any underlying tool outside the role gateway. Use currentUrl and screenshot exactly once each. Do not click or type. Report which external tools are available and return blocked as the task status, with a limitation saying this is only a smoke test.':await readFile(join(root,'agents/prompts',role+'.md'),'utf8');
 const instructions='You are an independent browser test agent. You must not modify code or use tools outside your assigned gateway. Never inspect other sessions or seek credentials beyond your own sandbox account. Tool failures are evidence, not permission to bypass restrictions. Use screenshots and recorded evidence IDs for findings. Return the required JSON schema. Your visibleTools field must list every external tool you were offered, including any unexpected tools. If a needed capability is unavailable, report blocked. Do not state that static frames prove normal-speed video quality.';
 const extra=role==='A09'?'\nNative model video observation is unavailable. Actually review the supported timestamped frames and record useful partial findings, but normal-speed video review is blocked and the overall status cannot be passed.':role==='A05'||role==='A06'?'\nUse only the supplied synthetic account in ownAccount and the visible registration/login UI. If registered is true, log in instead of registering another account. Do not reuse or request another player’s credentials. You may share only the public invitation through your designated inbox/outbox.':role==='A08'?'\nAsk the approvedReferences and blindedCaptures tools for their manifests first. Missing approved or blinded inputs are blocked; do not invent a comparison.':'';
 await writeFile(join(privateDir,'task.md'),prompt+extra);await writeFile(join(sandbox,'instructions.md'),instructions);await save(join(sandbox,'result-schema.json'),RESULT_SCHEMA);await save(join(privateDir,'private-input.json'),{account,references,target});
 let gateway:Awaited<ReturnType<typeof createGateway>>|undefined;
 try{
  if(!session.preflight.canLaunch&&!options.smoke)throw Error(session.preflight.blockedReasons.join(' '));
  gateway=await createGateway(config);session.browserContextId=gateway.contextId;session.browser.version=gateway.browserVersion;await save(join(privateDir,'gateway-policy.json'),{role,exposedTools:gateway.tools,arbitraryShell:false,arbitraryJavaScript:false,sourceAccess:role==='A07'||role==='A12'});
  const args=codexArgs({cwd:sandbox,schema:join(sandbox,'result-schema.json'),instructions:join(sandbox,'instructions.md'),socket:socketPath,proxy:join(root,'scripts/agent-testing/gateway-stdio.mjs'),role,model});
  await save(join(privateDir,'cli-policy.json'),{args:args.map(a=>redact(a)),cliVersion:(await exec(cli,['--version'])).stdout.trim(),documentation:'https://learn.chatgpt.com/docs/config-file/config-reference'});
  const child=spawn(cli,args,{cwd:sandbox,env:process.env,stdio:['pipe','pipe','pipe']}),rawOut=createWriteStream(join(privateDir,'agent-events.jsonl'),{mode:0o600}),rawErr=createWriteStream(join(privateDir,'agent-stderr.txt'),{mode:0o600});let pendingLine='',timedOut=false,outputLimit=false,bytes=0;const messages:string[]=[],observed=new Set<string>();
  const terminate=()=>{child.kill('SIGTERM');setTimeout(()=>child.kill('SIGKILL'),3000).unref()};
  const parseEvent=(line:string)=>{let event:any;try{event=JSON.parse(line)}catch{return}session.agentSessionId??=event.thread_id??event.threadId??event.session_id??null;if(typeof event.model==='string'){session.actualModel=event.model;session.model=event.model;session.modelProvenance='raw-cli-event';}const item=event.item;if(item?.type==='agent_message'&&typeof item.text==='string')messages.push(item.text);if(item?.type==='mcp_tool_call'&&event.type==='item.completed'&&!observed.has(item.id)){observed.add(item.id);const name=item.tool??item.name;session.observedMcpTools.push({id:item.id,server:item.server,tool:name,status:item.status});if(item.server!=='qa'||!allowedTools(role).includes(name))session.limitations.push('Unexpected MCP tool observed; isolation is unverified.');}};
  const timeout=setTimeout(()=>{timedOut=true;terminate()},Number(get('--timeout-sec',options.smoke?'120':'1800'))*1000);
  child.stdout.pipe(rawOut);child.stderr.pipe(rawErr);
  child.stdout.on('data',d=>{bytes+=d.length;pendingLine+=String(d);if(bytes>250_000_000||pendingLine.length>15_000_000){outputLimit=true;terminate();pendingLine='';return;}let nl;while((nl=pendingLine.indexOf('\n'))>=0){parseEvent(pendingLine.slice(0,nl));pendingLine=pendingLine.slice(nl+1);}});
  child.stdin.end(prompt+extra+'\nBefore taking any action, inspect ALL_TOOLS metadata (names only) and list every underlying tool in visibleTools. Do not include code-mode orchestration wrappers. If any underlying tool is outside your role gateway, stop and return blocked without inspecting the game.\nUse only the current page. Actual target: '+target+'\nReturn structured JSON; no markdown fences.');
  let exitCode:number|null=null;
  try{exitCode=await new Promise<number|null>((done,reject)=>{child.once('error',reject);child.once('close',done)});}finally{clearTimeout(timeout);await Promise.all([new Promise<void>(r=>rawOut.closed?r():rawOut.once('close',()=>r())),new Promise<void>(r=>rawErr.closed?r():rawErr.once('close',()=>r()))]);}
  if(pendingLine)parseEvent(pendingLine);if(outputLimit)session.limitations.push('CLI output limit exceeded; run stopped with evidence retained.');
  let result:AgentResult|undefined;for(const text of messages.reverse()){try{const candidate=JSON.parse(text);if(['passed','failed','blocked'].includes(candidate.status)&&Array.isArray(candidate.completedTasks)&&Array.isArray(candidate.findings)&&Array.isArray(candidate.limitations)&&Array.isArray(candidate.visibleTools)&&candidate.visibleTools.every((x:any)=>typeof x==='string')){result=candidate;break}}catch{}}
  if(result)session.result=result;session.exitCode=exitCode;session.status=timedOut||outputLimit?'blocked':exitCode===0&&result?result.status:'blocked';if(timedOut)session.limitations.push('Agent execution timed out; evidence retained.');if(!session.agentSessionId)session.limitations.push('CLI did not return an actual agent session ID.');if(!result)session.limitations.push('No schema-valid final result was observed.');
  const visible=result?.visibleTools??[];const unexpected=visible.filter(name=>!allowedTools(role).some(tool=>name===tool||name===`mcp__qa__${tool}`||name===`mcp__qa.${tool}`));if(new Set(visible.map((name:string)=>name.replace(/^mcp__qa(?:__|\.)/,''))).size!==allowedTools(role).length){session.status='blocked';session.limitations.push('The full role tool inventory was not reported; isolation is unverified.');}if(unexpected.length){session.status='blocked';session.limitations.push('Agent reported tools outside the role allowlist: '+unexpected.join(', '));}
  if(role==='A09'){session.status=session.status==='failed'?'failed':'blocked';session.limitations.push('Timestamped frame review is partial coverage; native normal-speed video observation unavailable.');}
  if(role==='A08'&&(!references.some(r=>r.kind==='reference')||captures.length<2)){session.status='blocked';session.limitations.push('Approved reference and anonymous before/after captures were not both provided.');}
  if(result?.findings?.some(f=>f.severity==='P0'||f.severity==='P1')&&session.status==='passed')session.status='failed';
  if(session.limitations.some((s:string)=>s.includes('isolation is unverified')||s.includes('actual agent session')))session.status='blocked';
 }catch(error){session.status='blocked';session.limitations.push(redact(String((error as Error).message),account?[account.password,account.username]:[]));}
 finally{try{await gateway?.close()}catch(error){session.status='blocked';session.limitations.push('Browser evidence could not finalize: '+redact(String((error as Error).message)));}session.finishedAt=new Date().toISOString();}
 if(options.smoke&&session.agentSessionId&&session.result?.visibleTools?.length===allowedTools(role).length&&session.limitations.length===0&&session.observedMcpTools.length===2&&session.observedMcpTools.every((call:any)=>call.server==='qa'&&call.status==='completed')&&existsSync(join(privateDir,'gateway-session.json'))){const g=await json(join(privateDir,'gateway-session.json'));if(g.actions===2)await save(join(publicRoot,'toolchain.json'),{status:'passed',scope:'non-sample CLI/MCP transport and tool isolation only',smokeRunId:runId,agentSessionId:session.agentSessionId,cliVersion:(await exec(cli,['--version'])).stdout.trim(),policyHash:hashFile(policyPath),visibleTools:session.result.visibleTools,observedActions:g.actions,actualModel:session.actualModel,requestedModel:session.requestedModel,formalAcceptance:'not-run',evidenceHash:hashFile(join(privateDir,'agent-events.jsonl')),verifiedAt:new Date().toISOString()});}
 const files=(await walk(privateDir)).filter(path=>!path.endsWith('/session.json'));session.artifacts=files.map(path=>({id:relative(privateDir,path),sha256:hashFile(path),visibility:'restricted-local'}));await save(join(privateDir,'session.json'),session);const projected=publicSession(session);await save(join(publicRoot,runId,'attempt-'+attempt+'.json'),projected);await save(join(publicRoot,runId,'session.json'),projected);console.log(JSON.stringify({runId,attempt,status:session.status,agentSessionId:session.agentSessionId,scope:session.scope}));return projected;
}
async function run(){const target=get('--url');if(!target)throw Error('--url is required');safeTarget(target,originArgs);await access(cli);const smoke=flag('--smoke'),commit=await getCommit();if(!smoke){if(!model)throw Error('Set --model or QA_MODEL for a traceable formal model context');const source=get('--published-commit');if(!source)throw Error('Formal runs are blocked until --published-commit has been verified');await published(source)}
 const manifest=await loadPlan(),requested=get('--run');if(!smoke&&!requested&&!flag('--all'))throw Error('Choose --run A01-R01 or --all');const {references,accounts}=await fixtures();let selected=smoke?[manifest.runs[0]]:flag('--all')?manifest.runs:manifest.runs.filter((entry:any)=>entry.runId===requested);if(!selected.length)throw Error('Unknown run ID');
 const concurrency=Math.max(2,Math.min(4,Number(get('--concurrency','3'))||3)),completed=new Set<string>(),jobs:{entries:any[];weight:number;pairPath?:string}[]=[];
 for(const entry of selected){if(completed.has(entry.runId))continue;const matched=/^A0[56]-R(\d\d)$/.exec(entry.runId);if(matched&&!smoke){const paired=manifest.runs.filter((r:any)=>r.runId===`A05-R${matched[1]}`||r.runId===`A06-R${matched[1]}`);jobs.push({entries:paired,weight:2,pairPath:join(privateRoot,'pairs','friend-R'+matched[1]+'-'+randomUUID()+'.json')});paired.forEach((r:any)=>completed.add(r.runId));}else{jobs.push({entries:[entry],weight:entry.roleId==='A10'?concurrency:1});completed.add(entry.runId)}}
 // A10 is exclusive so other agents and fixed test suites do not contaminate its measurements.
 const active=new Set<Promise<void>>();let weight=0;
 while(jobs.length||active.size){while(jobs.length&&weight+jobs[0].weight<=concurrency){const job=jobs.shift()!;weight+=job.weight;let running:Promise<void>;running=(async()=>{if(!smoke)await published(commit);await Promise.all(job.entries.map(entry=>runOne(entry,target,{smoke,commit,references,accounts,pairPath:job.pairPath})));})().finally(()=>{weight-=job.weight;active.delete(running)});active.add(running);}if(active.size)await Promise.race(active);}
}

async function verify(){const manifest=await loadPlan(),results:any[]=[],ids=new Set<string>(),contexts=new Set<string>();for(const entry of manifest.runs){const path=join(publicRoot,entry.runId,'session.json');if(!existsSync(path)){results.push({runId:entry.runId,status:'not-run',issues:['No executed session']});continue}const result=await json(path),issues:string[]=[];if(result.scope!=='independent-agent-acceptance')issues.push('Not an acceptance sample');if(!result.agentSessionId||ids.has(result.agentSessionId))issues.push('Missing or reused model session');if(!result.browserContextId||contexts.has(result.browserContextId))issues.push('Missing or reused browser context');if(result.agentSessionId)ids.add(result.agentSessionId);if(result.browserContextId)contexts.add(result.browserContextId);if(!result.model)issues.push('Unrecorded model');if(!result.commit)issues.push('Unrecorded commit');if(JSON.stringify(result.toolPolicy)!==JSON.stringify(allowedTools(entry.roleId)))issues.push('Tool policy mismatch');const raw=join(privateRoot,entry.runId,'attempt-'+result.attempt);for(const artifact of result.artifacts??[]){const path=join(raw,artifact.id);if(!existsSync(path)||hashFile(path)!==artifact.sha256)issues.push('Missing or changed evidence: '+artifact.id)}for(const essential of ['agent-events.jsonl','actions.jsonl','trace.zip','gateway-session.json'])if(!result.artifacts?.some((a:any)=>a.id===essential))issues.push('Missing '+essential);if(!result.artifacts?.some((a:any)=>a.id.startsWith('screenshots/')))issues.push('No screenshots');if(!result.artifacts?.some((a:any)=>a.id.startsWith('video/')&&a.id.endsWith('.webm')))issues.push('No actual video');if(entry.roleId==='A09')issues.push('Normal-speed model video review remains blocked');if(result.status!=='passed')issues.push('Run status is '+result.status);results.push({runId:entry.runId,status:issues.length?'blocked':'passed',actualStatus:result.status,attempt:result.attempt,issues})}
 const report={scope:'evidence-integrity-and-completion',generatedAt:new Date().toISOString(),plannedRuns:48,actualSessions:ids.size,passed:results.filter(r=>r.status==='passed').length,status:results.every(r=>r.status==='passed')?'passed':'blocked',countingRule:'Retries remain attempts of the original run ID; SMOKE IDs are excluded.',independentRunCompletion:results,realUserRetention:null,sharingRate:null};await save(join(publicRoot,'verification.json'),report);console.log(JSON.stringify({status:report.status,actualSessions:report.actualSessions,passed:report.passed,plannedRuns:48}));if(report.status!=='passed')process.exitCode=1;}
const command=process.argv[2];if(command==='plan')await plan();else if(command==='run')await run();else if(command==='verify')await verify();else throw Error('Use plan, run or verify');
