import {offerArt,supportArt,educationSeal} from '../assets';
import {useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';
import Replay from './Replay';
import {useBattleFullscreen} from '../fullscreen';
import '../styles/battle-viewport.css';
import BattleEffects from '../components/BattleEffects';
import {useCardDrag} from '../components/useCardDrag';
import {initialBoardPresentation,presentBoard,finishBoardDepartures} from '../components/board-presentation';
import TutorialGuide from '../components/TutorialGuide';
import OpponentSkills from '../components/OpponentSkills';
import {exportBattle} from '../share';
import type {MatchView,Command,UnitView,OfferDefinition,PlayerView} from '../game/types';
import {rules,education,cardById,templateById,benefitById} from '../game/catalog';
import {Icon,Art,heroPath,OfferCard,CommonCard,Modal,schoolName,Badge} from '../ui';
import type {Room} from '../api';
interface Props {accountRequired?:boolean;signedIn?:boolean;onSaveMatch?:()=>void;saveBusy?:boolean;savedMatch?:boolean;onSaveReport?:(download:()=>void)=>void;view:MatchView;room:Room;send:(c:Command)=>Promise<void>;busy:boolean;onExit:()=>void;onRematch:()=>void;notify:(s:string)=>void;onSettings:()=>void;onTutorialRestart:()=>void;onTutorialExit:()=>void;onTutorialNext:()=>void}
export default function Battle({accountRequired=false,signedIn=false,onSaveMatch,saveBusy=false,savedMatch=false,onSaveReport,view,room,send,busy:networkBusy,onExit,onRematch,notify,onSettings,onTutorialRestart,onTutorialExit,onTutorialNext}:Props){
 const {fullscreen,toggle:toggleFullscreen}=useBattleFullscreen();
 const arenaRef=useRef<HTMLDivElement>(null);const [motionBusy,setMotionBusy]=useState(false);const busy=networkBusy||motionBusy;
 const [boardPresentation,setBoardPresentation]=useState(()=>initialBoardPresentation(view));
 let presented=boardPresentation;
 if(boardPresentation.view!==view){presented=presentBoard(boardPresentation,view);setBoardPresentation(presented)}
 const finishDeparture=useCallback((id:string)=>setBoardPresentation(previous=>finishBoardDepartures(previous,[id])),[]);
 const motionChanged=useCallback((value:boolean)=>{setMotionBusy(value);if(!value)setBoardPresentation(previous=>finishBoardDepartures(previous))},[]);
 const boardPositions=useRef(new Map<string,{x:number;y:number}>());
 useLayoutEffect(()=>{
  const positions=new Map<string,{x:number;y:number}>();
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.reduced==='true';
  for(const node of arenaRef.current?.querySelectorAll<HTMLElement>('.battle-unit[data-battle-id]')??[]){
   const id=node.dataset.battleId!,position={x:node.offsetLeft,y:node.offsetTop},old=boardPositions.current.get(id);positions.set(id,position);
   if(old&&!reduced&&(Math.abs(old.x-position.x)>1||Math.abs(old.y-position.y)>1))node.animate([{transform:`translate(${old.x-position.x}px,${old.y-position.y}px)`},{transform:'translate(0,0)'}],{duration:240,easing:'cubic-bezier(.2,.7,.2,1)'});
  }
  boardPositions.current=positions;
 },[presented]);
 const me=view.players.find(p=>p.id===view.selfId)!,enemy=view.players.find(p=>p.id!==view.selfId)!;const mine=view.activePlayerId===me.id;
 const [showReplay,setShowReplay]=useState(false),[readMode,setReadMode]=useState(false),[reading,setReading]=useState<{offer?:OfferDefinition;id?:string;actions:Command[]}|null>(null);
 const [showKnown,setShowKnown]=useState(false);
 const previousView=useRef<MatchView|null>(null);const [turnFlash,setTurnFlash]=useState(false);
 useEffect(()=>{const previous=previousView.current;previousView.current=view;if(!previous||previous.matchId!==view.matchId)return;if(previous.activePlayerId!==view.activePlayerId&&view.activePlayerId===view.selfId)setTurnFlash(true);const t=setTimeout(()=>setTurnFlash(false),850);return()=>clearTimeout(t)},[view.version,view.matchId]);
 const [selection,setSelection]=useState<{label:string;actions:Command[]}|null>(null),[details,setDetails]=useState<UnitView|null>(null),[showLog,setShowLog]=useState(false),[offerDrawer,setOfferDrawer]=useState(true),[flex,setFlex]=useState(view.legalActions.find(c=>c.type==='SELECT_FLEX')?.flexIds||['F01','F04','F05']),[mull,setMull]=useState<string[]>([]),[clock,setClock]=useState(30),[concede,setConcede]=useState(false);
 useEffect(()=>{setSelection(null)},[view.version]);useEffect(()=>{const t=setInterval(()=>setClock(room.deadline?Math.max(0,Math.ceil((room.deadline-Date.now())/1000)):30),250);return()=>clearInterval(t)},[room.deadline]);

 const act=async(c:Command)=>{if(busy)return;if(room.tutorial&&c.type!=='CONCEDE'&&!view.legalActions.some(a=>JSON.stringify(a)===JSON.stringify(c))){notify(room.tutorial.objective);return}setSelection(null);await send(c)};
 const inspectOrPlay=(label:string,actions:Command[],data:{offer?:OfferDefinition;id?:string})=>{if(readMode||!actions.length){setReading({...data,actions});return}pick(label,actions)};
 const pick=(label:string,actions:Command[])=>{if(!actions.length){notify(!mine?'等待对手行动':me.timeRemaining<1?'本回合时间已用完':'当前没有合法目标或时间不足');return}if(actions.length===1&&!actions[0].targetId&&!actions[0].targetIds&&!actions[0].sacrificeId){void act(actions[0]);return}setSelection({label,actions})};
 const cardDrag=useCardDrag({arenaRef,selfId:me.id,legalActions:view.legalActions,busy,epoch:`${view.matchId}:${view.version}`,onStart:()=>setSelection(null),onDrop:(commands,label,needsTarget)=>{if(!needsTarget&&commands.length===1)void act(commands[0]);else pick(label,commands)}});
 const target=(id:string)=>{const actions=selection?.actions.filter(c=>c.targetId===id&&!c.targetIds)||[];if(actions.length===1){void act(actions[0]);return true}if(actions.length>1){setSelection({label:'请选择目标的具体上桌效果',actions});return true}return false};
 const skill=(secondary:boolean)=>{const type=secondary?'USE_SECONDARY':'USE_PRIMARY';pick(secondary?'发动进修技能':'发动主技能',view.legalActions.filter(c=>c.type===type))};
 function unit(u:UnitView,own:boolean,departing=false){const legalTarget=!departing&&selection?.actions.some(c=>c.targetId===u.id||c.targetIds?.includes(u.id));const selected=selection?.actions.some(c=>c.type==='ATTACK'&&c.cardId===u.id);const offer=u.kind==='offer'?view.players.flatMap(p=>p.offerZone).find(o=>o.id===u.offerId)?.definition:undefined;
 return <div key={u.id} data-battle-id={u.id} data-departing={departing||undefined} className={`battle-unit ${own?'friendly':'hostile'} ${legalTarget?'targetable':''} ${selected?'selected':''} ${!departing&&u.canAttack&&mine&&own?'ready':''} ${u.taunt?'taunt':''}`}><button disabled={busy||departing} className="unit-main" onClick={()=>{if(target(u.id))return;if(own&&mine)pick(`用「${u.name}」开怼`,view.legalActions.filter(c=>c.type==='ATTACK'&&(c.cardId===u.id||c.offerId===u.id)));else setDetails(u)}} aria-label={`${own?'己方':'敌方'}${u.name}，${u.attack}排面，${u.health}底气`}><div className="unit-portrait"><Art src={offer?.artId?.startsWith('/')?offer.artId:u.templateId?offerArt(u.templateId):supportArt(u.definitionId)} fallback={u.templateId?offerArt(u.templateId):supportArt(u.definitionId)} alt=""/></div><span className="unit-name">{u.name}</span><span className="unit-attack">{u.attack}</span><span className={`unit-health ${u.damage?'damaged':''}`}>{u.health}</span>{u.age&&<span className="unit-age">{u.age}岁</span>}{u.taunt&&<span className="unit-status">挡话</span>}{u.notice&&<span className="notice-stamp">优化通知</span>}{u.frozenUntilTurn>=view.players.find(p=>p.id===u.ownerId)!.ownTurn&&u.frozenUntilTurn>0&&<span className="unit-status frozen">暂停开怼</span>}</button><button className="unit-info" disabled={departing} onClick={()=>setDetails(u)} aria-label={`查看${u.name}规则`}><Icon name="info" size={12}/></button></div>}
 function hero(p:PlayerView,own:boolean){return <div className={`battle-hero ${own?'own-hero':'opponent-hero'} ${selection?.actions.some(c=>c.targetId===p.id)?'targetable':''}`}><button data-battle-id={p.id} className="hero-avatar" onClick={()=>{if(!target(p.id)&&!own)notify('先选择一个可以开怼的己方角色')}} aria-label={`${own?'你的':'对方'}主角，${p.mind}心态`}><Art src={heroPath(p.education.primaryId)}/><Art className="hero-education-badge" src={educationSeal(p.education.secondaryId)} alt=""/><span className="hero-mind">{p.mind}</span></button><div className="hero-meta"><strong>{p.name}</strong><span>{schoolName(p.education.primaryId)} · {schoolName(p.education.secondaryId)}</span><div className="mind-track"><i style={{width:`${Math.max(0,p.mind)/30*100}%`}}/></div>{p.education.primaryId==='H10'&&<div className="jlu-signins">{p.education.jluUltimateUsed?'全校撑腰 · 已兑现':`校友签到 ${'●'.repeat(p.education.jluSignins)}${'○'.repeat(2-p.education.jluSignins)}`}</div>}</div><div className="retort-slot" title={own&&p.retort?.definitionId?cardById[p.retort.definitionId]?.name:'未触发的反话对对手隐藏'}>{p.retort?<><Icon name="mail"/><span>留了一手</span></>:<><Icon name="mail"/><span>反话位</span></>}</div></div>}
 const primary=rules.heroes.find(h=>h.id===me.education.primaryId)!,secondary=education.secondary.find(h=>h.id===me.education.secondaryId)!;
 const targetLabel=(id?:string)=>!id?'无需目标':view.players.find(p=>p.id===id)?.name||view.players.flatMap(p=>p.board).find(u=>u.id===id)?.name||me.offerZone.find(o=>o.id===id)?.definition.name||me.hand.find(h=>h.id===id)?.name||id;
 const commandLabel=(c:Command)=>c.type==='NEGOTIATE'?`拿 ${targetLabel(c.sacrificeId)} 抬价 → ${targetLabel(c.offerId)}（${Math.max(1,(me.offerZone.find(o=>o.id===c.offerId)?.cost||0)-Math.floor((me.offerZone.find(o=>o.id===c.sacrificeId)?.definition.originalTime||0)/2))} 小时）${c.targetId?' · 目标 '+targetLabel(c.targetId):''}${c.benefitChoice?' · 轮岗'+(c.benefitChoice==='attack'?'排面+1':'底气+2'):''}`:c.topic?rules.public_topics.find(t=>t.id===c.topic)?.name:c.targetIds?c.targetIds.map(targetLabel).join(' ＋ '):c.cardId&&c.type.startsWith('USE')?targetLabel(c.cardId):c.benefitChoice?`${targetLabel(c.targetId)} · ${c.benefitChoice==='attack'?'轮岗：排面 +1':'轮岗：底气 +2'}`:targetLabel(c.targetId);
 const cueCommand=selection?.actions[0]||room.tutorial?.allowedCommands[0];
 const selector=(attr:string,id?:string)=>id?`[${attr}="${CSS.escape(id)}"]`:undefined;
 const focusSelector=!room.tutorial||room.tutorial.completed?undefined:selection?cueCommand?.targetId?selector('data-battle-id',cueCommand.targetId):'[data-tutorial-action="0"]':cueCommand?.type==='ATTACK'?selector('data-battle-id',cueCommand.cardId):cueCommand?.type==='DEPLOY_OFFER'?selector('data-offer-id',cueCommand.offerId):cueCommand?.type==='PLAY_CARD'?selector('data-hand-id',cueCommand.cardId):cueCommand?.type==='USE_PRIMARY'?'[data-tutorial="primary"]':cueCommand?.type==='USE_SECONDARY'?'[data-tutorial="secondary"]':cueCommand?.type==='NEGOTIATE'?'[data-tutorial="negotiate"]':cueCommand?.type==='END_TURN'?'[data-tutorial="endTurn"]':cueCommand?.type==='RESOLVE_CHOICE'?selector('data-choice-id',cueCommand.optionId):undefined;
 const [completionReady,setCompletionReady]=useState(false);
 useEffect(()=>{setCompletionReady(false);if(room.tutorial?.completed&&!busy){const timer=setTimeout(()=>setCompletionReady(true),900);return()=>clearTimeout(timer)}},[room.tutorial?.completed,busy]);
 const phases=view.phase==='flex'||view.phase==='mulligan';
 return <div className={`battle-page battle-fit ${room.tutorial?'in-tutorial':''}`} ref={arenaRef}><div className="battle-topbar"><button className="text-btn" onClick={()=>room.tutorial?onTutorialExit():setConcede(true)}><Icon name="logout" size={17}/>离开牌桌</button><div className="battle-brand">秋招斗兽棋<span>OFFER BATTLE</span></div><div className="battle-top-actions"><button className="fullscreen-button" onClick={toggleFullscreen} aria-label={fullscreen?'退出全屏':'进入全屏'} title={fullscreen?'退出全屏 · Esc':'进入全屏'}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d={fullscreen?'M3 8h5V3m8 0v5h5M3 16h5v5m8 0v-5h5':'M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5'}/></svg>{fullscreen?'退出全屏':'全屏'}</button><Badge>{room.tutorial?'入职训练':room.mode==='bot'?'机器人练习':'好友对战'}</Badge><button className="icon-btn" aria-label="设置" onClick={onSettings}><Icon name="settings"/></button><button className="icon-btn" aria-label="战斗记录" onClick={()=>setShowLog(true)}><Icon name="book"/></button></div></div>
 <div className="landscape-hint">大屏全屏体验更佳；竖屏可逐张放大读牌。</div>
 {room.tutorial&&<TutorialGuide tutorial={{...room.tutorial,completed:room.tutorial.completed&&completionReady}} focusSelector={focusSelector} onRestart={onTutorialRestart} onExit={onTutorialExit} onNext={onTutorialNext} busy={busy}/>}
 {(room as any).scenario&&<details className="scenario-guide" open><summary>演示练习 · {(room as any).scenario.title}</summary><ol>{((room as any).scenario.instructions||[]).map((text:string,i:number)=><li key={i}>{text}</li>)}</ol></details>}<div className="arena"><div className="board-grain"/><div className="opponent-zone has-skill-reference">{hero(enemy,false)}<OpponentSkills player={enemy} round={view.round} activePlayerId={view.activePlayerId}/><div className="opponent-resources"><div className="opponent-cards">{Array.from({length:Math.min(enemy.handCount,8)},(_,i)=><div className={`card-back ${enemy.education.primaryId==='H10'?'jlu-back':''}`} key={i}><Icon name="mail" size={15}/></div>)}<span>{enemy.handCount} 手牌 · {enemy.deckCount} 牌库</span></div>{enemy.knownHand?.length>0&&<button className="known-hand-button" onClick={()=>setShowKnown(true)}>已知 {enemy.knownHand.length} 张</button>}<div className="enemy-offers">{enemy.offerZone.map(o=><div className={`offer-mini ${o.status}`} key={o.id} title={`${o.definition.name} · ${o.status}`}><Art src={o.definition.artId?.startsWith('/')?o.definition.artId:offerArt(o.definition.templateId)}/><span>{o.definition.originalTime}</span></div>)}</div></div></div>
 <div data-battle-row={enemy.id} className="board-row enemy-row">{Array.from({length:4},(_,i)=>{const slot=presented.rows[enemy.id]?.[i];return slot?unit(slot.unit,false,slot.departing):<div className="empty-slot" key={`empty-${i}`}><span>◇</span></div>})}</div>
 <div className="topic-bar"><div className="round-counter">第 <b>{view.round}</b> 轮 <small>/ 12</small></div><div className="topic-text"><Icon name={view.topic==='salary'?'crown':view.topic==='life'?'moon':'spark'} size={18}/><strong>{rules.public_topics.find(t=>t.id===view.topic)?.name}</strong><span>{rules.public_topics.find(t=>t.id===view.topic)?.effect}</span></div><div className={`turn-indicator ${mine?'your-turn':''}`}>{mine?'你的回合':'对方回合'}<span>{room.deadline?`${clock}s`:'练习'}</span></div></div>
 <div data-battle-row={me.id} data-card-drop-zone={me.id} className="board-row friendly-row">{Array.from({length:4},(_,i)=>{const slot=presented.rows[me.id]?.[i];return slot?unit(slot.unit,true,slot.departing):<div className="empty-slot" key={`empty-${i}`}><span>◇</span><small>{i===0&&!me.board.length?'让你的 Offer 上桌':''}</small></div>})}</div>
 <div className="player-console">{hero(me,true)}<div className="education-controls"><span className="shared-skill-state">{me.education.usedThisOwnTurn?'本回合学历行动已用':'本回合可发动 1 次学历技能'}</span><div><button data-tutorial="primary" className="skill-button" disabled={busy||!mine||me.education.usedThisOwnTurn||!!room.tutorial&&!view.legalActions.some(a=>a.type==='USE_PRIMARY')} onClick={()=>skill(false)} title={primary.text}><Icon name="crown" size={17}/><span>{primary.id==='H10'?(me.education.jluUltimateUsed?'校友饭局':me.education.jluSignins===2?'全校撑腰':'校友集合'):primary.skill}<small>{primary.time_cost} 小时 · 主技能</small></span></button><button data-tutorial="secondary" className="skill-button secondary" disabled={busy||!mine||view.round<4||me.education.usedThisOwnTurn||me.education.secondaryUsed||!!room.tutorial&&!view.legalActions.some(a=>a.type==='USE_SECONDARY')} onClick={()=>skill(true)} title={secondary.text}><Icon name={view.round<4?'lock':'spark'} size={17}/><span>{secondary.skill}<small>{me.education.secondaryUsed?'本局已兑现':view.round<4?'第 4 轮毕业':`${secondary.time_cost} 小时 · 进修`}</small></span></button></div></div><div className="time-controls"><div className="time-resource"><Icon name="clock" size={20}/><strong>{me.timeRemaining}<small> / {Math.min(8,view.round)}</small></strong><span>可用时间</span></div><button data-tutorial="endTurn" className="end-turn" disabled={!mine||busy||view.phase!=='playing'||!!view.pendingChoice||!!room.tutorial&&!view.legalActions.some(a=>a.type==='END_TURN')} onClick={()=>act({type:'END_TURN'})}>{busy?'结算中…':mine?'结束回合':'对手思考中'}<Icon name="arrow" size={17}/></button></div></div>
 </div>
 <div className="hand-dock"><div className="offer-drawer"><div className="drawer-heading"><button onClick={()=>setOfferDrawer(!offerDrawer)}><Icon name="cards" size={16}/>我的 Offer <span>{me.offerZone.filter(o=>o.status==='available').length}/3</span></button><button data-tutorial="negotiate" className="negotiate-btn" disabled={me.negotiationUsed||!mine||busy||!!room.tutorial&&!view.legalActions.some(a=>a.type==='NEGOTIATE')} onClick={()=>pick('选择谈薪筹码与上桌 Offer',view.legalActions.filter(c=>c.type==='NEGOTIATE'))}>{me.negotiationUsed?'已谈薪':'谈薪 ↗'}</button></div>{offerDrawer&&<div className="offer-hand">{me.offerZone.filter(o=>o.status==='available'||o.status==='negotiated').map(o=><div {...cardDrag.sourceProps({kind:'offer',id:o.id,label:`让「${o.definition.name}」上桌`,disabled:o.status!=='available'||!mine||readMode})} data-offer-id={o.id} key={o.id} className={o.status==='negotiated'?'negotiated':''}><OfferCard small offer={o.definition} cost={o.cost} disabled={busy||o.status==='negotiated'||o.cost>me.timeRemaining||!mine} selected={selection?.actions.some(c=>c.offerId===o.id)} onClick={()=>inspectOrPlay(`让「${o.definition.name}」上桌`,view.legalActions.filter(c=>c.type==='DEPLOY_OFFER'&&c.offerId===o.id),{offer:o.definition})}/>{o.status==='negotiated'&&<span className="negotiated-stamp">用于谈薪</span>}</div>)}</div>}</div>
 <div className="hand-section"><div className="hand-label"><span>你的手牌 <b>{me.handCount}/8</b><button className={`read-mode ${readMode?'active':''}`} onClick={()=>setReadMode(!readMode)}><Icon name="book" size={12}/>{readMode?'读牌模式 · 点击切回':'放大读牌'}</button><small className="drag-help">可拖到牌桌出牌</small></span><span>{me.deckCount} 张牌库{me.fatigue>0?` · 焦虑 ${me.fatigue}`:''}</span></div><div className="hand-cards">{me.hand.map(h=><div {...cardDrag.sourceProps({kind:'hand',id:h.id,offerId:h.offer?.id,label:`打出「${h.name}」`,disabled:!mine||readMode})} className="hand-card-wrapper" data-hand-id={h.id} key={h.id}>{h.kind==='offer'&&h.offer?<OfferCard key={h.id} small offer={h.offer.definition} cost={h.cost} disabled={busy||h.cost>me.timeRemaining||!mine} onClick={()=>inspectOrPlay(`让「${h.name}」返场`,view.legalActions.filter(c=>(c.type==='PLAY_CARD'||c.type==='DEPLOY_OFFER')&&(c.cardId===h.id||c.offerId===h.offer?.id)),{offer:h.offer!.definition})}/>:<CommonCard key={h.id} id={h.definitionId} small cost={h.cost} disabled={busy||h.cost>me.timeRemaining||!mine} selected={selection?.actions.some(c=>c.cardId===h.id)} onClick={()=>inspectOrPlay(`打出「${h.name}」`,view.legalActions.filter(c=>c.type==='PLAY_CARD'&&c.cardId===h.id),{id:h.definitionId})}/>}</div>)}{!me.hand.length&&<p className="empty-hand">手牌暂空。每回合开始抽 1 张。</p>}</div></div></div>
 {selection&&<div className="target-prompt"><div><strong>{selection.label}</strong><span>点击发光目标，或选择下方行动</span></div><div className="target-options">{selection.actions.map((c,i)=><button data-tutorial-action={i} disabled={busy} key={i} onClick={()=>act(c)}>{commandLabel(c)}</button>)}</div><button className="icon-btn" onClick={()=>setSelection(null)} aria-label="取消选牌"><Icon name="close"/></button></div>}
 {phases&&<Modal title={view.phase==='flex'?'看清对手，再留三张底牌。':'起手不错，还能再挑。'} onClose={()=>{}} wide>{view.phase==='flex'?<><p>对手：{schoolName(enemy.education.primaryId)} / {schoolName(enemy.education.secondaryId)}。选择 3 张不重复的应对牌。</p><div className="setup-offers">{enemy.offerZone.map(o=><OfferCard small key={o.id} offer={o.definition}/>)}</div><div className="flex-selection">{rules.flex_cards.map(c=><CommonCard key={c.id} id={c.id} small selected={flex.includes(c.id)} onClick={()=>setFlex(flex.includes(c.id)?flex.filter(x=>x!==c.id):flex.length<3?[...flex,c.id]:flex)}/>)}</div><button className="btn gold full" disabled={flex.length!==3||me.flexReady||busy} onClick={()=>act({type:'SELECT_FLEX',flexIds:flex})}>{me.flexReady?'等待对方选牌…':`确认应对牌 ${flex.length}/3`}</button></>:<><p>最多更换 2 张通用牌。Offer 独立公开，不进入普通牌库。</p><div className="flex-selection">{me.hand.map(h=><CommonCard key={h.id} id={h.definitionId} selected={mull.includes(h.id)} onClick={()=>setMull(mull.includes(h.id)?mull.filter(x=>x!==h.id):mull.length<2?[...mull,h.id]:mull)}/>)}</div><button className="btn gold full" disabled={me.mulliganReady||busy} onClick={()=>act({type:'MULLIGAN',cardIds:mull})}>{me.mulliganReady?'等待对方准备…':mull.length?`更换 ${mull.length} 张，开始对局`:'保留起手，开始对局'}</button></>}</Modal>}
 {view.pendingChoice&&view.pendingChoice.ownerId===me.id&&<Modal title="完成技能选择" onClose={()=>notify('行动已支付时间，请完成选择')}><p>行动已经支付时间。请选择一项继续；关闭面板不会退还费用。</p><div className="choice-options">{view.pendingChoice.options.map(o=><button data-choice-id={o.id} disabled={busy} className="btn subtle" key={o.id} onClick={()=>act({type:'RESOLVE_CHOICE',choiceId:view.pendingChoice!.id,optionId:o.id})}>{o.label}</button>)}</div></Modal>}
 {details&&<Modal title={details.name} onClose={()=>setDetails(null)}><div className="unit-details"><Art src={details.templateId?offerArt(details.templateId):supportArt(details.definitionId)}/><div><Badge>{details.age?`${details.age} 岁`:'助阵角色'}</Badge><h2>{details.attack} 排面 / {details.health} 底气</h2><p>{details.templateId?templateById[details.templateId]?.main_effect:cardById[details.definitionId]?.rules_text}</p>{details.benefitId&&<p>{benefitById[details.benefitId]?.name}：{benefitById[details.benefitId]?.text}</p>}<p>已受伤害：{details.damage} · 底气上限：{details.maxHealth}</p>{details.modifiers.map((m,i)=><p key={i}>{m.source}：排面 {m.attack>=0?'+':''}{m.attack} / 底气 {m.health>=0?'+':''}{m.health}</p>)}</div></div></Modal>}
 {showLog&&<Modal title="这局都发生了什么" onClose={()=>setShowLog(false)}><ol className="battle-log">{view.events.filter(e=>e.text).map(e=><li key={e.sequence}><span>{String(e.sequence).padStart(2,'0')}</span>{e.text}</li>)}</ol></Modal>}
 {concede&&<Modal title="要离开本局吗？" onClose={()=>setConcede(false)}><p>正在进行的对局会记为认输，已收集的 Offer 和配队仍然保留。</p><div className="modal-actions"><button className="btn subtle" onClick={()=>setConcede(false)}>继续战斗</button><button className="btn gold" onClick={async()=>{if(view.phase!=='finished')await act({type:'CONCEDE'});setConcede(false);onExit()}}>认输并离开</button></div></Modal>}
 {view.phase==='finished'&&!room.tutorial&&!motionBusy&&<Modal title={view.result?.winnerId===me.id?'这一局，你赢得很有底气。':view.result?.winnerId?'暂时下班，下局反杀。':'旗鼓相当，各自下班。'} onClose={onExit} wide><div className="result-banner"><Icon name="trophy" size={58}/><span className="eyebrow">{view.result?.winnerId===me.id?'OFFER ACCEPTED':'MATCH COMPLETE'}</span><h1>{view.result?.winnerId===me.id?'胜利':view.result?.winnerId?'惜败':'平局'}</h1><p>{view.result?.reason} · 第 {view.round} 轮</p><div className="result-score"><span>{me.name}<b>{me.mind}</b></span><small>心态</small><span>{enemy.name}<b>{enemy.mind}</b></span></div></div><div className="highlights">{view.events.filter(e=>/谈薪|退场|全校|通知|合同|胜|心态/.test(e.text)).slice(-3).map(e=><p key={e.sequence}><Icon name="spark" size={14}/>{e.text}</p>)}</div><div className="modal-actions">{accountRequired&&!room.scenario&&<button className="btn subtle" disabled={saveBusy||savedMatch} onClick={onSaveMatch}><Icon name="mail"/>{saveBusy?'正在保存…':savedMatch?'已保存到我的对局':'长期保存这局'}</button>}<button className="btn subtle" onClick={()=>exportBattle(view).catch(()=>notify('分享图生成失败，请重试'))}><Icon name="spark"/>保存名场面</button><button className="btn subtle" onClick={()=>{const download=()=>{const blob=new Blob([JSON.stringify({rulesVersion:view.rulesVersion,room:room.code,result:view.result,events:view.events},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Offer战报.json';a.click();URL.revokeObjectURL(a.href)};if(onSaveReport)onSaveReport(download);else download()}}><Icon name="download"/>保存战报</button><button className="btn subtle" onClick={()=>setShowReplay(true)}><Icon name="replay"/>回放本局</button><button className="btn gold" onClick={onRematch}>同样阵容再来<Icon name="arrow"/></button></div>{accountRequired&&<p className="save-match-note">{signedIn?'长期保存的对局可在“我的对局”中再次回放。':'游客可以回看本局、保存名场面；登录后可长期保存对局与 JSON 战报。'}</p>}</Modal>}
 {reading&&<Modal title={reading.offer?.name||cardById[reading.id!]?.name||'卡牌详情'} onClose={()=>setReading(null)}><div className="read-card">{reading.offer?<OfferCard offer={reading.offer}/>:<CommonCard id={reading.id!}/>}</div><p className="read-rules">{reading.offer&&<><strong>{reading.offer.company} · {reading.offer.role}</strong><br/></>}{reading.offer?templateById[reading.offer.templateId]?.main_effect:cardById[reading.id!]?.rules_text}</p>{reading.offer?.benefitId&&<p className="read-rules">{benefitById[reading.offer.benefitId]?.name}：{benefitById[reading.offer.benefitId]?.text}</p>}<button className="btn gold full" disabled={!reading.actions.length} onClick={()=>{const r=reading;setReading(null);pick(r.offer?.name||cardById[r.id!]?.name||'出牌',r.actions)}}>{!mine?'等待你的回合':!reading.actions.length?'当前时间不足，或没有合法目标':'选择使用这张牌'}</button></Modal>}
 {showKnown&&<Modal title="已经窥视的手牌" onClose={()=>setShowKnown(false)}><p>这里只显示你实际看过、目前仍在对手手里的牌。之后新抽的牌继续隐藏。</p><div className="flex-selection">{enemy.knownHand.map(h=>h.kind==='offer'&&h.offer?<OfferCard key={h.id} small offer={h.offer.definition}/>:<CommonCard key={h.id} small id={h.definitionId}/>)}</div></Modal>}
 {showReplay&&<Replay roomId={room.id} matchId={view.matchId} onClose={()=>setShowReplay(false)}/>}
 {cardDrag.overlay}
 <BattleEffects view={view} arenaRef={arenaRef} onBusyChange={motionChanged} onDepartureComplete={finishDeparture}/>
 {turnFlash&&<div className="turn-flash">轮到你了<small>让这份 Offer 说话</small></div>}

 </div>
}
