import SceneAnchor from '../scene/SceneAnchor';
import {useState} from 'react';
import {api,type Profile} from '../api';
import {CARDS,rules} from '../game/catalog';
import {exampleOffers} from '../game/offers';
import type {Loadout,OfferDefinition} from '../game/types';
import {Icon,OfferCard,CommonCard,Modal} from '../ui';
import {CardDetails,type ReadingCard} from '../components/CardDetails';
import OfferReplacement from '../components/OfferReplacement';
import ShareDialog from '../components/ShareDialog';

export default function Collection({offers,profile,loadout,onProfile,onLoadout,onCreate,onEdit,notify}:{offers:OfferDefinition[];profile:Profile|null;loadout:Loadout;onProfile:(profile:Profile)=>void;onLoadout:(loadout:Loadout)=>void;onCreate:()=>void;onEdit:(offer:OfferDefinition,intent:'revise'|'copy')=>void;notify:(message:string)=>void}){
 const [tab,setTab]=useState('offers'),[search,setSearch]=useState(''),[origin,setOrigin]=useState('all'),[cost,setCost]=useState('all'),[template,setTemplate]=useState('all'),[benefit,setBenefit]=useState('all');
 const [reading,setReading]=useState<ReadingCard|null>(null),[replace,setReplace]=useState<OfferDefinition|null>(null),[remove,setRemove]=useState<OfferDefinition|null>(null),[sharing,setSharing]=useState<OfferDefinition|null>(null),[working,setWorking]=useState(false);
 const publicIds=new Set(exampleOffers.map(o=>o.id));
 const add=(o:OfferDefinition)=>{if(loadout.offers.some(x=>x.id===o.id)){notify('这张卡已经在阵容里');return}if(loadout.offers.length===3){setReplace(o);return}onLoadout({...loadout,offers:[...loadout.offers,o]});notify('已加入阵容')};
 const visible=offers.filter(o=>(origin==='all'||(origin==='public')===publicIds.has(o.id))&&(cost==='all'||o.originalTime===Number(cost))&&(template==='all'||o.templateId===template)&&(benefit==='all'||(benefit==='none'?!o.benefitId:o.benefitId===benefit))&&(o.name+' '+o.company+' '+o.role).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 async function refresh(){onProfile(await api<Profile>('/api/profile'))}
 async function erase(){if(!remove||working)return;setWorking(true);try{await api(`/api/offers/${encodeURIComponent(remove.id)}`,undefined,'DELETE');await refresh();if(loadout.offers.some(x=>x.id===remove.id))onLoadout({...loadout,offers:loadout.offers.filter(x=>x.id!==remove.id)});setRemove(null);notify('已移入回收站，30 天内可恢复')}catch(e){notify((e as Error).message)}finally{setWorking(false)}}
 return <div className="page collection-page"><div className="page-heading"><SceneAnchor kind="collection"/><div><span className="eyebrow">THE OFFER COLLECTION</span><h1>每一张，都有<em>话要说。</em></h1><p>公共体验卡随时可用。你的私人卡，单独收好。</p></div><button className="btn gold" onClick={onCreate}><Icon name="plus"/>录入新 Offer</button></div>
  <div className="collection-toolbar"><div className="tabs">{[['offers',`Offer · ${offers.length}`],['support','助阵'],['action','行动'],['retort','反话'],['trash',`回收站 · ${profile?.deletedOffers?.length||0}`]].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><input aria-label="搜索卡牌" className="search-input" placeholder="搜索岗位、公司、卡名…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  {tab==='offers'&&<><div className="collection-filters"><label>来源<select value={origin} onChange={e=>setOrigin(e.target.value)}><option value="all">全部卡片</option><option value="private">我的私人卡</option><option value="public">公共体验卡</option></select></label><label>耗时<select value={cost} onChange={e=>setCost(e.target.value)}><option value="all">全部耗时</option>{[2,3,4,5,6,7].map(n=><option key={n}>{n}</option>)}</select></label><label>玩法类型<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="all">全部类型</option>{rules.offer_templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>条款<select value={benefit} onChange={e=>setBenefit(e.target.value)}><option value="all">全部条款</option><option value="none">不带条款</option>{rules.benefits.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><p className="collection-count" role="status">找到 {visible.length} 张卡 · 点击卡面阅读完整详情</p><div className="card-grid">{visible.map(o=><article className="collection-card" key={o.id}><span className={`collection-origin ${publicIds.has(o.id)?'public':'private'}`}>{publicIds.has(o.id)?'公共体验卡':'我的私人卡'}</span><OfferCard offer={o} onClick={()=>setReading({offer:o,private:!publicIds.has(o.id)})}/><div className="collection-card-actions"><button className="text-btn" onClick={()=>add(o)}>加入阵容<Icon name="plus" size={14}/></button><button className="icon-btn" aria-label={`分享${o.name}`} onClick={()=>setSharing(o)}><Icon name="download" size={18}/></button></div>{!publicIds.has(o.id)&&<div className="collection-card-actions"><button className="text-btn" onClick={()=>onEdit(o,'revise')}>修订</button><button className="text-btn" onClick={()=>onEdit(o,'copy')}>另存副本</button><button className="text-btn" onClick={()=>setRemove(o)}>删除</button></div>}</article>)}</div>{!visible.length&&<p className="empty-collection">没有符合条件的卡片。可以清除筛选，或制作第一张私人卡。</p>}</>}
  {['support','action','retort'].includes(tab)&&<div className="common-grid">{CARDS.filter(c=>c.type===tab&&(c.name+c.rules_text).includes(search)).map(c=><CommonCard key={c.id} id={c.id} onClick={()=>setReading({cardId:c.id})}/>)}</div>}
  {tab==='trash'&&<section className="collection-trash"><p>删除的私人卡保留 30 天。恢复不会自动改动阵容；旧对局始终保留当时的卡牌定义。</p>{profile?.deletedOffers?.map(d=><div key={d.offer.id}><span><strong>{d.offer.name}</strong><br/>保留至 {new Date(d.expiresAt).toLocaleDateString()}</span><button className="btn subtle" disabled={working} onClick={async()=>{setWorking(true);try{await api(`/api/offers/${encodeURIComponent(d.offer.id)}/restore`,{});await refresh();notify('已恢复到私人收藏')}catch(e){notify((e as Error).message)}finally{setWorking(false)}}}>恢复这张卡</button></div>)}</section>}
  {reading&&<CardDetails card={reading} onClose={()=>setReading(null)}/>}
  {replace&&<OfferReplacement incoming={replace} current={loadout.offers} onClose={()=>setReplace(null)} onReplace={index=>{onLoadout({...loadout,offers:loadout.offers.map((o,i)=>i===index?replace:o)});setReplace(null);notify('已替换选定位置，原卡仍在卡册')}}/>}
  {remove&&<Modal title="把这张卡放进回收站？" onClose={()=>{if(!working)setRemove(null)}}><p><strong>{remove.name}</strong> 将从私人收藏移除，30 天内可以恢复。</p>{loadout.offers.some(o=>o.id===remove.id)&&<p className="delete-reference-warning">当前阵容正在使用它，删除后该位置会空出。开始下一局前，需要补齐三份 Offer。</p>}<p>已经开始的对局和历史回放保持原样。</p><div className="modal-actions"><button className="btn subtle" disabled={working} onClick={()=>setRemove(null)}>保留</button><button className="btn gold" disabled={working} onClick={()=>void erase()}>{working?'正在移入…':'确认移入回收站'}</button></div></Modal>}
  {sharing&&<ShareDialog source={{offer:sharing}} notify={notify} onClose={()=>setSharing(null)}/>}
 </div>
}
