import {useEffect,useState} from 'react';
import {rules,templateById} from '../game/catalog';
import {compileOffer} from '../game/offers';
import type {OfferProfile,OfferDefinition} from '../game/types';
import {OfferCard,Icon,Badge} from '../ui';
import {api} from '../api';
import {exportOffer} from '../share';
const initial:OfferProfile={company_display_name:'我的心动公司',ownership:'private',industry:'internet',company_stage:'established',role_family:'algorithm',role_title:'算法工程师',city:'',monthly_fixed_cny:25000,guaranteed_months:16,annual_fixed_allowance_cny:0,annual_target_bonus_cny:80000,annual_equity_cny:0,one_time_signing_cny:0,confirmed_benefits:[]};
export default function CreateOffer({onSaved,onBuild,notify}:{onSaved:(o:OfferDefinition)=>void;onBuild:()=>void;notify:(s:string)=>void}){const [form,setForm]=useState(initial),[benefit,setBenefit]=useState(''),[paste,setPaste]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState<OfferDefinition|null>(null),[ref,setRef]=useState(''),[flavor,setFlavor]=useState(0),[gender,setGender]=useState('默认造型');
 const [capabilities,setCapabilities]=useState({imageProvider:false,textProvider:false}),[job,setJob]=useState<any>(null);
 useEffect(()=>{api('/api/capabilities').then(setCapabilities).catch(()=>{})},[]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.state))return;const t=setInterval(()=>{api(`/api/generation/jobs/${job.id}`).then(async d=>{setJob(d.job);if(d.job.state==='ready'){const p=await api('/api/profile');const o=p.offers.find((x:OfferDefinition)=>x.id===saved?.id);if(o){setSaved(o);onSaved(o)}}}).catch(e=>notify(e.message))},1200);return()=>clearInterval(t)},[job?.id,job?.state,saved?.id]);
 const update=(o:Partial<OfferProfile>)=>{setForm({...form,...o});setConfirmed(false);setSaved(null)};let preview:OfferDefinition|null=null;try{preview=compileOffer({...form,confirmed_benefits:benefit?[benefit]:[]},benefit||null,'preview')}catch{}
 async function save(){if(!confirmed)return;setBusy(true);try{const result=await api('/api/offers',{profile:{...form,confirmed_benefits:benefit?[benefit]:[]},benefitId:benefit||null,creative:{gender,flavor}});setSaved(result.offer);onSaved(result.offer);notify('Offer 已收入收藏，可以拿去开打了')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 const parse=()=>{const next={...form};const m=paste.match(/(?:月薪|月固定|月工资)[：:\s]*(\d+(?:\.\d+)?)\s*(k|K|万|元)?/);if(m)next.monthly_fixed_cny=Number(m[1])*(m[2]?.toLowerCase()==='k'?1000:m[2]==='万'?10000:1);const months=paste.match(/(\d+)\s*薪/);if(months)next.guaranteed_months=Number(months[1]);const co=paste.match(/(?:公司|单位)[：:\s]*([^\n，,]+)/);if(co)next.company_display_name=co[1].trim();const role=paste.match(/(?:岗位|职位)[：:\s]*([^\n，,]+)/);if(role)next.role_title=role[1].trim();setForm(next);setConfirmed(false);notify('已提取明确的月薪、薪数、公司与岗位；请逐项确认其余字段')};
 return <div className="page creator-page"><div className="page-heading"><div><span className="eyebrow">YOUR OFFER, YOUR CHARACTER</span><h1>让你的 Offer，<em>站上牌桌。</em></h1><p>一份薪资，一种打法。真实字段编译规则，职业插画赋予个性。</p></div><Badge>本地创作 · 无需密钥</Badge></div><div className="creator-layout"><div className="form-panel"><div className="section-heading"><span>01</span><h2>说说你的 Offer</h2></div><details className="paste-panel"><summary>粘贴 Offer 文本 / 添加参考图 <Icon name="plus" size={15}/></summary><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder="公司：方盒科技\n岗位：算法工程师\n月薪：25k，16 薪"/><button className="btn subtle" onClick={parse} disabled={!paste}>提取明确字段</button><label className="upload-btn">添加参考图片<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){notify('参考图请小于 8MB');return}if(ref)URL.revokeObjectURL(ref);setRef(URL.createObjectURL(f));notify('参考图已展示；请在下方手动确认字段')}}/></label>{ref&&<div className="reference-preview"><img src={ref}/><p>参考图仅在本页展示，不自动识别，不进入对局。</p><button className="text-btn" onClick={()=>{URL.revokeObjectURL(ref);setRef('')}}>移除原图</button></div>}</details>
 <label className="field">卡牌名称<input maxLength={16} value={form.card_display_name||''} onChange={e=>update({card_display_name:e.target.value})} placeholder="例如：大厂算法岗、银行基层、投行做债"/><small>留空时按行业和岗位生成。公司名独立显示在卡面小字里。</small></label><div className="form-grid"><label className="field">公司显示名<input maxLength={24} value={form.company_display_name} onChange={e=>update({company_display_name:e.target.value})}/></label><label className="field">岗位名称<input maxLength={24} value={form.role_title} onChange={e=>update({role_title:e.target.value})}/></label><label className="field">工作城市（可选）<input maxLength={30} value={form.city} onChange={e=>update({city:e.target.value})} placeholder="填写实际城市，不参与战斗数值"/></label><label className="field">公司性质<select value={form.ownership} onChange={e=>update({ownership:e.target.value})}><option value="private">民营企业</option><option value="state_owned">国有企业</option><option value="foreign_owned">外资企业</option><option value="central_state_owned">中央企业</option></select></label><label className="field">所在行业<select value={form.industry} onChange={e=>update({industry:e.target.value})}><option value="internet">互联网 / 游戏</option><option value="manufacturing">制造 / 硬件</option><option value="finance">金融</option><option value="consulting">咨询</option><option value="other">其他</option></select></label><label className="field">职业归类<select value={form.role_family} onChange={e=>update({role_family:e.target.value})}>{[['algorithm','算法 / 开发'],['administration','综合职能'],['product','产品 / 项目'],['hardware_rd','硬件研发'],['management','管理岗'],['sales','销售'],['testing','测试 / 质量'],['hr','人事 / 招聘'],['general_rd','研发'],['general','其他岗位']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">公司阶段<select value={form.company_stage} onChange={e=>update({company_stage:e.target.value})}><option value="established">成熟企业</option><option value="startup">初创企业</option></select></label></div>
 <label className="field">玩法类型<select value={form.selected_template_id||''} onChange={e=>update({selected_template_id:e.target.value||undefined})}><option value="">根据行业与岗位自动匹配</option>{rules.offer_templates.map(t=><option key={t.id} value={t.id}>{t.name} — {t.main_effect}</option>)}</select><small>工作名称保留真实写法；这里只决定固定技能与基础身材。遇到新岗位可以手动修正，不能自定义数值。</small></label><div className="section-heading"><span>02</span><h2>薪酬与福利</h2><small>人民币 · 税前</small></div><div className="form-grid">{([['monthly_fixed_cny','固定月薪','元 / 月'],['guaranteed_months','保证薪数','个月'],['annual_fixed_allowance_cny','年度固定津贴','元'],['annual_target_bonus_cny','年度目标奖金','元'],['annual_equity_cny','年度股权价值','元'],['one_time_signing_cny','一次性签字费','元 · 不计年包']] as const).map(([key,label,unit])=><label className="field" key={key}>{label}<div className="input-unit"><input type="number" min={0} max={key==='guaranteed_months'?36:100000000} value={form[key]} onChange={e=>update({[key]:Number(e.target.value)})}/><span>{unit}</span></div></label>)}</div><label className="field">启用一项已确认条款<select value={benefit} onChange={e=>{setBenefit(e.target.value);setConfirmed(false);setSaved(null)}}><option value="">不启用条款</option>{rules.benefits.map(b=><option key={b.id} value={b.id}>{b.name} — {b.text}</option>)}</select></label><p className="helper">启用条款会减少 1 点初始底气；底气为 1 时改为减少排面。</p>
 <label className="confirmation"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>以上信息与所选条款已经由我确认，愿意在对局中公开公司名和卡牌属性。</span></label><button className="btn gold full" disabled={!confirmed||!preview||busy||!form.company_display_name.trim()} onClick={save}><Icon name="spark"/>{busy?'正在编译与保存…':saved?'更新我的 Offer':'生成我的角色卡'}</button></div>
 <aside className="creation-preview"><div className="preview-label"><span className="live-dot"/>实时卡面预览</div>{preview&&<OfferCard offer={saved||preview}/>}<div className="flavor-quote">“{['年包先放这儿，剩下的你自己体会。','工资先亮，底牌后出。','你负责开场炸裂，我负责还在场上。'][flavor%3]}”</div><button className="text-btn" onClick={()=>setFlavor(flavor+1)}><Icon name="replay" size={14}/>换句狠话</button><div className="compile-receipt"><h3><Icon name="shield" size={16}/>生成依据</h3><p>固定年薪 <strong>{((preview?.annualFixed||0)/10000).toFixed(1)} 万</strong></p><p>计价年包 <strong>{((preview?.annualPackage||0)/10000).toFixed(1)} 万</strong></p><p>玩法类型 <strong>{preview&&templateById[preview.templateId].name}</strong></p><small>月薪 × 保证薪数 + 津贴 + 目标奖金 + 年度股权。一次性签字费不计入。{form.selected_template_id?'玩法类型由你手动确认。':'按已确认行业、性质、岗位类型依次匹配。'}同一组字段始终得到相同数值，改名或换图不会改变属性。规则版本 2.0.0。</small></div>{saved&&<div className="saved-actions"><button className="btn subtle full" disabled={!capabilities.imageProvider||['queued','running'].includes(job?.state)} onClick={async()=>{try{const d=await api(`/api/offers/${saved.id}/appearance`,{stage:'image'});setJob(d.job)}catch(e){notify((e as Error).message)}}}><Icon name="spark"/>{['queued','running'].includes(job?.state)?'个性插画正在生成…':capabilities.imageProvider?'生成新外观':'个性插画 · 需配置图像服务'}</button>{job?.state==='failed'&&<div className="generation-error"><p>{job.error||'生成失败，现有角色仍可开打。'}</p><button className="text-btn" onClick={async()=>{try{const d=await api(`/api/generation/jobs/${job.id}/retry`,{});setJob(d.job)}catch(e){notify((e as Error).message)}}}>重试这一环节</button></div>}<div className="success-label"><Icon name="check"/>已收入收藏 · 本地职业插画</div><button className="btn gold full" onClick={onBuild}>带去开打<Icon name="arrow"/></button><button className="btn subtle full" onClick={()=>exportOffer(saved).catch(()=>notify('分享图生成失败，请重试'))}><Icon name="download"/>保存晒卡图</button></div>}</aside></div></div>
}
