import StarterDeckPicker from '../components/StarterDeckPicker';
import {usePaperFeedback} from '../motion/usePaperFeedback';
import SceneAnchor from '../scene/SceneAnchor';
import {educationAccessory,educationSeal} from '../assets';
import {useState} from 'react';
import ShareDialog from '../components/ShareDialog';
import {CardDetails,type ReadingCard} from '../components/CardDetails';
import OfferReplacement from '../components/OfferReplacement';
import {deckHealth,overseasPrimary} from '../game/deckHealth';
import {PaperCharacter} from '../scene/PaperCharacter';
import {rules,education,CARDS} from '../game/catalog';
import type {Loadout,OfferDefinition} from '../game/types';
import {Icon,Art,heroPath,OfferCard,CommonCard,schoolName,Badge} from '../ui';
export default function LoadoutPage({value,onChange,offers,onBattle,notify}:{value:Loadout;onChange:(l:Loadout)=>void;offers:OfferDefinition[];onBattle:()=>void;notify:(s:string)=>void}){
 const feedback=usePaperFeedback();
 const [tab,setTab]=useState<'offers'|'deck'>('offers'),[school,setSchool]=useState(''),[unlocked,setUnlocked]=useState(localStorage.getItem('jlu-unlocked')==='1');
 const [reading,setReading]=useState<ReadingCard|null>(null),[replacement,setReplacement]=useState<OfferDefinition|null>(null),[sharing,setSharing]=useState(false),[rank,setRank]=useState('');
 const health=deckHealth(value);
 const change=(d:Partial<Loadout>)=>{onChange({...value,...d});if(d.offers)feedback('deckInsert','.deck-health',`deck:${Date.now()}`)};
 const hero=rules.heroes.find(h=>h.id===value.primaryId)!;const secondary=education.secondary.find(h=>h.id===value.secondaryId)!;
 const unlock=(v:string)=>{setSchool(v);if(['吉林大学','吉大'].includes(v.replace(/\s/g,''))){setUnlocked(true);localStorage.setItem('jlu-unlocked','1');change({primaryId:'H10'});notify('隐藏角色已解锁 · 宇宙吉大')}};
 return <div className="page loadout-page"><div className="page-heading"><SceneAnchor kind="loadout"/><div><span className="eyebrow">BUILD YOUR ADVANTAGE</span><h1>牌还没出，<em>气势先到。</em></h1><p>第一学历定打法，第二学历留一招。带上你的三份底气。</p></div><div className="page-actions"><button className="btn subtle" onClick={()=>setSharing(true)}><Icon name="download"/>保存毕业照</button><button className="btn gold" onClick={onBattle} disabled={value.offers.length!==3||value.baseDeck.length!==12||value.flexDeck.length!==3}><Icon name="sword"/>用这套阵容开打</button></div></div>
 <StarterDeckPicker current={value} unlocked={unlocked} onApply={(loadout,title)=>{onChange(loadout);notify(`已应用「${title}」；可以继续微调`)}}/>
 <div className="education-builder"><div className="hero-preview"><div className="hero-halo"/><PaperCharacter artId={hero.id} size={768}/><Art className="education-accessory" src={educationAccessory(value.secondaryId)} alt="进修配饰"/><span className="education-seal"><Art src={educationSeal(value.secondaryId)} alt=""/>{schoolName(value.secondaryId)}</span><div className="hero-caption"><Badge>第一学历 · {hero.name}</Badge><h2>{hero.id==='H10'?'宇宙吉大':hero.skill}</h2><p>{value.primaryId==='H10'&&value.secondaryId==='S10'?'本硕连读 · 宇宙吉大':`${hero.name}出身 · ${schoolName(value.secondaryId)}进修`}</p></div></div>
 <div className="education-form"><div className="section-heading"><span>01</span><h2>选择你的教育背景</h2><small>每回合共享 1 次学历行动</small></div><label className="field school-search">你的学校<input value={school} onChange={e=>unlock(e.target.value)} placeholder="输入学校名，或直接选择下方流派"/></label><div className="school-options">{rules.heroes.filter(h=>h.id!=='H10'||unlocked).map(h=><button key={h.id} className={value.primaryId===h.id?'active':''} onClick={()=>change({primaryId:h.id})}>{h.name}{value.primaryId===h.id&&<Icon name="check" size={13}/>}</button>)}</div>
 {['H07','H08','H09'].includes(value.primaryId)&&<label className="field">海外院校排名（可选）<input type="number" min="1" value={rank} onChange={e=>{setRank(e.target.value);if(e.target.value){try{change({primaryId:overseasPrimary(Number(e.target.value))})}catch{}}}}/><small>1–50 为 Top 50；51–100 为 Top 100；101 起为 100+。</small></label>}<div className="education-skills"><div className="skill-description"><span className="eyebrow">主技能 · 每回合</span><h3>{hero.skill}<b>{hero.time_cost} 时</b></h3><p>{hero.text}</p></div><div className="skill-description secondary"><label className="field">第二学历<select value={value.secondaryId} onChange={e=>change({secondaryId:e.target.value})}>{education.secondary.filter(s=>s.id!=='S10'||unlocked).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><h3>{secondary.skill}<b>{secondary.time_cost} 时</b></h3><p>{secondary.text}</p><small>第 4 轮解锁 · 每局 1 次</small></div></div></div></div>
 <div className="collection-toolbar"><div className="tabs"><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}>02 · 携带 Offer <b>{value.offers.length}/3</b></button><button className={tab==='deck'?'active':''} onClick={()=>setTab('deck')}>03 · 选择牌组 <b>{value.baseDeck.length+value.flexDeck.length}/15</b></button></div></div>
 <section className="deck-health" aria-label="阵容检查"><div><strong>阵容检查</strong><span>按实际卡牌统计，不预测胜率</span></div><div className="deck-health-counts"><span>低耗时基础牌 <b>{health.early}</b></span><span>助阵 <b>{health.support}</b></span><span>行动 <b>{health.action}</b></span><span>反话 <b>{health.retort}</b></span></div><div className="deck-curve" aria-label="通用牌耗时曲线">{health.curve.map(c=><span key={c.cost}><b>{c.count}</b><i style={{height:8+c.count*5}}/><small>{c.cost} 时</small></span>)}</div>{health.warnings.length?<ul>{health.warnings.map(w=><li key={w}>{w}</li>)}</ul>:<p>三份 Offer、12 张基础牌与 3 张应对牌已齐备。</p>}</section>
 {tab==='offers'?<><p className="helper">点击卡面阅读，使用下方按钮调整。加入第四张时，先确认要替换的位置。</p><div className="card-grid">{offers.map(o=><div className="loadout-card" key={o.id}><OfferCard offer={o} selected={value.offers.some(x=>x.id===o.id)} onClick={()=>setReading({offer:o})}/><button className="btn subtle full" onClick={()=>{if(value.offers.some(x=>x.id===o.id))change({offers:value.offers.filter(x=>x.id!==o.id)});else if(value.offers.length<3)change({offers:[...value.offers,o]});else setReplacement(o)}}>{value.offers.some(x=>x.id===o.id)?'移出当前阵容':'加入阵容'}</button></div>)}</div></>:<><div className="strategy-decks">{Object.entries(rules.base_deck_presets).map(([name,deck],i)=><button className="strategy-deck" key={name} onClick={()=>{change({baseDeck:deck});notify(`已应用「${name}」基础牌；当前 Offer 和应对牌保留`)}}><Icon name={['sword','shield','target'][i]} size={30}/><strong>{name}</strong><span>{['低耗时上桌，主动争取先手。','稳住底气，等待成长兑现。','拆台与回手，打乱对手计划。'][i]}</span><small>应用 12 张基础牌</small></button>)}</div><details className="advanced-deck"><summary>进阶构筑 · 基础牌 {value.baseDeck.length}/12，应对牌 {value.flexDeck.length}/3</summary><p>基础牌每种最多 2 张；应对牌不重复。点击卡片读规则，用加减号调整。</p><div className="common-grid">{CARDS.map(c=>{const isFlex=c.id[0]==='F',deck=isFlex?value.flexDeck:value.baseDeck,count=deck.filter(id=>id===c.id).length;return <div className="deck-card" key={c.id}><CommonCard id={c.id} selected={count>0} onClick={()=>setReading({cardId:c.id})}/><div className="quantity"><button aria-label={`移除${c.name}`} disabled={!count} onClick={()=>{const n=[...deck];n.splice(n.indexOf(c.id),1);change(isFlex?{flexDeck:n}:{baseDeck:n})}}>−</button><span>{count} / {isFlex?1:2}{isFlex?' · 应对':''}</span><button aria-label={`添加${c.name}`} disabled={count>=(isFlex?1:2)||deck.length>=(isFlex?3:12)} onClick={()=>change(isFlex?{flexDeck:[...deck,c.id]}:{baseDeck:[...deck,c.id]})}>+</button></div></div>})}</div></details></>}
 {reading&&<CardDetails card={reading} onClose={()=>setReading(null)}/>}
 {replacement&&<OfferReplacement incoming={replacement} current={value.offers} onClose={()=>setReplacement(null)} onReplace={index=>{change({offers:value.offers.map((o,i)=>i===index?replacement:o)});setReplacement(null)}}/>}
 {sharing&&<ShareDialog source={{loadout:value}} onClose={()=>setSharing(false)} notify={notify}/>}

 </div>
}
