import {educationAccessory,educationSeal} from '../assets';
import {useState} from 'react';
import {exportGraduation} from '../share';
import {rules,education,CARDS,presets} from '../game/catalog';
import type {Loadout,OfferDefinition} from '../game/types';
import {Icon,Art,heroPath,OfferCard,CommonCard,schoolName,Badge} from '../ui';
export default function LoadoutPage({value,onChange,offers,onBattle,notify}:{value:Loadout;onChange:(l:Loadout)=>void;offers:OfferDefinition[];onBattle:()=>void;notify:(s:string)=>void}){
 const [tab,setTab]=useState<'offers'|'deck'>('offers'),[school,setSchool]=useState(''),[unlocked,setUnlocked]=useState(localStorage.getItem('jlu-unlocked')==='1');
 const change=(d:Partial<Loadout>)=>onChange({...value,...d});
 const hero=rules.heroes.find(h=>h.id===value.primaryId)!;const secondary=education.secondary.find(h=>h.id===value.secondaryId)!;
 const unlock=(v:string)=>{setSchool(v);if(v.replace(/\s/g,'')==='吉林大学'){setUnlocked(true);localStorage.setItem('jlu-unlocked','1');change({primaryId:'H10'});notify('隐藏角色已解锁 · 宇宙吉大')}};
 return <div className="page loadout-page"><div className="page-heading"><div><span className="eyebrow">BUILD YOUR ADVANTAGE</span><h1>牌还没出，<em>气势先到。</em></h1><p>第一学历定打法，第二学历留一招。带上你的三份底气。</p></div><div className="page-actions"><button className="btn subtle" onClick={()=>exportGraduation(value).catch(()=>notify('毕业照生成失败，请稍后重试'))}><Icon name="download"/>保存毕业照</button><button className="btn gold" onClick={onBattle} disabled={value.offers.length!==3||value.baseDeck.length!==12||value.flexDeck.length!==3}><Icon name="sword"/>用这套阵容开打</button></div></div>
 <div className="education-builder"><div className="hero-preview"><div className="hero-halo"/><Art src={heroPath(hero.id)} alt={hero.name}/><Art className="education-accessory" src={educationAccessory(value.secondaryId)} alt="进修配饰"/><span className="education-seal"><Art src={educationSeal(value.secondaryId)} alt=""/>{schoolName(value.secondaryId)}</span><div className="hero-caption"><Badge>第一学历 · {hero.name}</Badge><h2>{hero.id==='H10'?'宇宙吉大':hero.skill}</h2><p>{value.primaryId==='H10'&&value.secondaryId==='S10'?'本硕连读 · 宇宙吉大':`${hero.name}出身 · ${schoolName(value.secondaryId)}进修`}</p></div></div>
 <div className="education-form"><div className="section-heading"><span>01</span><h2>选择你的教育背景</h2><small>每回合共享 1 次学历行动</small></div><label className="field school-search">你的学校<input value={school} onChange={e=>unlock(e.target.value)} placeholder="输入学校名，或直接选择下方流派"/></label><div className="school-options">{rules.heroes.filter(h=>h.id!=='H10'||unlocked).map(h=><button key={h.id} className={value.primaryId===h.id?'active':''} onClick={()=>change({primaryId:h.id})}>{h.name}{value.primaryId===h.id&&<Icon name="check" size={13}/>}</button>)}</div>
 <div className="education-skills"><div className="skill-description"><span className="eyebrow">主技能 · 每回合</span><h3>{hero.skill}<b>{hero.time_cost} 时</b></h3><p>{hero.text}</p></div><div className="skill-description secondary"><label className="field">第二学历<select value={value.secondaryId} onChange={e=>change({secondaryId:e.target.value})}>{education.secondary.filter(s=>s.id!=='S10'||unlocked).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><h3>{secondary.skill}<b>{secondary.time_cost} 时</b></h3><p>{secondary.text}</p><small>第 4 轮解锁 · 每局 1 次</small></div></div></div></div>
 <div className="collection-toolbar"><div className="tabs"><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}>02 · 携带 Offer <b>{value.offers.length}/3</b></button><button className={tab==='deck'?'active':''} onClick={()=>setTab('deck')}>03 · 选择牌组 <b>{value.baseDeck.length+value.flexDeck.length}/15</b></button></div><select aria-label="推荐阵容" value="" onChange={e=>{const p=presets.find(p=>p.id===e.target.value)!;change({primaryId:p.primary_id,secondaryId:p.secondary_id,offers:p.offer_ids.map(id=>offers.find(o=>o.id===id)!).filter(Boolean),baseDeck:p.base_deck,flexDeck:p.default_flex});notify(`已装备「${p.name}」`)}}><option value="">推荐阵容</option>{presets.filter(p=>unlocked||p.primary_id!=='H10'&&p.secondary_id!=='S10').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
 {tab==='offers'?<><p className="helper">选择 3 张不同的 Offer。点击已选卡牌可移出阵容。</p><div className="card-grid">{offers.map(o=><OfferCard key={o.id} offer={o} selected={value.offers.some(x=>x.id===o.id)} onClick={()=>{if(value.offers.some(x=>x.id===o.id))change({offers:value.offers.filter(x=>x.id!==o.id)});else if(value.offers.length<3)change({offers:[...value.offers,o]});else notify('最多携带 3 张 Offer，请先移出一张')}}/>)}</div></>:<><div className="deck-presets">{Object.entries(rules.base_deck_presets).map(([name,deck])=><button className="btn subtle" key={name} onClick={()=>change({baseDeck:deck})}>{name}</button>)}<button className="text-btn" onClick={()=>change({baseDeck:[]})}>清空基础牌</button><span>基础牌 12 张，每种最多 2 张；应对牌 3 张，不重复。</span></div><div className="common-grid">{CARDS.map(c=>{const isFlex=c.id[0]==='F',deck=isFlex?value.flexDeck:value.baseDeck,count=deck.filter(id=>id===c.id).length;return <div className="deck-card" key={c.id}><CommonCard id={c.id} selected={count>0} onClick={()=>{if(deck.length>=(isFlex?3:12)||count>=(isFlex?1:2)){notify('已达到选择上限，可点击减号移出');return}change(isFlex?{flexDeck:[...deck,c.id]}:{baseDeck:[...deck,c.id]})}}/><div className="quantity"><button aria-label={`移除${c.name}`} disabled={!count} onClick={()=>{const n=[...deck];n.splice(n.indexOf(c.id),1);change(isFlex?{flexDeck:n}:{baseDeck:n})}}>−</button><span>{count} / {isFlex?1:2}{isFlex?' · 应对':''}</span><button aria-label={`添加${c.name}`} disabled={count>=(isFlex?1:2)||deck.length>=(isFlex?3:12)} onClick={()=>change(isFlex?{flexDeck:[...deck,c.id]}:{baseDeck:[...deck,c.id]})}>+</button></div></div>})}</div></>}
 </div>
}
