import {useEffect,useState} from 'react';
import {accountApi,type Account} from '../api';
import {Icon,Modal} from '../ui';
import Replay,{type ReplayData} from './Replay';
import '../styles/account.css';
interface SavedMatch {id:string;createdAt:number|string;opponent:string;outcome?:'win'|'lose'|'draw';result?:{winnerId:string|null;reason:string};round:number;source:'friend'|'local'}
export default function MatchHistory({account,onPlay,notify}:{account:Account;onPlay:()=>void;notify:(text:string)=>void}){
 const [matches,setMatches]=useState<SavedMatch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[busyId,setBusyId]=useState<string|null>(null),[deleting,setDeleting]=useState<SavedMatch|null>(null),[replay,setReplay]=useState<{id:string;record:ReplayData}|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError('');setMatches([]);setReplay(null);void accountApi<{matches:SavedMatch[]}>('/api/matches').then(data=>{if(active)setMatches(data.matches)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[account.id,attempt]);
 async function open(match:SavedMatch){if(busyId)return;setBusyId(match.id);try{const data=await accountApi<ReplayData>(`/api/matches/${encodeURIComponent(match.id)}`);if(!Array.isArray(data.frames)||!data.frames.length)throw new Error('这份战报暂时没有可读取的回放，请稍后重试');setReplay({id:match.id,record:data})}catch(e){notify((e as Error).message)}finally{setBusyId(null)}}
 async function remove(){if(!deleting||busyId)return;setBusyId(deleting.id);try{await accountApi(`/api/matches/${encodeURIComponent(deleting.id)}`,undefined,'DELETE');setMatches(items=>items.filter(item=>item.id!==deleting.id));setDeleting(null);notify('已删除这份保存的对局')}catch(e){notify((e as Error).message)}finally{setBusyId(null)}}
 const stamp=(date:number|string)=>{const d=new Date(date);return Number.isNaN(d.getTime())?'保存时间待同步':d.toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})};
 return <main className="page match-history-page"><div className="page-heading"><div><span className="eyebrow">THE MATCH ARCHIVE</span><h1>这几局，<em>值得留着。</em></h1><p>{account.nickname} 的对局档案 · 在结算页选择“长期保存这局”，下次登录还可回看。</p></div><button className="btn gold" onClick={onPlay}>再打一局<Icon name="arrow"/></button></div>
 {loading?<div className="history-empty" role="status">正在取回你的对局…</div>:error?<div className="history-empty"><p className="account-error" role="alert">{error}</p><button className="btn subtle" onClick={()=>setAttempt(n=>n+1)}>重新加载</button></div>:!matches.length?<div className="history-empty"><Icon name="replay" size={38}/><h2>第一场名局，还在路上。</h2><p>人机或好友对局结束后，点击“长期保存这局”。<br/>这里会留下对手、胜负和可以重新走一遍的回放。</p></div>:<div className="match-history-list">{matches.map(match=><article className="match-history-item" key={match.id}><div><h3><span className="history-outcome">{match.outcome==='win'?'胜利':match.outcome==='lose'?'惜败':match.outcome==='draw'?'平局':'已结束'}</span>对阵 {match.opponent}</h3><p>{stamp(match.createdAt)} · 第 {match.round} 轮 · {match.source==='friend'?'好友对局':'本地人机'}</p></div><div className="match-history-actions"><button className="btn subtle" disabled={!!busyId} onClick={()=>void open(match)}>{busyId===match.id?'处理中…':'回放对局'}<Icon name="replay" size={16}/></button><button className="text-btn" disabled={!!busyId} onClick={()=>setDeleting(match)}>删除</button></div></article>)}</div>}
 {deleting&&<Modal title="删除这份对局记录？" onClose={()=>{if(!busyId)setDeleting(null)}}><p>对阵 {deleting.opponent} 的保存记录将从你的档案中删除。此操作不会删除你的账号、Offer 或朋友自己的记录。</p><div className="modal-actions"><button className="btn subtle" disabled={!!busyId} onClick={()=>setDeleting(null)}>保留记录</button><button className="btn gold" disabled={!!busyId} onClick={()=>void remove()}>{busyId?'正在删除…':'确认删除'}</button></div></Modal>}
 {replay&&<Replay roomId="" matchId={replay.id} record={replay.record} onClose={()=>setReplay(null)}/>}
 </main>
}
