import {useEffect,useState} from 'react';
import {ApiError,migrationSource,previewAccountMigration,commitAccountMigration,type Profile} from '../api';
import type {MigrationChoice,MigrationInput,MigrationItem} from '../game/migration';
import {Modal,Icon} from '../ui';
export default function MigrationDialog({onClose,onComplete}:{onClose:()=>void;onComplete:(profile:Profile)=>void}){
 const [source]=useState<MigrationInput>(()=>migrationSource()),[plan,setPlan]=useState<{revision:number;items:MigrationItem[];canIncludeLoadout:boolean}|null>(null),[choices,setChoices]=useState<Record<string,MigrationChoice>>({}),[includeLoadout,setIncludeLoadout]=useState(false),[includeNickname,setIncludeNickname]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[request,setRequest]=useState<MigrationInput|null>(null);
 const preview=async()=>{setBusy(true);setError('');try{setPlan(await previewAccountMigration(source));setChoices({});setRequest(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{void preview()},[]);
 const commit=async()=>{if(!plan||busy)return;setBusy(true);setError('');const body=request??{...source,choices,includeLoadout,includeNickname,expectedRevision:plan.revision,idempotencyKey:crypto.randomUUID()};setRequest(body);
  try{const result=await commitAccountMigration(body);setDone(true);onComplete(result.profile)}catch(e){setError(e instanceof ApiError&&e.code==='PROFILE_REVISION_CONFLICT'?'云端资料刚刚有更新，请刷新预览后重新选择。':(e as Error).message)}finally{setBusy(false)}};
 const conflicts=plan?.items.filter(i=>i.status==='conflict')??[];
 return <Modal title={done?'已迁移到账号':'把本机卡册带到账号'} onClose={onClose} wide><p>这里展示将要复制的内容。所有本机原件都会保留；相同卡自动去重，冲突卡由你选择。</p>{done?<><p>账号已收到这次选择的卡牌。当前本机阵容保留，可继续练习；好友房会使用账号认可的卡牌定义。</p><button className="btn gold" onClick={onClose}>完成<Icon name="check"/></button></>:<>
 {plan&&<><div className="migration-list">{plan.items.length?plan.items.map(item=><div className="migration-item" key={item.localId}><strong>{item.name}</strong><span>{item.status==='new'?'复制到账号':item.status==='duplicate'?'云端已有相同卡 · 不重复添加':'与云端版本不同'}</span>{item.status==='conflict'&&<fieldset><legend>选择如何处理「{item.name}」</legend>{([['keep-both','保留两份（另存本机版本）'],['use-cloud','使用云端已有版本']] as const).map(([value,label])=><label key={value}><input type="radio" name={item.localId} value={value} checked={choices[item.localId]===value} disabled={busy||!!request} onChange={()=>setChoices(old=>({...old,[item.localId]:value}))}/>{label}</label>)}</fieldset>}</div>):<p>本机还没有自定义卡牌。</p>}</div><label className="confirmation"><input type="checkbox" disabled={!plan.canIncludeLoadout||busy||!!request} checked={includeLoadout} onChange={e=>setIncludeLoadout(e.target.checked)}/><span>同时将本机阵容设为账号阵容（替换账号当前阵容）</span></label><label className="confirmation"><input type="checkbox" disabled={busy||!!request} checked={includeNickname} onChange={e=>setIncludeNickname(e.target.checked)}/><span>同时使用本机昵称「{source.nickname}」</span></label></>}
 {error&&<p role="alert" className="form-error">{error}</p>}<div className="modal-actions"><button className="btn subtle" disabled={busy} onClick={()=>void preview()}>刷新预览</button><button className="btn gold" disabled={busy||!plan||conflicts.some(i=>!choices[i.localId])} onClick={()=>void commit()}>{busy?'正在处理…':request?'重试本次迁移':'确认迁移'}<Icon name="arrow"/></button></div></>}</Modal>
}
