import {useEffect,useLayoutEffect,useState} from 'react';
import {Art,Icon,heroPath} from '../ui';
import type {Command} from '../game/types';
import '../styles/tutorial.css';
export interface TutorialPresentation {lessonId:string;title:string;stepIndex:number;stepCount:number;objective:string;coachLine:string;hint:string;completed:boolean;allowedCommands:Command[];nextLessonId?:string|null;summary?:string[]}
export default function TutorialGuide({tutorial,focusSelector,onRestart,onExit,onNext,busy}:{tutorial:TutorialPresentation;focusSelector?:string;onRestart:()=>void;onExit:()=>void;onNext:()=>void;busy:boolean}){
 const [hint,setHint]=useState(false),[bounds,setBounds]=useState<DOMRect|null>(null);
 useEffect(()=>setHint(false),[tutorial.lessonId,tutorial.stepIndex]);
 useLayoutEffect(()=>{if(busy){setBounds(null);return}let frame:number;const measure=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const e=focusSelector?document.querySelector(focusSelector):null;setBounds(e?.getBoundingClientRect()||null)})};measure();window.addEventListener('resize',measure);window.addEventListener('scroll',measure,true);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',measure);window.removeEventListener('scroll',measure,true)}},[focusSelector,tutorial.stepIndex,tutorial.completed,busy]);
 useEffect(()=>{if(busy||!focusSelector||tutorial.completed||matchMedia('(min-width:1024px) and (min-height:650px)').matches)return;const timer=setTimeout(()=>{const target=document.querySelector(focusSelector);if(!target)return;const r=target.getBoundingClientRect(),coach=document.querySelector('.tutorial-coach')?.getBoundingClientRect();if(r.bottom>innerHeight-24||r.top<(coach?.bottom||0)+16)target.scrollIntoView({behavior:'instant',block:'center',inline:'center'})},70);return()=>clearTimeout(timer)},[focusSelector,tutorial.stepIndex,tutorial.completed,busy]);

 const locate=()=>{if(matchMedia('(min-width:1024px) and (min-height:650px)').matches)return;if(focusSelector)document.querySelector(focusSelector)?.scrollIntoView({behavior:document.documentElement.dataset.reduced==='true'||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center',inline:'center'})};
 if(tutorial.completed)return <div className="lesson-complete-overlay" role="dialog" aria-modal="true" aria-label="本课完成"><section className="lesson-complete"><div className="lesson-complete-seal"><Icon name="check" size={46}/></div><span className="eyebrow">LESSON COMPLETE · 做得漂亮</span><h1>{tutorial.title}<em>完成。</em></h1><p>{tutorial.coachLine||'这一招，你已经学会了。带着它继续往前吧。'}</p>{tutorial.summary&&<ul>{tutorial.summary.map(s=><li key={s}><Icon name="check" size={14}/>{s}</li>)}</ul>}<div className="modal-actions"><button className="btn subtle" onClick={onExit}>返回课程</button><button className="btn gold" disabled={busy} onClick={onNext}>{tutorial.nextLessonId?'下一课':'完成训练，去打一局'}<Icon name="arrow"/></button></div><button className="text-btn center-btn" onClick={onRestart} disabled={busy}><Icon name="replay" size={14}/>再练一次本课</button></section></div>;
 return <><aside className="tutorial-coach" aria-label="导师指引"><div className="coach-portrait"><Art src={heroPath('H05','full')} alt="带教前辈"/></div><div className="coach-message"><div className="coach-topline"><span>带教前辈 · {tutorial.title}</span><b>{Math.min(tutorial.stepIndex+1,tutorial.stepCount)} / {tutorial.stepCount}</b></div><p key={`${tutorial.lessonId}-${tutorial.stepIndex}`} aria-live="polite">{tutorial.coachLine}</p><strong><span>当前目标</span>{tutorial.objective}</strong>{hint&&<div className="coach-hint">{tutorial.hint}</div>}</div><div className="coach-actions"><button onClick={locate} disabled={!focusSelector||busy}><Icon name="target" size={15}/>定位目标</button><button onClick={()=>setHint(!hint)}><Icon name="info" size={15}/>{hint?'收起提示':'给我提示'}</button><button onClick={onRestart} disabled={busy}><Icon name="replay" size={15}/>重来本课</button><button onClick={onExit}><Icon name="logout" size={15}/>课程目录</button></div><div className="coach-progress"><i style={{width:`${(tutorial.stepIndex)/tutorial.stepCount*100}%`}}/></div></aside>{!busy&&bounds&&bounds.width>0&&bounds.bottom>0&&bounds.top<innerHeight&&<div className="tutorial-spotlight" aria-hidden="true" style={{left:bounds.left-5,top:bounds.top-5,width:bounds.width+10,height:bounds.height+10}}><span>点击这里<Icon name="arrow" size={12}/></span></div>}</>;
}
