/** Runtime budgets, not an assertion that every planned scene has been filmed. */
export type MotionChannel='feedback'|'ambient'|'navigation'|'battle'|'attention';
/** A backlog first plays faster (compressScale), and only a very long one snaps to the current table. */
export const MOTION_LIMITS={ambientConcurrent:2,attentionConcurrent:1,compressAfterMs:7000,compressScale:.65,compressFloorMs:320,catchUpAfterMs:12000,resultDeadlineMs:3400} as const;
export const MOTION_CUES=[
  {
    "id": "M01",
    "key": "homeAssemble",
    "channel": "navigation",
    "durationMs": 1600,
    "trigger": "首页首次交互壳就绪",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M02",
    "key": "titleSettle",
    "channel": "ambient",
    "durationMs": 430,
    "trigger": "首页搭台子动作",
    "cancelPolicy": "stop-on-hide-or-preference",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 2,
    "reducedDurationMs": 0
  },
  {
    "id": "M03",
    "key": "propUnfold",
    "channel": "ambient",
    "durationMs": 460,
    "trigger": "场景道具首次出现",
    "cancelPolicy": "stop-on-hide-or-preference",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 2,
    "reducedDurationMs": 0
  },
  {
    "id": "M04",
    "key": "blink",
    "channel": "ambient",
    "durationMs": 150,
    "trigger": "角色静止且无阅读",
    "cancelPolicy": "stop-on-hide-or-preference",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 2,
    "reducedDurationMs": 0
  },
  {
    "id": "M05",
    "key": "idleSway",
    "channel": "ambient",
    "durationMs": 4000,
    "trigger": "完整动效且环境未暂停",
    "cancelPolicy": "stop-on-hide-or-preference",
    "confirmationRequired": false,
    "loops": true,
    "maxConcurrentInChannel": 2,
    "reducedDurationMs": 0
  },
  {
    "id": "M06",
    "key": "quip",
    "channel": "attention",
    "durationMs": 1400,
    "trigger": "首见或用户触发台词",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M07",
    "key": "press",
    "channel": "feedback",
    "durationMs": 90,
    "trigger": "按钮pointerdown或键盘按下",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M08",
    "key": "hoverFocus",
    "channel": "feedback",
    "durationMs": 140,
    "trigger": "悬停或focus-visible",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M09",
    "key": "hotspotReact",
    "channel": "feedback",
    "durationMs": 180,
    "trigger": "道具入口选中",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M10",
    "key": "panelOpen",
    "channel": "navigation",
    "durationMs": 220,
    "trigger": "打开详情或抽屉",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M11",
    "key": "panelClose",
    "channel": "navigation",
    "durationMs": 160,
    "trigger": "关闭详情或抽屉",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M12",
    "key": "collectionTurn",
    "channel": "navigation",
    "durationMs": 360,
    "trigger": "卡册页变更",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M13",
    "key": "cardFocus",
    "channel": "feedback",
    "durationMs": 180,
    "trigger": "选中卡牌",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M14",
    "key": "dragFollow",
    "channel": "feedback",
    "durationMs": 0,
    "trigger": "有效拖拽",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 0
  },
  {
    "id": "M15",
    "key": "snapReturn",
    "channel": "feedback",
    "durationMs": 200,
    "trigger": "拖拽取消",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 0
  },
  {
    "id": "M16",
    "key": "deckInsert",
    "channel": "navigation",
    "durationMs": 260,
    "trigger": "确认阵容替换",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M17",
    "key": "creatorUnfold",
    "channel": "navigation",
    "durationMs": 300,
    "trigger": "进入Offer制作",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M18",
    "key": "generationReady",
    "channel": "attention",
    "durationMs": 440,
    "trigger": "当前任务真实完成",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M19",
    "key": "invitationSent",
    "channel": "feedback",
    "durationMs": 300,
    "trigger": "复制成功或发送确认",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M20",
    "key": "friendSeated",
    "channel": "navigation",
    "durationMs": 420,
    "trigger": "好友实际加入确认",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M21",
    "key": "matchBridge",
    "channel": "navigation",
    "durationMs": 380,
    "trigger": "对局创建成功",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M22",
    "key": "dealCard",
    "channel": "battle",
    "durationMs": 280,
    "trigger": "玩家可见抽牌事件",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M23",
    "key": "deploy",
    "channel": "battle",
    "durationMs": 340,
    "trigger": "上桌正式确认",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M24",
    "key": "attack",
    "channel": "battle",
    "durationMs": 1180,
    "trigger": "开怼正式确认",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M25",
    "key": "hit",
    "channel": "battle",
    "durationMs": 180,
    "trigger": "伤害节点",
    "cancelPolicy": "coalesce-by-damage-node",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M26",
    "key": "buff",
    "channel": "battle",
    "durationMs": 240,
    "trigger": "强化事件",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M27",
    "key": "heal",
    "channel": "battle",
    "durationMs": 260,
    "trigger": "恢复事件",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M28",
    "key": "retortCancel",
    "channel": "battle",
    "durationMs": 300,
    "trigger": "反话真实揭示",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M29",
    "key": "ageAdvance",
    "channel": "battle",
    "durationMs": 220,
    "trigger": "Offer年龄推进",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M30",
    "key": "notice",
    "channel": "battle",
    "durationMs": 360,
    "trigger": "挂优化通知事件",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M31",
    "key": "management",
    "channel": "battle",
    "durationMs": 380,
    "trigger": "转管理成功",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M32",
    "key": "returnToHand",
    "channel": "battle",
    "durationMs": 320,
    "trigger": "收回确认",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M33",
    "key": "retire",
    "channel": "battle",
    "durationMs": 320,
    "trigger": "退场事件",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M34",
    "key": "boardReflow",
    "channel": "battle",
    "durationMs": 380,
    "trigger": "场位变更",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M35",
    "key": "turnBanner",
    "channel": "attention",
    "durationMs": 360,
    "trigger": "玩家回合变更",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M36",
    "key": "resultCurtain",
    "channel": "attention",
    "durationMs": 650,
    "trigger": "胜负已确定",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M37",
    "key": "recapCard",
    "channel": "navigation",
    "durationMs": 420,
    "trigger": "生成真实战报预览",
    "cancelPolicy": "latest-wins",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M38",
    "key": "saveReceipt",
    "channel": "feedback",
    "durationMs": 180,
    "trigger": "真实保存成功",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  },
  {
    "id": "M39",
    "key": "errorNote",
    "channel": "attention",
    "durationMs": 160,
    "trigger": "提交或任务失败",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": false,
    "loops": false,
    "maxConcurrentInChannel": 1,
    "reducedDurationMs": 100
  },
  {
    "id": "M40",
    "key": "topicChange",
    "channel": "battle",
    "durationMs": 260,
    "trigger": "共享话题变更",
    "cancelPolicy": "cancel-or-fast-forward-to-current-state",
    "confirmationRequired": true,
    "loops": false,
    "maxConcurrentInChannel": 4,
    "reducedDurationMs": 100
  }
] as const;
export type MotionCueKey=typeof MOTION_CUES[number]['key'];
export const cueByKey=Object.fromEntries(MOTION_CUES.map(cue=>[cue.key,cue])) as Record<MotionCueKey,typeof MOTION_CUES[number]>;
