import fs from 'node:fs';import path from 'node:path';import React from 'react';import{renderToStaticMarkup}from'react-dom/server';import{chromium}from'@playwright/test';import{PaperCharacter}from'../src/scene/PaperCharacter';import{PAPER_CHARACTER_IDS,type PaperExpression}from'../src/assets';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'assets/paper-source/evidence'),data=(url:string)=>'data:image/webp;base64,'+fs.readFileSync(path.join(root,'public',url)).toString('base64');let counter=0;
function rig(id:string,layer:'character'|'body'|'face'|'prop'='character',expression:PaperExpression='confident',size=320){return renderToStaticMarkup(<PaperCharacter artId={id} size={size<=128?128:768} expression={expression} layer={layer}/>,{identifierPrefix:'qa'+counter++}).replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" width="'+size*.75+'" height="'+size+'" ').replace(/href="([^\"]+)"/g,(_,url)=>'href="'+data(url)+'"');}
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1360,height:900},deviceScaleFactor:1});
const pairs=PAPER_CHARACTER_IDS.map(id=>({id,svg:rig(id),original:'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="320" viewBox="0 0 240 320"><image width="240" height="320" href="'+data('/assets/paper/characters/'+id+'/768.webp')+'"/></svg>',layers:['body','face','prop'].map(layer=>({layer,svg:rig(id,layer as 'body')}))}));
await page.evaluate('window.__name=(fn)=>fn');
const results=await page.evaluate(async pairs=>{async function pixels(s:string){const im=new Image();im.src='data:image/svg+xml;base64,'+btoa(s);await im.decode();const c=document.createElement('canvas');c.width=240;c.height=320;const ctx=c.getContext('2d')!;ctx.drawImage(im,0,0);return ctx.getImageData(0,0,240,320).data;}const checks=[];for(const pair of pairs){const a=await pixels(pair.svg),b=await pixels(pair.original);let max=0,changed=0,total=0;for(let i=0;i<a.length;i++){const d=Math.abs(a[i]-b[i]);max=Math.max(max,d);total+=d;if(d>0)changed++;}const layers=[];for(const l of pair.layers){const d=await pixels(l.svg);let opaque=0;for(let i=3;i<d.length;i+=4)if(d[i]>20)opaque++;layers.push({layer:l.layer,visiblePixels:opaque});}checks.push({id:pair.id,maxChannelDelta:max,changedChannels:changed,meanChannelDelta:total/a.length,layers});}return checks;},pairs);
const css='<style>body{font:14px system-ui;margin:24px;background:#f7f2e8;color:#25313c}.row{display:flex;gap:10px;flex-wrap:wrap;align-items:flex-end}.card{display:flex;flex-direction:column;align-items:center;padding:10px}.dark{background:#25313c;color:white}h2{font-size:18px}svg{display:block}figcaption{margin:8px 0}</style>';
for(let offset=0;offset<PAPER_CHARACTER_IDS.length;offset+=4){const ids=PAPER_CHARACTER_IDS.slice(offset,offset+4);await page.setContent(css+'<h1>Actual PaperCharacter masks · '+ids.join(', ')+'</h1>'+ids.map(id=>'<h2>'+id+'</h2><div class="row">'+['character','body','face','prop'].map(layer=>'<div class="card">'+rig(id,layer as 'body')+'<figcaption>'+layer+'</figcaption></div>').join('')+'</div>').join(''));await page.screenshot({path:path.join(out,'rig-layers-'+offset+'.png'),fullPage:true});}
for(const id of['algorithm','research']){const states=['confident','hit','happy','thinking','blink'] as PaperExpression[];await page.setContent(css+'<h1>'+id+' · generated same-identity face variants</h1>'+[72,128,512].map(size=>'<h2>'+size+' CSS px</h2><div class="row '+(size===128?'dark':'')+'">'+states.map(e=>'<div class="card">'+rig(id,'character',e,size)+'<figcaption>'+e+'</figcaption></div>').join('')+'</div>').join(''));await page.screenshot({path:path.join(out,'expressions-'+id+'.png'),fullPage:true});}
const report={kind:'production-mask-compositing-qa',generatedAt:new Date().toISOString(),checks:results,failures:results.filter(r=>r.maxChannelDelta>0||r.layers.some(l=>l.visiblePixels<100)),manualReview:'pending',limitations:'Static mask and expression QA only, not independent application/motion test acceptance.'};fs.writeFileSync(path.join(out,'rig-qa-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
