import {test,expect,type Page} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {applyCommand,createMatch,defaultLoadout,getView} from '../../src/game/index';
import type {MatchState,Command} from '../../src/game/types';

const account={id:'account-ui-a',username:'test_player',nickname:'留一手的朋友'};
const recovered='new-recovery-key-fixture-1234';
async function prepare(page:Page){await page.addInitScript(()=>{localStorage.setItem('offer-sound','0');localStorage.setItem('offer-motion-preference','reduced')});}
async function fillAuth(page:Page,mode:'register'|'login'='register'){
 const panel=page.locator('.account-layer');await panel.getByRole('button',{name:mode==='register'?'注册账号':'登录',exact:true}).click();await panel.getByLabel('用户名',{exact:true}).fill(account.username);await panel.getByLabel('密码',{exact:true}).fill('Strong-test-password-123');if(mode==='register')await panel.getByLabel('牌桌昵称').fill(account.nickname);await panel.getByRole('button',{name:mode==='register'?'创建账号':'登录并继续',exact:true}).click();
}
async function finishRecovery(page:Page){const panel=page.locator('.account-layer');await expect(panel.getByText('fixture-recovery-code-1234',{exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'保存好了，继续'})).toBeDisabled();await panel.getByLabel('我已妥善保存恢复码').check();await panel.getByRole('button',{name:'保存好了，继续'}).click();}
async function authRoutes(page:Page){await page.route('**/api/auth/register',route=>route.fulfill({json:{token:'account-ui-token',profile:{id:account.id,nickname:account.nickname,offers:[]},account,recoveryKey:'fixture-recovery-code-1234'}}));await page.route('**/api/auth/logout',route=>route.fulfill({json:{ok:true}}));}
function ending(){
 const loadouts=[defaultLoadout('p1','你的角色',5),defaultLoadout('p2','测试机器人',5)] as const;
 let seed=1,state=createMatch([...loadouts],seed,{skipSetup:true,matchId:'account-save-match'});while(state.firstPlayerId!=='p2'){seed++;state=createMatch([...loadouts],seed,{skipSetup:true,matchId:'account-save-match'})}
 const initialState=structuredClone(state),journal:{actorId:string;command:Command}[]=[],frames=[getView(state,'p1')];
 while(true){const actorId=state.activePlayerId,command:Command={type:'END_TURN',commandId:`history-${journal.length}`};const next=applyCommand(state,actorId,command);expect(next.error).toBeUndefined();if(next.state.phase==='finished'){expect(actorId).toBe('p1');return {state,initialState,journal,seed,loadouts:[...loadouts],finished:next.state,frames:[...frames,getView(next.state,'p1')]}}
 journal.push({actorId,command});state=next.state;frames.push(getView(state,'p1'));if(journal.length>30)throw Error('Expected deterministic round cap');
 }
}
async function seedEnding(page:Page){const f=ending();await page.addInitScript(({f})=>{
 localStorage.setItem('offer-active-room','local_account_final');sessionStorage.setItem('offer-local-active-v1',JSON.stringify({expiresAt:Date.now()+3600000,room:{id:'local_account_final',code:'LOCAL',mode:'bot',strategy:'aggressive',training:true,status:'playing',seats:f.loadouts.map((loadout,i)=>({id:loadout.playerId,name:loadout.name,loadout,isBot:i===1,ready:true})),state:f.state,initialState:f.initialState,journal:f.journal,receipts:{},deadline:null,lastBotAt:0,seed:f.seed,skipSetup:true}}));
 },{f});return f;}

test('guest bot and tutorial stay local; friend action requires account',async({page})=>{
 await prepare(page);const requests:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))requests.push(r.url())});await page.goto('./');await expect(page.getByRole('button',{name:'游客 · 登录 / 注册'})).toBeVisible();await page.locator('.hotspot-friends').click();await page.getByRole('button',{name:'创建好友房',exact:true}).click();await expect(page.locator('.account-layer')).toBeVisible();expect(requests).toHaveLength(0);await page.locator('.account-layer').getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('dialog',{name:'把 Offer，摆到朋友面前。'}).getByRole('button',{name:'关闭',exact:true}).click();await page.locator('.hotspot-play').click();await page.getByLabel('开局准备',{exact:true}).selectOption('quick');await page.getByRole('button',{name:'就用这套，开始对局'}).click();await expect(page.locator('.battle-page')).toBeVisible();expect(requests).toHaveLength(0);await page.getByRole('button',{name:'离开牌桌'}).click();await page.getByRole('button',{name:'认输并离开'}).click();await page.locator('.hotspot-tutorial').click();await page.getByRole('button',{name:'开始第一课',exact:true}).click();await expect(page.locator('.battle-page')).toBeVisible();expect(requests).toHaveLength(0);
});

test('invite survives registration and recovery code confirmation, mobile account fits',async({page},testInfo)=>{
 await page.setViewportSize({width:390,height:844});await prepare(page);await authRoutes(page);
 await page.route('**/api/invitations/ABC123',route=>route.fulfill({json:{status:'waiting',hostNickname:'牌桌朋友'}}));
 const snapshot={room:{id:'cloud_invite_ui',code:'ABC123',mode:'friend',status:'waiting',players:[{id:'p1',name:'牌桌朋友',ready:false,connected:true,isBot:false},{id:'p2',name:account.nickname,ready:false,connected:true,isBot:false}],version:0,deadline:null},view:null};
 let joinedCode='';await page.route('**/api/rooms/join',route=>{joinedCode=route.request().postDataJSON().code;return route.fulfill({json:snapshot})});await page.route('**/api/rooms/cloud_invite_ui',route=>route.fulfill({json:snapshot}));await page.routeWebSocket('**/ws?*',socket=>socket.send(JSON.stringify({type:'state',...snapshot})));
 await page.goto('./?room=ABC123');await expect(page.getByText('朋友的牌桌正在等你')).toBeVisible();await expect(page.locator('.account-layer')).toHaveCount(0);await expect(page.getByLabel('房间码或邀请链接')).toHaveValue('ABC123');await page.getByRole('button',{name:'登录后加入这张牌桌',exact:true}).click();await fillAuth(page);await finishRecovery(page);
 await expect(page.locator('.room-code strong')).toHaveText('ABC123');expect(joinedCode).toBe('ABC123');await expect(page.getByRole('button',{name:'准备好了',exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath('mobile-invite-registered.png')});
});

test('login errors are readable and recovery rotates credentials',async({page})=>{
 await prepare(page);await page.route('**/api/auth/login',route=>route.fulfill({status:401,json:{error:'用户名或密码不正确',code:'AUTH_INVALID'}}));let recoveryBody:any;await page.route('**/api/auth/recover',route=>{recoveryBody=route.request().postDataJSON();return route.fulfill({json:{token:'recovered-token',profile:{id:account.id,nickname:account.nickname,offers:[]},account,recoveryKey:recovered}})});await page.goto('./');await page.getByRole('button',{name:'游客 · 登录 / 注册'}).click();await fillAuth(page,'login');await expect(page.getByRole('alert')).toHaveText('用户名或密码不正确');const panel=page.locator('.account-layer');await panel.getByRole('button',{name:'恢复账号',exact:true}).click();await panel.getByLabel('恢复码',{exact:true}).fill('old-recovery-key-fixture');await panel.getByLabel('新密码',{exact:true}).fill('Replacement-password-123');await panel.getByRole('button',{name:'显示密码'}).click();await expect(panel.getByLabel('新密码',{exact:true})).toHaveAttribute('type','text');await panel.getByRole('button',{name:'验证并更新密码'}).click();expect(recoveryBody).toEqual({username:account.username,recoveryKey:'old-recovery-key-fixture',newPassword:'Replacement-password-123'});await expect(panel.getByText(recovered,{exact:true})).toBeVisible();await expect(panel.getByText(/旧恢复码与旧登录会话已失效/)).toBeVisible();await panel.getByLabel('我已妥善保存恢复码').check();await panel.getByRole('button',{name:'保存好了，继续'}).click();await expect(page.getByRole('button',{name:/^(账号 · test_player|你好，留一手的朋友)$/})).toBeVisible();
});

test('finished local match survives registration and saves its real journal; history replay delete and logout',async({page})=>{
 await prepare(page);await authRoutes(page);const f=await seedEnding(page);let saveBody:any,deleted=false;const saved={id:'saved-match-a',createdAt:Date.now(),opponent:'测试机器人',outcome:'draw',round:12,source:'local'};
 await page.route('**/api/matches',route=>{if(route.request().method()==='POST'){saveBody=route.request().postDataJSON();return route.fulfill({json:{ok:true,match:saved}})}return route.fulfill({json:{matches:deleted?[]:[saved]}})});
 await page.route('**/api/matches/saved-match-a',route=>{if(route.request().method()==='DELETE'){deleted=true;return route.fulfill({json:{ok:true}})}return route.fulfill({json:{frames:f.frames,events:getView(f.finished,'p1').events,result:f.finished.result,verified:true}})});
 await page.goto('./');await expect(page.locator('.battle-page')).toBeVisible();await page.getByRole('button',{name:'结束回合',exact:true}).click();await expect(page.locator('.result-banner')).toBeVisible();await page.getByRole('button',{name:'长期保存这局',exact:true}).click();await expect(page.locator('.account-layer')).toBeVisible();await expect(page.locator('.result-banner')).toBeVisible();await fillAuth(page);await finishRecovery(page);await expect(page.getByRole('button',{name:'已保存到我的对局'})).toBeDisabled();expect(saveBody.record.initialState.matchId).toBe(f.initialState.matchId);expect(saveBody.record.journal.length).toBe(f.journal.length+1);expect(saveBody.record.journal.at(-1).command.type).toBe('END_TURN');await expect(page.locator('.result-banner')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.locator('.hotspot-history').click();await expect(page.getByRole('heading',{name:/平局.*对阵 测试机器人/})).toBeVisible();await page.getByRole('button',{name:'回放对局'}).click();await expect(page.getByText('✓ 确定性重放校验一致')).toBeVisible();await page.getByLabel('回放进度').fill(String(f.frames.length-1));await expect(page.locator('.replay-status')).toContainText('第 12 轮');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'删除',exact:true}).click();await expect(page.getByRole('dialog',{name:'删除这份对局记录？'})).toBeVisible();await page.getByRole('button',{name:'保留记录'}).click();expect(deleted).toBe(false);await page.getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'确认删除'}).click();await expect(page.getByText('第一场名局，还在路上。')).toBeVisible();await page.getByRole('button',{name:/^(账号 · test_player|你好，留一手的朋友)$/}).click();await page.getByRole('button',{name:'退出账号',exact:true}).click();await page.getByRole('button',{name:'确认退出账号'}).click();await expect(page.getByRole('button',{name:'游客 · 登录 / 注册'})).toBeVisible();await expect(page.getByRole('button',{name:'我的对局',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('offer-account-token'))).toBeNull();
});

test('guest JSON report requires login and cancelling keeps finished match',async({page})=>{
 await prepare(page);await seedEnding(page);await page.goto('./');await expect(page.locator('.battle-page')).toBeVisible();await page.getByRole('button',{name:'结束回合',exact:true}).click();await expect(page.locator('.result-banner')).toBeVisible();let download=false;page.on('download',()=>{download=true});await page.getByText('完整战报导出',{exact:true}).click();await page.getByRole('button',{name:'保存战报',exact:true}).click();await expect(page.locator('.account-layer')).toBeVisible();expect(download).toBe(false);await page.locator('.account-layer').getByRole('button',{name:'关闭',exact:true}).click();await expect(page.locator('.result-banner')).toBeVisible();await expect(page.getByRole('button',{name:'长期保存这局',exact:true})).toBeVisible();
});

test('expired cloud room can authenticate in recovery without losing its seat',async({page})=>{
 await prepare(page);const state=createMatch([defaultLoadout('p1','你的角色',5),defaultLoadout('p2','联机朋友',5)],14,{skipSetup:true,matchId:'cloud-recovery-match'});const snapshot={room:{id:'cloud_recovery_room',code:'BACK12',mode:'friend',status:'playing',players:state.players.map(p=>({id:p.id,name:p.name,ready:true,connected:true,isBot:false})),version:state.version,deadline:null},view:getView(state,'p1')};
 await page.addInitScript(({account})=>{localStorage.setItem('offer-active-room','cloud_recovery_room');localStorage.setItem('offer-account',JSON.stringify(account));localStorage.setItem('offer-account-token','expired-token')},{account});let failed=0;
 await page.route('**/api/rooms/cloud_recovery_room',route=>{if(route.request().headers().authorization==='Bearer recovered-room-token')return route.fulfill({json:snapshot});failed++;return route.fulfill({status:401,json:{error:'登录已失效',code:'AUTH_REQUIRED'}})});
 await page.route('**/api/auth/login',route=>route.fulfill({json:{token:'recovered-room-token',profile:{id:account.id,nickname:account.nickname,offers:[]},account}}));await page.routeWebSocket('**/ws?*',socket=>socket.send(JSON.stringify({type:'state',...snapshot})));
 await page.goto('./');await expect(page.getByRole('button',{name:'登录恢复对局'})).toBeVisible();expect(failed).toBe(1);expect(await page.evaluate(()=>localStorage.getItem('offer-active-room'))).toBe('cloud_recovery_room');await page.getByRole('button',{name:'登录恢复对局'}).click();await fillAuth(page,'login');await expect(page.locator('.battle-page')).toBeVisible();await expect(page.locator('.recovery-screen')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('offer-active-room'))).toBe('cloud_recovery_room');
});

test('late unauthorized history response cannot clear a newer account login',async({page})=>{
 await prepare(page);await page.addInitScript(({account})=>{localStorage.setItem('offer-account',JSON.stringify(account));localStorage.setItem('offer-account-token','old-history-token')},{account});let releaseOld:()=>void=()=>{};const oldResponse=new Promise<void>(resolve=>{releaseOld=resolve});let requested=false,responded=false;
 await page.route('**/api/matches',async route=>{requested=true;await oldResponse;await route.fulfill({status:401,json:{error:'旧会话失效',code:'AUTH_REQUIRED'}});responded=true});await page.route('**/api/auth/logout',route=>route.fulfill({json:{ok:true}}));await page.route('**/api/auth/login',route=>route.fulfill({json:{token:'new-history-token',profile:{id:'second-account',nickname:'另一位玩家',offers:[]},account:{id:'second-account',username:'second_player',nickname:'另一位玩家'}}}));
 await page.goto('./');await expect(page.getByRole('button',{name:/^(账号 · test_player|你好，留一手的朋友)$/})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:/^(账号 · test_player|你好，留一手的朋友)$/})).toBeVisible();await page.locator('.hotspot-history').click();await expect.poll(()=>requested).toBe(true);await page.getByRole('button',{name:/^(账号 · test_player|你好，留一手的朋友)$/}).click();await page.getByRole('button',{name:'退出账号',exact:true}).click();await page.getByRole('button',{name:'确认退出账号'}).click();await page.getByRole('button',{name:'游客 · 登录 / 注册'}).click();await fillAuth(page,'login');await expect(page.getByRole('button',{name:/^(账号 · second_player|你好，另一位玩家)$/})).toBeVisible();releaseOld();await expect.poll(()=>responded).toBe(true);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('offer-account-token'))).toBe('new-history-token');await expect(page.getByRole('button',{name:/^(账号 · second_player|你好，另一位玩家)$/})).toBeVisible();await expect(page.locator('.match-history-item')).toHaveCount(0);
});
