import {test,expect,type Page} from '@playwright/test';
import type {OfferDefinition} from '../../src/game/types';
async function openForge(page:Page){
 const requests:string[]=[],errors:string[]=[];page.on('request',request=>{if(new URL(request.url()).pathname.includes('/api/'))requests.push(request.url())});page.on('pageerror',error=>errors.push(error.message));await page.route('**/api/**',route=>route.abort());
 await page.goto('./');await page.getByRole('button',{name:/^做我的卡|^录入我的 Offer/}).click();await expect(page.getByRole('region',{name:'实时属性'})).toBeVisible();return {requests,errors};
}
async function storedOffers(page:Page):Promise<OfferDefinition[]>{return page.evaluate(()=>JSON.parse(localStorage.getItem('offer-local-profile-v1')!).offers)}
async function confirmSave(page:Page,name='收入收藏') {await page.getByRole('checkbox',{name:'确认本版资料和公开卡面'}).check();await page.getByRole('button',{name,exact:true}).click();await expect(page.getByText('已收入收藏 · 本地职业插画',{exact:true})).toBeVisible();}
async function completeParsed(page:Page){await page.getByRole('button',{name:'未填写的工作条件采用常规设置',exact:true}).click();await page.getByRole('button',{name:'确认未填写的附加收入均为零',exact:true}).click();await page.getByRole('button',{name:'确认已填写 / 提取的字段',exact:true}).click();await page.getByRole('button',{name:'确认推荐玩法',exact:true}).click();await page.getByLabel('启用一项已确认条款',{exact:true}).selectOption('');}

test('Q01–Q10: empty draft, replacement, explicit confirmation, idempotent collection, revision and copy',async({page},testInfo)=>{
 const observed=await openForge(page);await expect(page.getByLabel('固定月薪',{exact:true})).toHaveValue('');await expect(page.getByLabel('保证薪数',{exact:true})).toHaveValue('');await expect(page.getByTestId('forge-cost')).toHaveText('—');
 await page.getByText('粘贴 Offer 文本 / 添加参考图',{exact:false}).click();await page.getByLabel('Offer 原文',{exact:true}).fill('公司：星海科技\n岗位：销售顾问\n月薪：20k，13薪');await page.getByRole('button',{name:'提取并替换草稿',exact:true}).click();
 await expect(page.getByLabel('固定月薪',{exact:true})).toHaveValue('20000');await expect(page.locator('[data-field-state="annual_target_bonus_cny"]')).toContainText('未填写');await expect(page.getByTestId('forge-cost')).toHaveText('—');
 await completeParsed(page);await expect(page.getByTestId('forge-cost')).toHaveText('4');await page.getByLabel('角色口吻',{exact:true}).selectOption('witty');await expect(page.locator('.forge-card-stage [data-paper-profession]')).toHaveAttribute('data-paper-profession','sales');await page.getByLabel('本地立绘',{exact:true}).selectOption('formal');await expect(page.locator('.forge-card-stage [data-paper-profession]')).toHaveAttribute('data-paper-profession','public');await confirmSave(page);
 const original=(await storedOffers(page))[0];expect(original).toMatchObject({role:'销售顾问',annualPackage:260000,definitionRevision:1,persona:{preferences:{tone:'witty',appearance:'formal'}}});expect(original.artId).toBe('/assets/offer-T02.webp');
 const revision=await page.locator('.offer-forge').getAttribute('data-draft-revision');await page.getByRole('button',{name:'保存晒卡图',exact:true}).click();const share=page.getByRole('dialog',{name:'这张分享图，公开什么？'});await expect(share.getByRole('checkbox',{name:'公司名称'})).not.toBeChecked();await expect(share.getByRole('checkbox',{name:'精确年包'})).not.toBeChecked();await share.getByText('文字预览',{exact:true}).click();await expect(share.locator('details')).not.toContainText('星海科技');await share.getByRole('checkbox',{name:'公司名称'}).check();await expect(share.locator('details')).toContainText('星海科技');await expect(share.getByRole('button',{name:'保存这张图片'})).toBeEnabled();await share.getByRole('button',{name:'关闭',exact:true}).click();await expect(page.locator('.offer-forge')).toHaveAttribute('data-draft-revision',revision!);await expect(page.getByRole('checkbox',{name:'确认本版资料和公开卡面'})).toBeChecked();
 await page.getByLabel('固定月薪',{exact:true}).fill('');await expect(page.getByTestId('forge-cost')).toHaveText('—');await expect(page.locator('[data-field-state="monthly_fixed_cny"]')).toContainText('未确认');await expect(page.getByRole('checkbox',{name:'确认本版资料和公开卡面'})).not.toBeChecked();
 await page.getByLabel('固定月薪',{exact:true}).fill('22000');await confirmSave(page,'修订这张卡');const revised=await storedOffers(page);expect(revised).toHaveLength(1);expect(revised[0].id).toBe(original.id);expect(revised[0].definitionRevision).toBe(2);
 await page.getByLabel('保存方式',{exact:true}).selectOption('copy');await confirmSave(page,'另存副本');const copies=await storedOffers(page);expect(copies).toHaveLength(2);expect(copies[1].id).not.toBe(original.id);
 await page.getByLabel('Offer 原文',{exact:true}).fill('公司：新公司\n岗位：分析师\n年包：60万');await page.getByRole('button',{name:'提取并替换草稿',exact:true}).click();await expect(page.getByLabel('固定月薪',{exact:true})).toHaveValue('');await expect(page.getByLabel('保证薪数',{exact:true})).toHaveValue('');await expect(page.getByTestId('forge-cost')).toHaveText('—');await expect(page.getByText('已收入收藏 · 本地职业插画',{exact:true})).toHaveCount(0);await expect(page.getByText('原文年包：60 万。',{exact:false})).toBeVisible();
 await page.screenshot({path:testInfo.outputPath('draft-replacement.png'),fullPage:true});expect(observed.requests).toEqual([]);expect(observed.errors).toEqual([]);
});

test('Q04/Q05: merge requires visible review, job classification changes invalidate the template, and reload preserves drafts',async({page})=>{
 await openForge(page);await page.getByRole('button',{name:'填入示例',exact:true}).click();await expect(page.getByText('当前使用示例资料',{exact:false})).toBeVisible();
 await page.getByText('粘贴 Offer 文本 / 添加参考图',{exact:false}).click();await page.getByLabel('Offer 原文',{exact:true}).fill('公司：新的销售公司\n岗位：销售顾问\n月薪：18k');await page.getByRole('button',{name:'合并当前草稿…',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'确认合并字段差异'})).toContainText('固定月薪');await expect(page.getByLabel('公司显示名',{exact:true})).not.toHaveValue('新的销售公司');await page.getByRole('button',{name:'取消合并',exact:true}).click();
 await page.getByRole('button',{name:'合并当前草稿…',exact:true}).click();await page.getByRole('button',{name:'确认合并这些字段',exact:true}).click();await expect(page.getByLabel('公司显示名',{exact:true})).toHaveValue('新的销售公司');await expect(page.getByTestId('forge-cost')).toHaveText('—');
 await page.getByRole('button',{name:'确认已填写 / 提取的字段',exact:true}).click();await page.getByRole('button',{name:'确认推荐玩法',exact:true}).click();await page.getByLabel('启用一项已确认条款',{exact:true}).selectOption('');
 await expect(page.getByLabel('玩法类型',{exact:true})).toHaveValue('T06');await page.getByLabel('具体岗位名称',{exact:true}).fill('算法工程师');await expect(page.getByLabel('玩法类型',{exact:true})).toHaveValue('');await expect(page.getByText('岗位条件已变化，原类型',{exact:false})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:/^做我的卡|^录入我的 Offer/}).click();await expect(page.getByLabel('具体岗位名称',{exact:true})).toHaveValue('算法工程师');await expect(page.getByLabel('固定月薪',{exact:true})).toHaveValue('18000');await expect(page.getByLabel('玩法类型',{exact:true})).toHaveValue('');
});

for(const width of [390,320])test(`Q11/Q14: ${width}px local creation uses real preferences, readable source rows and actionable incomplete values`,async({page},testInfo)=>{
 await page.setViewportSize({width,height:844});const observed=await openForge(page);await page.getByRole('button',{name:'填入示例',exact:true}).click();
 await page.getByLabel('公司显示名',{exact:true}).fill('<img src=x onerror=alert(1)>公司');await page.getByLabel('角色口吻',{exact:true}).selectOption('calm');await page.getByLabel('本地立绘',{exact:true}).selectOption('formal');await expect(page.locator('.forge-card-stage [data-paper-profession]')).toHaveAttribute('data-paper-profession','public');await page.getByLabel('本地立绘',{exact:true}).selectOption('casual');await expect(page.locator('.forge-card-stage [data-paper-profession]')).toHaveAttribute('data-paper-profession','algorithm');
 await page.getByRole('button',{name:'查看依据',exact:false}).click();await expect(page.getByRole('region',{name:'生成依据',exact:true})).toBeVisible();await expect(page.locator('[data-contribution]')).toHaveCount(6);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);expect(await page.locator('[data-field-state=monthly_fixed_cny]').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(13);await page.screenshot({path:testInfo.outputPath(`forge-${width}-receipt.png`),fullPage:true});
 await confirmSave(page);expect((await storedOffers(page))[0].persona?.preferences).toMatchObject({tone:'calm',appearance:'casual'});await expect(page.getByRole('button',{name:'生成个性插画',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'自动识别（逐项确认）',exact:true})).toHaveCount(0);
 expect(observed.requests).toEqual([]);expect(observed.errors).toEqual([]);
});
