import StarterDeckPicker from './components/StarterDeckPicker';
import {getStarterDecks} from './game/starterDecks';
import SceneAnchor from './scene/SceneAnchor';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import HomeStage from './scene/HomeStage';
import {useSceneBridge} from './motion/useSceneBridge';
import {useInterfaceMotion} from './motion/useInterfaceMotion';
import {usePaperFeedback} from './motion/usePaperFeedback';
import {experimentFlags,type ExperimentFlags} from './game/experiments/features';
import type {ExperimentStart} from './pages/ExperimentHub';
const ExperimentHub=lazy(()=>import('./pages/ExperimentHub'));
const experimentNames:Record<keyof ExperimentFlags,string>={tempo:'先后手节奏实验',challenges:'固定残局挑战',series:'三局两胜',boss:'特殊 Boss 关卡',achievements:'操作成就与纸贴纸'};
import {useMotionPreferences} from './motion/useMotionPreferences';
import {useProfileDraft} from './components/useProfileDraft';
import ShareDialog from './components/ShareDialog';
import MigrationDialog from './components/MigrationDialog';
import {invitationCode,type InvitationPreview} from './game/invitation';
import {BOT_DIFFICULTIES} from './game/ai/config';
import type {BotDifficulty,SetupMode} from './game/ai/types';
import {rules,CARDS} from './game/catalog';
import {defaultLoadout,exampleOffers} from './game/offers';
import {showcaseCatalog} from './game/showcase';
import type {Command,Loadout,MatchView,OfferDefinition} from './game/types';
import {ApiError,api,session,socket,sendCommand,isStaticMode,currentAccount,logoutAccount,accountApi,getLocalReplay,isCloudRoom,getInvitationPreview,diagnosticLog,sanitizedErrorReport,type Account,type GameSocket,type Profile,type Room,type RoomResponse} from './api';
import {Icon,Art,OfferCard,CommonCard,Modal,Badge} from './ui';
const LoadoutPage=lazy(()=>import('./pages/Loadout'));
const CreateOffer=lazy(()=>import('./pages/CreateOffer'));
const Battle=lazy(()=>import('./pages/Battle'));
import TutorialHub,{readTutorialProgress,progressKey} from './pages/TutorialHub';
import RecoveryScreen from './components/RecoveryScreen';
import AccountPanel from './components/AccountPanel';
const Collection=lazy(()=>import('./pages/Collection'));
const MatchHistory=lazy(()=>import('./pages/MatchHistory'));
import './styles/account.css';
import {MusicDirector,chooseMusic,musicTitles} from './audio';
import {SoundEffects} from './sound-effects';
import {enterBattleFullscreen,exitBattleFullscreen} from './fullscreen';
import {invitationUrl} from './deployment';
type Page='home'|'loadout'|'create'|'collection'|'battle'|'tutorial'|'recovering'|'history'|'experiments';
const tutorial=[{title:'每一小时，都要花在刀刃上。',icon:'clock',body:'从 30 点心态开始。每轮可用时间从 1 小时增加到 8 小时。角色上桌需要时间，通常要到你的下个回合才能开怼。把对手心态打到 0 就获胜。',tip:'点击手牌出牌，再点击发光的合法目标。'}, {title:'另一份 Offer，也能当筹码。',icon:'mail',body:'每局可以谈薪一次：永久放弃一份从未上桌的 Offer，让另一份立刻低费上桌。筹码原始耗时 2–3 / 4–5 / 6–7 小时，对应优惠 1 / 2 / 3 小时。',tip:'打开「我的 Offer」旁的谈薪按钮，比较全部合法方案。'}, {title:'三十五岁，是一张牌。',icon:'shield',body:'场上的 Offer 在己方回合开始时从 22 → 27 → 31 → 35 岁成长。《三十五岁》可给 35 岁的一线 Offer 挂通知；持有者有一回合用《转管理》或《跳槽》应对。',tip:'收回保留年龄，清除本次强化、伤害和优化通知。'}, {title:'工资先亮，底牌后出。',icon:'cards',body:'聊年包、聊生活、聊以后，会改变全桌优势。反话盖下后保持隐藏，条件满足自动触发。可以先用小牌试出《合同写着呢》，再打关键拆台。',tip:'挡话只限制角色开怼，不拦截指向明确的行动牌和技能。'}, {title:'母校能撑腰，时机要选好。',icon:'crown',body:'第一学历技能每个己方回合可用。第二学历第 4 轮解锁，每局一次；两者共享每回合一次机会。选配队时先考虑两项技能的配合。',tip:'现在就去打一次练习局，计时关闭，可以慢慢读牌。'}];
export default function App(){
 const [recoveryRoomId,setRecoveryRoomId]=useState(()=>localStorage.getItem('offer-active-room'));
 const [recoveryError,setRecoveryError]=useState(false),[recoveryAttempt,setRecoveryAttempt]=useState(0);
 const recoveryGeneration=useRef(0),recoveryAbort=useRef<AbortController|null>(null);
 const [page,setPage]=useState<Page>(()=>recoveryRoomId?'recovering':'home'),[profile,setProfile]=useState<Profile|null>(null),[loadout,setLoadout]=useState<Loadout>(()=>{try{const l=JSON.parse(localStorage.getItem('offer-loadout')||'null');if(Array.isArray(l?.offers)&&Array.isArray(l.baseDeck)&&Array.isArray(l.flexDeck))return {...l,offers:l.offers.map((o:OfferDefinition)=>exampleOffers.find(x=>x.id===o.id)||o)}}catch{}return {...getStarterDecks(false)[0].loadout,name:'秋招挑战者'}}),[room,setRoom]=useState<Room|null>(null),[view,setView]=useState<MatchView|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[modal,setModal]=useState<'play'|'friends'|'settings'|'tutorial'|'account'|null>(null),[joinCode,setJoinCode]=useState(''),[strategy,setStrategy]=useState('aggressive'),[training,setTraining]=useState(true),[nickname,setNickname]=useState(localStorage.getItem('offer-name')||'秋招挑战者'),[tutorialStep,setTutorialStep]=useState(0),[filter,setFilter]=useState('offers'),[cardSearch,setCardSearch]=useState(''),[sound,setSound]=useState(localStorage.getItem('offer-sound')!=='0'),[volume,setVolume]=useState(Number(localStorage.getItem('offer-volume')||'0.35')),[connected,setConnected]=useState(true),[intro,setIntro]=useState(true);
 const motion=useMotionPreferences(),reduced=motion.reduced;
 const bridge=useSceneBridge(modal==='friends'?'friends':page),feedback=usePaperFeedback();useInterfaceMotion();
 const [experiments,setExperiments]=useState<ExperimentFlags>(()=>{try{return experimentFlags(JSON.parse(localStorage.getItem('offer-experiments-v22')||'{}'))}catch{return experimentFlags({})}});
 const setExperiment=(key:keyof ExperimentFlags,checked:boolean)=>{setExperiments(old=>{const next={...old,[key]:checked};localStorage.setItem('offer-experiments-v22',JSON.stringify(next));return next})};
 const [learnWhilePlaying,setLearnWhilePlaying]=useState(localStorage.getItem('offer-context-hints')!=='0'),[diagnosticPreview,setDiagnosticPreview]=useState(false);
 const lastDiagnosticMatch=useRef('');
 useEffect(()=>{diagnosticLog.record('app_open',{route:'home'});const capture=(event:ErrorEvent)=>{diagnosticLog.record('runtime_error',sanitizedErrorReport(event.error,{route:page}))};window.addEventListener('error',capture);return()=>window.removeEventListener('error',capture)},[]);
 useEffect(()=>{if(!view||view.phase!=='finished'||lastDiagnosticMatch.current===view.matchId)return;lastDiagnosticMatch.current=view.matchId;diagnosticLog.record('match_finished',{mode:room?.mode,round:view.round,result:view.result?.winnerId===null?'draw':view.result?.winnerId===view.selfId?'win':'lose'})},[view?.matchId,view?.phase]);
 const [difficulty,setDifficulty]=useState<BotDifficulty>(()=>(localStorage.getItem('offer-bot-difficulty') as BotDifficulty)||'normal'),[setupMode,setSetupMode]=useState<SetupMode>(()=>localStorage.getItem('offer-setup-mode')==='quick'?'quick':'full'),[autoFullscreen,setAutoFullscreen]=useState(localStorage.getItem('offer-auto-fullscreen')==='1');
 const [editingOffer,setEditingOffer]=useState<OfferDefinition|null>(null),[editIntent,setEditIntent]=useState<'revise'|'copy'>('revise');
 const profileDraft=useProfileDraft(profile,setProfile);
 const [showConflict,setShowConflict]=useState(false),[showMigration,setShowMigration]=useState(false),[shareInvitation,setShareInvitation]=useState(false),[publishLineup,setPublishLineup]=useState(false),[friendSeries,setFriendSeries]=useState(false),[friendSeriesAvailable,setFriendSeriesAvailable]=useState(false),[invitation,setInvitation]=useState<InvitationPreview|null>(null),[inviteLoading,setInviteLoading]=useState(false),[inviteError,setInviteError]=useState('');
 useEffect(()=>{if(profileDraft.conflict)setShowConflict(true)},[profileDraft.conflict]);
 useEffect(()=>{if(modal!=='friends')return;let active=true;setInvitation(null);setInviteError('');if(!invitationCode(joinCode)){setInviteLoading(false);return}setInviteLoading(true);const timer=setTimeout(()=>{void getInvitationPreview(joinCode).then(result=>{if(active)setInvitation(result)}).catch(()=>{if(active)setInviteError('暂时无法查看房间状态，请稍后重试。')}).finally(()=>{if(active)setInviteLoading(false)})},300);return()=>{active=false;clearTimeout(timer)}},[joinCode,modal]);
 const [account,setAccount]=useState<Account|null>(currentAccount),[authReason,setAuthReason]=useState<string|null>(null),[saveBusy,setSaveBusy]=useState(false),[savedMatch,setSavedMatch]=useState(''),[logoutConfirm,setLogoutConfirm]=useState(false);
 useEffect(()=>{if(modal!=='friends'||!experiments.series){setFriendSeriesAvailable(false);setFriendSeries(false);return}let live=true;const request=isStaticMode?accountApi:api;void request('/api/capabilities').then(c=>{if(live)setFriendSeriesAvailable(c.experimental?.bestOfThree===true)}).catch(()=>{if(live)setFriendSeriesAvailable(false)});return()=>{live=false}},[modal,experiments.series,account?.id]);
 const pendingAccountAction=useRef<(()=>void|Promise<void>)|null>(null),accountGeneration=useRef(0);
 function requireAccount(action:()=>void|Promise<void>,reason:string){if(!isStaticMode||currentAccount()){void action();return}pendingAccountAction.current=action;setAuthReason(reason)}
 function openFriends(){bridge.onBeforeNavigate('friends');diagnosticLog.record('invite_opened',{route:'invite'});setModal('friends')}
 async function accountReady(value:Account){setAccount(value);setNickname(value.nickname);localStorage.setItem('offer-name',value.nickname);setAuthReason(null);const action=pendingAccountAction.current;pendingAccountAction.current=null;if(action)await action()}
 async function signOut(){setBusy(true);accountGeneration.current++;try{await logoutAccount();setAccount(null);setSavedMatch('');setModal(null);setLogoutConfirm(false);if(roomRef.current&&isCloudRoom(roomRef.current.id))exit();else if(page==='history')setPage('home');notify('已退出账号，仍可作为游客练习')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function saveCurrentMatch(){
  const currentRoom=roomRef.current,currentView=view;if(!currentRoom||!currentView||currentView.phase!=='finished'||saveBusy)return;if(currentRoom.experiment){notify('实验对局保留在本机，不计入标准云端战报');return}
  requireAccount(async()=>{const owner=currentAccount();if(!owner)return;const generation=accountGeneration.current;setSaveBusy(true);try{const body=isCloudRoom(currentRoom.id)?{roomId:currentRoom.id}:{record:getLocalReplay(currentRoom.id)};await accountApi('/api/matches',body);if(generation===accountGeneration.current&&currentAccount()?.id===owner.id){setSavedMatch(currentView.matchId);feedback('saveReceipt','.result-banner',`cloud-save:${currentView.matchId}`);notify('已长期保存，可在“我的对局”中回放')}}catch(e){notify((e as Error).message)}finally{setSaveBusy(false)}},'这一局会保留在原处。注册或登录后，立即把完整对局保存到你的账号。');
 }
 const snapshotWatermark=useRef({matchId:'',version:-1});const retiredMatches=useRef(new Set<string>());const effectsRef=useRef<SoundEffects|null>(null);const musicRef=useRef<MusicDirector|null>(null);const [completedLessons,setCompletedLessons]=useState<string[]>(readTutorialProgress);const [musicVolume,setMusicVolume]=useState(Number(localStorage.getItem('offer-music-volume')||'0.26'));
 const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),roomRef=useRef(room),socketRef=useRef<GameSocket|null>(null);roomRef.current=room;
 const previousSeatCount=useRef(0);useEffect(()=>{if(room?.mode==='friend'&&room.players.length>previousSeatCount.current&&previousSeatCount.current>0)feedback('friendSeated','.room-seats',`seated:${room.id}:${room.players.length}`);previousSeatCount.current=room?.players.length??0},[room?.id,room?.players.length]);
 function notify(text:string){setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000)}
 function update(d:RoomResponse){
  if(d.room?.status==='waiting'&&!d.view&&roomRef.current?.id===d.room.id&&roomRef.current.status==='playing')return;
  if(d.view&&retiredMatches.current.has(d.view.matchId))return;
  if(d.room&&d.view?.matchId===snapshotWatermark.current.matchId&&roomRef.current?.id===d.room.id&&d.room.version<roomRef.current.version)return;
  if(d.view&&snapshotWatermark.current.matchId===d.view.matchId&&snapshotWatermark.current.version>d.view.version)return;
  if(d.view){if(snapshotWatermark.current.matchId&&snapshotWatermark.current.matchId!==d.view.matchId)retiredMatches.current.add(snapshotWatermark.current.matchId);snapshotWatermark.current={matchId:d.view.matchId,version:d.view.version}}
  else if(d.room?.status==='waiting'&&snapshotWatermark.current.matchId){retiredMatches.current.add(snapshotWatermark.current.matchId);snapshotWatermark.current={matchId:'',version:-1}}
  if(d.room){roomRef.current=d.room;setRoom(d.room)}if('view' in d)setView(d.view);if(d.room||d.view)setPage('battle');
 }

 useEffect(()=>{
  const generation=++recoveryGeneration.current,controller=new AbortController();let disposed=false;
  recoveryAbort.current=controller;
  const current=()=>!disposed&&generation===recoveryGeneration.current&&!controller.signal.aborted;
  const forget=()=>{if(localStorage.getItem('offer-active-room')===recoveryRoomId)localStorage.removeItem('offer-active-room');setRecoveryRoomId(null);setPage('home')};
  if(recoveryRoomId)setRecoveryError(false);
  void (async()=>{
   try{
    const p=await session();if(!current())return;setProfile(p);
    if(!recoveryRoomId)return;
    const data=await api<RoomResponse>(`/api/rooms/${encodeURIComponent(recoveryRoomId)}`,undefined,'GET',{signal:controller.signal});if(!current())return;
    if(data.room.status==='finished'&&data.room.series?.status!=='between'){forget();return}
    update(data);setRecoveryRoomId(null);
   }catch(e){if(!current())return;if(recoveryRoomId&&e instanceof ApiError&&e.status===404){forget();return}if(recoveryRoomId)setRecoveryError(true);else notify(`服务连接失败：${(e as Error).message}`)}
  })();
  return()=>{disposed=true;controller.abort();if(recoveryAbort.current===controller)recoveryAbort.current=null};
 },[recoveryRoomId,recoveryAttempt]);
 useEffect(()=>{localStorage.setItem('offer-loadout',JSON.stringify(loadout))},[loadout]);
 useEffect(()=>{if(!room?.id)return;localStorage.setItem('offer-active-room',room.id);let stopped=false,retry:ReturnType<typeof setTimeout>;const connect=()=>{if(stopped)return;let ws:GameSocket;try{ws=socket(room.id)}catch(e){setConnected(false);notify((e as Error).message);return}socketRef.current=ws;ws.onopen=()=>setConnected(true);ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='state'&&roomRef.current?.id===room.id)update(d);if(d.type==='error')notify(d.message||'房间连接错误')}catch{}};ws.onclose=()=>{setConnected(false);if(!stopped)retry=setTimeout(connect,1200)}};connect();return()=>{stopped=true;clearTimeout(retry);socketRef.current?.close()}},[room?.id,account?.id]);
 useEffect(()=>{
  if(!effectsRef.current)effectsRef.current=new SoundEffects((level,duration)=>musicRef.current?.duck(level,duration));
  effectsRef.current.set(sound,volume);
  if(view)effectsRef.current.consume(view.matchId,view.visualCues||[],view.selfId);else effectsRef.current.reset();
 },[view?.matchId,view?.version,sound,volume]);
 useEffect(()=>()=>effectsRef.current?.dispose(),[]);
 const musicScene=page==='battle'&&room?.tutorial?.completed?'victory':chooseMusic(page,view,!!room?.tutorial);
 useEffect(()=>{if(!musicRef.current)musicRef.current=new MusicDirector();musicRef.current.set(musicScene,sound,musicVolume)},[musicScene,sound,musicVolume]);
 useEffect(()=>()=>musicRef.current?.dispose(),[]);
 const unlockAudio=()=>musicRef.current?.unlock();
 useEffect(()=>{if(room?.tutorial?.completed)setCompletedLessons(old=>{const id=room.tutorial!.lessonId;if(old.includes(id))return old;const next=[...old,id];localStorage.setItem(progressKey,JSON.stringify(next));return next})},[room?.tutorial?.lessonId,room?.tutorial?.completed]);
 useEffect(()=>{let identity=currentAccount()?.id;const sync=()=>{const next=currentAccount();if(identity!==next?.id){identity=next?.id;accountGeneration.current++;setSavedMatch('')}setAccount(next);if(!next){setPage(current=>current==='history'?'home':current);if(roomRef.current&&isCloudRoom(roomRef.current.id))exit()}};window.addEventListener('offer-account-change',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('offer-account-change',sync);window.removeEventListener('storage',sync)}},[]);
 const offers=[...exampleOffers,...(profile?.offers||[]).filter(o=>!exampleOffers.some(x=>x.id===o.id))];
 async function start(mode:'bot'|'friend'){if(mode==='friend'&&isStaticMode&&!currentAccount()){requireAccount(()=>start(mode),'登录后即可创建好友房，当前配队会保留。');return}bridge.onBeforeNavigate('battle');if(mode==='bot'&&autoFullscreen)void enterBattleFullscreen();setBusy(true);try{await session();const data=await api<RoomResponse>('/api/rooms',{mode,strategy,difficulty,setupMode,training,...(experiments.achievements?{achievementsEnabled:true}:{}),...(mode==='friend'?{publishLineup,...(experiments.series&&friendSeries&&friendSeriesAvailable?{experiment:{kind:'series',enabled:true}}:{})}:{}),loadout:{...loadout,name:nickname}});update(data);diagnosticLog.record('match_started',{mode,difficulty});setModal(null);setIntro(false)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function startExperiment(request:ExperimentStart){if(autoFullscreen)void enterBattleFullscreen();setBusy(true);try{await session();update(await api('/api/rooms',{mode:'bot',training:true,difficulty,strategy,setupMode:'full',loadout:{...loadout,name:nickname},achievementsEnabled:experiments.achievements,experiment:{...request,enabled:true}}));setModal(null)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function startPractice(id:string){if(autoFullscreen)void enterBattleFullscreen();setBusy(true);try{await session();update(await api('/api/rooms',{mode:'bot',training:true,practiceScenario:id,loadout:{...loadout,name:nickname}}));setModal(null)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function startLesson(lessonId:string){if(autoFullscreen)void enterBattleFullscreen();setBusy(true);try{await session();update(await api('/api/rooms',{mode:'bot',training:true,lessonId,loadout:{...loadout,name:nickname}}));setModal(null);setIntro(false)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function tutorialExit(){exit();setPage('tutorial')}
 async function join(){const code=invitationCode(joinCode);if(!code){notify('请输入六位房间码或完整邀请链接');return}if(isStaticMode&&!currentAccount()){requireAccount(join,'登录后即可加入这张牌桌，朋友的房间码会保留。');return}setBusy(true);try{await session();update(await api('/api/rooms/join',{code}));setModal(null);if(isStaticMode)history.replaceState({},'',location.pathname)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function send(command:Command){
  if(!room||!view||busy)return;setBusy(true);
  try{update(await sendCommand(room,view,command))}
  catch(e){
   let failure=e;
   try{
    const fresh=await api<RoomResponse>(`/api/rooms/${room.id}`);update(fresh);
    const own=fresh.view?.players.find(p=>p.id===fresh.view!.selfId);
    const sameSetup=fresh.view?.matchId===view.matchId&&own&&((command.type==='SELECT_FLEX'&&fresh.view.phase==='flex'&&!own.flexReady)||(command.type==='MULLIGAN'&&fresh.view.phase==='mulligan'&&!own.mulliganReady));
    if(e instanceof ApiError&&e.code==='STALE_VERSION'&&sameSetup&&fresh.view){update(await sendCommand(fresh.room,fresh.view,command));return}
   }catch(retryError){failure=retryError}
   notify((failure as Error).message);
  }finally{setBusy(false)}
 }

 function exit(){void exitBattleFullscreen();recoveryGeneration.current++;recoveryAbort.current?.abort();setRecoveryRoomId(null);roomRef.current=null;setPage('home');setRoom(null);setView(null);localStorage.removeItem('offer-active-room')}
 const nav=(p:Page)=>{bridge.onBeforeNavigate(p);setPage(p);if(p==='create')setEditingOffer(null);history.pushState({offerPage:p},'',location.pathname+location.search+'#'+p);window.scrollTo({top:0})};
 useEffect(()=>{const back=(event:PopStateEvent)=>{const next=event.state?.offerPage;if(['home','collection','create','loadout','tutorial','history','experiments'].includes(next)&&!roomRef.current)setPage(next);else if(!roomRef.current)setPage('home')};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[]);
 const accountPanel=authReason!==null?<AccountPanel reason={authReason} onClose={()=>{setAuthReason(null);pendingAccountAction.current=null;setAccount(currentAccount())}} onAuthenticated={value=>void accountReady(value)}/>:null;
 if(page==='recovering')return <><RecoveryScreen failed={recoveryError} onRetry={()=>setRecoveryAttempt(attempt=>attempt+1)} onLogin={isStaticMode&&recoveryRoomId&&isCloudRoom(recoveryRoomId)&&!account?()=>requireAccount(()=>setRecoveryAttempt(attempt=>attempt+1),'登录原账号后，继续恢复已保留的好友房间。'):undefined} onExit={exit}/>{accountPanel}</>;
 return <div className={`app ${page==='battle'?'in-battle':''}`} onPointerDown={unlockAudio}>
 {page!=='battle'&&page!=='home'&&<header className="site-header"><button className="brand" onClick={()=>nav('home')} aria-label="返回首页"><span className="brand-emblem"><Icon name="sword" size={27}/></span><span>秋招斗兽棋<small>OFFER BATTLE</small></span></button><nav>{([['home','会客厅'],['collection','我的卡册'],['loadout','双学历配队']] as const).map(([p,label])=><button key={p} className={page===p?'active':''} onClick={()=>nav(p)}>{label}</button>)}{isStaticMode&&account&&<button className={page==='history'?'active':''} onClick={()=>nav('history')}>我的对局</button>}</nav><div className="header-right"><span className="season-label">秋招赛季 <i>·</i> S01</span><button className="icon-btn" aria-label="设置" onClick={()=>setModal('settings')}><Icon name="settings"/></button>{isStaticMode&&<button className="text-btn account-entry" onClick={()=>account?setModal('account'):requireAccount(()=>{},'登录后和朋友开打，也能长期保存完整对局。')}>{account?`账号 · ${account.username}`:'游客 · 登录 / 注册'}</button>}<button className="player-chip" onClick={()=>setModal('settings')}><span>聘</span>{nickname}</button></div></header>}
 {page==='home'&&<HomeStage accountLabel={account?`你好，${account.nickname}`:'游客 · 登录 / 注册'} onAccount={()=>account?setModal('account'):requireAccount(()=>{},'登录后和朋友开打，也能长期保存对局。')} sound={sound} onToggleSound={()=>{setSound(!sound);localStorage.setItem('offer-sound',String(Number(!sound)));unlockAudio()}} onSettings={()=>setModal('settings')} invited={!!new URLSearchParams(location.search).get('room')} onExperiments={Object.values(experiments).some(Boolean)?()=>nav('experiments'):undefined} onAction={action=>{if(action==='play')setModal('play');else if(action==='friends')openFriends();else if(action==='history'){if(account)nav('history');else requireAccount(()=>nav('history'),'登录后查看长期保存的对局。')}else nav(action)}}/>}
 <Suspense fallback={<div className="route-loading" role="status">正在展开这一页…</div>}>
 {page==='history'&&account&&<MatchHistory key={account.id} account={account} onPlay={()=>setModal('play')} notify={notify}/>}
 {page==='tutorial'&&<TutorialHub completed={completedLessons} busy={busy} onStart={id=>void startLesson(id)} onPractice={()=>setModal('play')}/>}
 {page==='loadout'&&<LoadoutPage value={loadout} onChange={l=>{setLoadout(l);profileDraft.save({loadout:l})}} offers={offers} onBattle={()=>setModal('play')} notify={notify}/>}
 {page==='experiments'&&<ExperimentHub flags={experiments} profile={profile} busy={busy} onStart={request=>void startExperiment(request)} onSettings={()=>setModal('settings')}/>}
 {page==='create'&&<CreateOffer key={`${editingOffer?.id??'new'}:${editIntent}`} editingOffer={editingOffer} initialIntent={editIntent} onSaved={o=>{diagnosticLog.record('offer_saved',{route:'create'});setProfile(p=>p?{...p,offers:[...(p.offers||[]).filter(x=>x.id!==o.id),o]}:p);void api<Profile>('/api/profile').then(setProfile).catch(()=>notify('卡牌已保存，档案刷新失败，请稍后重试'))}} onBuild={()=>nav('loadout')} notify={notify}/>}
 {page==='collection'&&<Collection offers={offers} profile={profile} loadout={loadout} onProfile={setProfile} onLoadout={l=>{setLoadout(l);profileDraft.save({loadout:l})}} onCreate={()=>nav('create')} onEdit={(offer,intent)=>{setEditingOffer(offer);setEditIntent(intent);setPage('create')}} notify={notify}/>}
 {page==='battle'&&room&&view&&<Battle key={view.matchId} accountRequired={isStaticMode} signedIn={!!account} onSaveMatch={saveCurrentMatch} saveBusy={saveBusy} savedMatch={savedMatch===view.matchId} onSaveReport={download=>requireAccount(download,'登录后才能保存完整 JSON 战报。这局会留在原处，登录后继续导出。')} onSettings={()=>setModal('settings')} onTutorialRestart={()=>void startLesson(room.tutorial!.lessonId)} onTutorialExit={tutorialExit} onTutorialNext={()=>room.tutorial?.nextLessonId?void startLesson(room.tutorial.nextLessonId):(tutorialExit(),setModal('play'))} room={room} view={view} send={send} busy={busy} onExit={exit} onEditLoadout={()=>{exit();nav('loadout')}} onFriends={()=>{exit();openFriends()}} onRematch={async(flexDeck)=>{if(autoFullscreen)void enterBattleFullscreen();setBusy(true);try{update(await api(`/api/rooms/${room.id}/rematch`,flexDeck?{flexDeck}:{}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}} notify={notify}/>}
 {page==='battle'&&room&&!view&&<div className="room-lobby page"><span className="eyebrow">THE TABLE IS READY</span><h1>桌已摆好，<em>等你入席。</em></h1><div className="room-code"><span>好友房间码</span><strong>{room.code}</strong><button className="btn subtle" onClick={()=>navigator.clipboard.writeText(invitationUrl(room.code,location.origin)).then(()=>{feedback('invitationSent','.room-code',`invite-copy:${room.code}:${Date.now()}`);notify('邀请链接已复制')}).catch(()=>notify(`房间码：${room.code}`))}>复制邀请链接<Icon name="mail"/></button><button className="btn subtle" onClick={()=>setShareInvitation(true)}>保存邀请图<Icon name="download"/></button></div><div className="room-seats">{[0,1].map(i=><div className="room-seat" key={i}><Icon name="users" size={34}/><h3>{room.players[i]?.name||'等待朋友加入'}</h3><Badge>{room.players[i]?.ready?'已准备':room.players[i]?'配队准备中':'空位'}</Badge></div>)}</div><p>双方准备后，公开三张 Offer 并选择应对牌。</p><div className="modal-actions"><button className="btn subtle" onClick={exit}>返回会客厅</button><button className="btn gold" disabled={busy} onClick={async()=>{if(autoFullscreen)void enterBattleFullscreen();setBusy(true);try{update(await api(`/api/rooms/${room.id}/ready`,{ready:true,loadout:{...loadout,name:nickname}}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>准备好了<Icon name="check"/></button></div></div>}
 {page==='battle'&&!connected&&<div className="connection-status">连接暂时中断，正在自动重连…</div>}
 </Suspense>
 {modal==='play'&&<Modal title="这一次，准备怎么赢？" onClose={()=>setModal(null)}><div className="play-mode-heading"><Icon name="sword" size={38}/><div><h3>单人练习</h3><p>选择难度和打法，带上当前阵容开桌。</p></div></div><StarterDeckPicker compact current={loadout} unlocked={localStorage.getItem('jlu-unlocked')==='1'} onApply={(l,title)=>{setLoadout(l);profileDraft.save({loadout:l});notify(`已应用「${title}」`)}}/><fieldset className="difficulty-options"><legend>对手难度</legend>{BOT_DIFFICULTIES.map(d=><label className={difficulty===d.id?'active':''} key={d.id}><input type="radio" name="difficulty" value={d.id} checked={difficulty===d.id} onChange={()=>{setDifficulty(d.id);localStorage.setItem('offer-bot-difficulty',d.id)}}/><strong>{d.label}</strong><small>{d.description}</small></label>)}</fieldset><label className="field">开局准备<select aria-label="开局准备" value={setupMode} onChange={e=>{setSetupMode(e.target.value as SetupMode);localStorage.setItem('offer-setup-mode',e.target.value)}}><option value="full">完整开局 · 选应对牌和换牌</option><option value="quick">快速开局 · 自动应对牌，保留起手</option></select></label><div className="strategy-options">{[['aggressive','抢节奏','尽早上桌，主动压低心态。'],['control','拆台控场','保留解牌，等你露出破绽。'],['growth','长期养成','稳定守岗，打到后期兑现。']].map(([id,t,d])=><button key={id} className={strategy===id?'active':''} onClick={()=>setStrategy(id)}><strong>{t}</strong><span>{d}</span></button>)}</div><label className="confirmation"><input type="checkbox" checked={learnWhilePlaying} onChange={e=>{setLearnWhilePlaying(e.target.checked);localStorage.setItem('offer-context-hints',String(Number(e.target.checked)))}}/><span>边打边学：只在相关局面显示提示，可以随时关闭。</span></label><label className="confirmation"><input type="checkbox" checked={training} onChange={e=>setTraining(e.target.checked)}/><span>慢慢练习：关闭回合计时，可以随时读牌。</span></label><label className="confirmation"><input type="checkbox" checked={autoFullscreen} onChange={e=>{setAutoFullscreen(e.target.checked);localStorage.setItem('offer-auto-fullscreen',String(Number(e.target.checked)))}}/><span>开始时进入全屏（记住我的选择）</span></label><button className="btn gold full" disabled={busy||loadout.offers.length!==3||loadout.baseDeck.length!==12||loadout.flexDeck.length!==3} onClick={()=>start('bot')}>{busy?'正在摆好牌桌…':'就用这套，开始对局'}<Icon name="arrow"/></button><button className="text-btn center-btn" onClick={()=>{setModal(null);nav('tutorial')}}><Icon name="book" size={16}/>第一次玩？跟着前辈完成入职训练</button><button className="text-btn center-btn" onClick={()=>{setModal(null);nav('loadout')}}>先调整我的阵容</button></Modal>}
 {modal==='friends'&&<Modal title="把 Offer，摆到朋友面前。" onClose={()=>setModal(null)}><SceneAnchor kind="friends"/><p>朋友收到链接后，可以先查看房间状态；注册或登录后入座。</p><button className="btn gold full" disabled={busy} onClick={()=>start('friend')}><Icon name="users"/>创建好友房</button><label className="confirmation"><input type="checkbox" checked={publishLineup} onChange={e=>setPublishLineup(e.target.checked)}/><span>邀请预览中公开阵容类型和战斗数值（不包含岗位、公司、年包）</span></label>{experiments.series&&<label className="confirmation"><input type="checkbox" checked={friendSeries&&friendSeriesAvailable} disabled={!friendSeriesAvailable} onChange={e=>setFriendSeries(e.target.checked)}/><span>三局两胜 · 阵容锁定，局间只换应对牌{!friendSeriesAvailable?'（当前联机服务未开放此实验）':''}</span></label>}<div className="or-divider">或加入朋友的牌桌</div><label className="field">房间码或邀请链接<input maxLength={300} placeholder="六位房间码或完整邀请链接" value={joinCode} onChange={e=>{setJoinCode(e.target.value);setInvitation(null);setInviteLoading(!!invitationCode(e.target.value))}}/></label><button className="btn subtle full" disabled={busy||!invitationCode(joinCode)||inviteLoading||!!invitation&&invitation.status!=='waiting'} onClick={()=>void join()}>{inviteLoading?'正在查看房间…':isStaticMode&&!account?'登录后加入这张牌桌':'加入房间'}<Icon name="arrow"/></button>{inviteLoading&&<p role="status">正在查看房间…</p>}{inviteError&&<p role="alert">{inviteError}</p>}{invitation&&<section className="invitation-preview" aria-live="polite"><h3>{({waiting:'朋友的牌桌正在等你',full:'这张牌桌已经坐满',ended:'这场对局已经结束',expired:'这份邀请已过期','not-found':'没有找到这张牌桌'})[invitation.status]}</h3>{invitation.hostNickname&&<p>房主：{invitation.hostNickname}</p>}<p>{invitation.status==='waiting'?'加入后可以调整阵容，双方准备后才开始。':invitation.status==='full'?'可以请朋友再开一张牌桌。':'可以创建新房间，或回到会客厅练习。'}</p>{invitation.offers&&<div className="invitation-lineup">{invitation.offers.map((o,i)=><span key={i}>{rules.offer_templates.find(t=>t.id===o.templateId)?.name??'Offer'}<br/>{o.cost} 时 · {o.attack} / {o.health}</span>)}</div>}</section>}</Modal>}
 {modal==='settings'&&<Modal title="按你的习惯开打。" onClose={()=>setModal(null)}><label className="field">牌桌昵称<input value={nickname} maxLength={16} onChange={e=>{setNickname(e.target.value);localStorage.setItem('offer-name',e.target.value);profileDraft.save({nickname:e.target.value})}}/></label><div className={`save-status inline state-${profileDraft.state}`} role="status">{profileDraft.label}{profileDraft.state==='failed'&&<button onClick={profileDraft.retry}>重试保存</button>}{profileDraft.state==='conflict'&&<button onClick={()=>setShowConflict(true)}>选择版本</button>}</div><div className="settings-row"><div><h3>游戏声音</h3><p>原创配乐 · {musicTitles[musicScene]}</p></div><button className={`toggle ${sound?'on':''}`} aria-label="切换音效" onClick={()=>{setSound(!sound);localStorage.setItem('offer-sound',String(Number(!sound)));unlockAudio()}}><i/></button></div><label className="field">音效音量 <input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{setVolume(Number(e.target.value));localStorage.setItem('offer-volume',e.target.value)}}/></label><label className="field">背景音乐音量 <input type="range" min="0" max="1" step=".05" value={musicVolume} onChange={e=>{setMusicVolume(Number(e.target.value));localStorage.setItem('offer-music-volume',e.target.value)}}/></label><div className="settings-row"><div><h3>动态效果</h3><p>跟随系统，或按你的习惯选择</p></div><select aria-label="动态效果" value={motion.preference} onChange={e=>motion.setPreference(e.target.value as 'system'|'full'|'reduced')}><option value="system">跟随系统</option><option value="full">完整</option><option value="reduced">减少动态</option></select></div><div className="settings-row"><div><h3>首页环境动作</h3><p>人物待机与场景小动作，可随时暂停</p></div><button className={`toggle ${motion.ambientPaused?'':'on'}`} role="switch" aria-checked={!motion.ambientPaused} aria-label="首页环境动作" onClick={()=>motion.setAmbientPaused(!motion.ambientPaused)}><i/></button></div><button className="text-btn" onClick={()=>{setTutorialStep(0);setModal('tutorial')}}><Icon name="book"/>查看规则速查与进阶演练</button><details><summary>实验室 · 默认关闭</summary><p>实验玩法单独记录，开关不会改变标准对局规则。</p><div className="experiment-settings">{(Object.keys(experimentNames) as (keyof ExperimentFlags)[]).map(key=><label key={key}><input type="checkbox" checked={experiments[key]} onChange={e=>setExperiment(key,e.target.checked)}/>{experimentNames[key]}</label>)}</div><button className="btn subtle" onClick={()=>{setModal(null);nav('experiments')}}>进入实验室</button></details><details><summary>本机诊断与反馈</summary><p>仅记录页面、模式、版本和错误类型，不包含昵称、公司、薪资或手牌；不会自动上传。</p><button className="btn subtle" onClick={()=>setDiagnosticPreview(true)}>查看脱敏报告</button></details><p className="settings-version">游戏 2.2 公测版 · 造卡 2.1 · 对局规则 2.0</p><div className="settings-note"><Icon name="shield"/>配乐随局势自动变化。首次点击后开始播放；关闭声音和音量设置会保存在当前浏览器。</div></Modal>}
 {modal==='tutorial'&&<Modal title={tutorial[tutorialStep].title} onClose={()=>setModal(null)}><div className="tutorial-symbol"><Icon name={tutorial[tutorialStep].icon} size={55}/><span>{String(tutorialStep+1).padStart(2,'0')} / 05</span></div><p className="tutorial-body">{tutorial[tutorialStep].body}</p><div className="tutorial-tip"><Icon name="info"/>{tutorial[tutorialStep].tip}</div><details className="practice-list"><summary>实战演练 · 预置关键场景</summary>{showcaseCatalog.filter(s=>localStorage.getItem('jlu-unlocked')==='1'||s.id==='SC04'||s.id==='SC05').map(s=><button className="btn subtle full" key={s.id} disabled={busy} onClick={()=>startPractice(s.id)}>{s.title}<Icon name="arrow" size={14}/></button>)}</details><div className="tutorial-dots">{tutorial.map((_,i)=><button key={i} aria-label={`教程第${i+1}步`} className={i===tutorialStep?'active':''} onClick={()=>setTutorialStep(i)}/>)}</div><button className="btn gold full" onClick={()=>tutorialStep<4?setTutorialStep(tutorialStep+1):(setTraining(true),setModal('play'))}>{tutorialStep<4?'下一步':'学会了，去练一局'}<Icon name="arrow"/></button></Modal>}
 {modal==='account'&&account&&<Modal title="你的牌桌，有名有姓。" onClose={()=>{if(!busy){setModal(null);setLogoutConfirm(false)}}}><div className="account-status"><Icon name="shield"/><div><strong>{account.nickname}</strong><br/><span>@{account.username}</span></div></div><p>好友联机与长期对局保存在这个账号下。恢复码只在注册或恢复账号时显示，请妥善保管。</p><div className="account-menu"><button className="btn gold" onClick={()=>{setModal(null);nav('history')}}>我的对局<Icon name="replay"/></button><button className="btn subtle" onClick={()=>{setModal(null);setShowMigration(true)}}>迁移本机卡册</button><button className="btn subtle" onClick={()=>setLogoutConfirm(true)}>退出账号</button></div>{logoutConfirm&&<div className="account-logout-confirm"><p>{room&&isCloudRoom(room.id)?'退出会断开当前好友牌桌。之后登录原账号可尝试恢复座位；对局计时仍继续。':'退出后回到游客模式。已长期保存的对局仍留在账号中，下次登录可查看。'}</p><div className="modal-actions"><button className="btn subtle" disabled={busy} onClick={()=>setLogoutConfirm(false)}>继续使用</button><button className="btn gold" disabled={busy} onClick={()=>void signOut()}>{busy?'正在退出…':'确认退出账号'}</button></div></div>}</Modal>}
 {showConflict&&profileDraft.conflict&&<Modal title="资料有新版本，保留哪一份？" onClose={()=>setShowConflict(false)}><p>另一个页面已保存修改。当前草稿保存在本机，不会自动覆盖新版本。</p><div className="profile-conflict-comparison"><div><strong>当前本机草稿</strong><p>{nickname}</p><ul>{loadout.offers.map(o=><li key={o.id}>{o.name}</li>)}</ul></div><div><strong>已保存的新版本</strong><p>{profileDraft.conflict.nickname}</p><ul>{profileDraft.conflict.loadout?.offers.map(o=><li key={o.id}>{o.name}</li>)}</ul></div></div><div className="modal-actions"><button className="btn subtle" onClick={()=>{const p=profileDraft.resolve('remote');if(p){setNickname(p.nickname);localStorage.setItem('offer-name',p.nickname);setLoadout(p.loadout??defaultLoadout('p1',p.nickname,5))}setShowConflict(false)}}>使用已保存版本</button><button className="btn gold" onClick={()=>{profileDraft.resolve('local');setShowConflict(false)}}>用本机草稿覆盖</button></div></Modal>}
 {showMigration&&account&&<MigrationDialog onClose={()=>setShowMigration(false)} onComplete={()=>{diagnosticLog.record('migration_completed');notify('迁移已完成，本机原件保留')}}/>}
 {shareInvitation&&room&&<ShareDialog source={{loadout:{...loadout,name:nickname},roomCode:room.code}} onClose={()=>setShareInvitation(false)} notify={notify}/>}
 {diagnosticPreview&&<Modal title="脱敏报告预览" onClose={()=>setDiagnosticPreview(false)}><p>这是当前浏览器的开发诊断，不代表真实用户留存或传播率。可以检查后再下载。</p><pre className="diagnostic-preview">{JSON.stringify(diagnosticLog.export(),null,2)}</pre><button className="btn gold" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(diagnosticLog.export(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='offer-battle-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>下载这份报告<Icon name="download"/></button></Modal>}
 {accountPanel}
 {!modal&&page!=='battle'&&(page!=='home'||!['saved','local-only'].includes(profileDraft.state))&&<div className={`save-status state-${profileDraft.state}`} role="status">{profileDraft.label}{profileDraft.state==='failed'&&<button onClick={profileDraft.retry}>重试保存</button>}{profileDraft.state==='conflict'&&<button onClick={()=>setShowConflict(true)}>选择版本</button>}</div>}
 {toast&&<div className="toast" role="status"><Icon name="info" size={17}/>{toast}</div>}
 <InviteHandler onCode={code=>{setJoinCode(code);openFriends()}}/>
 </div>
}
function InviteHandler({onCode}:{onCode:(s:string)=>void}){const done=useRef(false);useEffect(()=>{if(done.current)return;done.current=true;const code=new URLSearchParams(location.search).get('room');if(code){onCode(code);if(!isStaticMode)history.replaceState({},'',location.pathname)}},[]);return null}
