import {useEffect,useRef,useState} from 'react';
import {rules,CARDS} from './game/catalog';
import {defaultLoadout,exampleOffers} from './game/offers';
import {showcaseCatalog} from './game/showcase';
import type {Command,Loadout,MatchView,OfferDefinition} from './game/types';
import {ApiError,api,session,socket,sendCommand,isStaticMode,currentAccount,logoutAccount,accountApi,getLocalReplay,isCloudRoom,type Account,type GameSocket,type Profile,type Room,type RoomResponse} from './api';
import {Icon,Art,OfferCard,CommonCard,Modal,Badge} from './ui';
import LoadoutPage from './pages/Loadout';
import CreateOffer from './pages/CreateOffer';
import Battle from './pages/Battle';
import TutorialHub,{readTutorialProgress,progressKey} from './pages/TutorialHub';
import RecoveryScreen from './components/RecoveryScreen';
import AccountPanel from './components/AccountPanel';
import MatchHistory from './pages/MatchHistory';
import './styles/account.css';
import {MusicDirector,chooseMusic,musicTitles} from './audio';
import {SoundEffects} from './sound-effects';
import {exportOffer,exportInvitation} from './share';
import {enterBattleFullscreen,exitBattleFullscreen} from './fullscreen';
import {invitationUrl} from './deployment';
type Page='home'|'loadout'|'create'|'collection'|'battle'|'tutorial'|'recovering'|'history';
const tutorial=[{title:'每一小时，都要花在刀刃上。',icon:'clock',body:'从 30 点心态开始。每轮可用时间从 1 小时增加到 8 小时。角色上桌需要时间，通常要到你的下个回合才能开怼。把对手心态打到 0 就获胜。',tip:'点击手牌出牌，再点击发光的合法目标。'}, {title:'另一份 Offer，也能当筹码。',icon:'mail',body:'每局可以谈薪一次：永久放弃一份从未上桌的 Offer，让另一份立刻低费上桌。筹码原始耗时 2–3 / 4–5 / 6–7 小时，对应优惠 1 / 2 / 3 小时。',tip:'打开「我的 Offer」旁的谈薪按钮，比较全部合法方案。'}, {title:'三十五岁，是一张牌。',icon:'shield',body:'场上的 Offer 在己方回合开始时从 22 → 27 → 31 → 35 岁成长。《三十五岁》可给 35 岁的一线 Offer 挂通知；持有者有一回合用《转管理》或《跳槽》应对。',tip:'收回保留年龄，清除本次强化、伤害和优化通知。'}, {title:'工资先亮，底牌后出。',icon:'cards',body:'聊年包、聊生活、聊以后，会改变全桌优势。反话盖下后保持隐藏，条件满足自动触发。可以先用小牌试出《合同写着呢》，再打关键拆台。',tip:'挡话只限制角色开怼，不拦截指向明确的行动牌和技能。'}, {title:'母校能撑腰，时机要选好。',icon:'crown',body:'第一学历技能每个己方回合可用。第二学历第 4 轮解锁，每局一次；两者共享每回合一次机会。选配队时先考虑两项技能的配合。',tip:'现在就去打一次练习局，计时关闭，可以慢慢读牌。'}];
export default function App(){
 const [recoveryRoomId,setRecoveryRoomId]=useState(()=>localStorage.getItem('offer-active-room'));
 const [recoveryError,setRecoveryError]=useState(false),[recoveryAttempt,setRecoveryAttempt]=useState(0);
 const recoveryGeneration=useRef(0),recoveryAbort=useRef<AbortController|null>(null);
 const [page,setPage]=useState<Page>(()=>recoveryRoomId?'recovering':'home'),[profile,setProfile]=useState<Profile|null>(null),[loadout,setLoadout]=useState<Loadout>(()=>{try{const l=JSON.parse(localStorage.getItem('offer-loadout')||'null');if(l?.offers?.length&&Array.isArray(l.baseDeck)&&Array.isArray(l.flexDeck))return {...l,offers:l.offers.map((o:OfferDefinition)=>exampleOffers.find(x=>x.id===o.id)||o)}}catch{}return defaultLoadout('p1','秋招挑战者',5)}),[room,setRoom]=useState<Room|null>(null),[view,setView]=useState<MatchView|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[modal,setModal]=useState<'play'|'friends'|'settings'|'tutorial'|'account'|null>(null),[joinCode,setJoinCode]=useState(''),[strategy,setStrategy]=useState('aggressive'),[training,setTraining]=useState(true),[nickname,setNickname]=useState(localStorage.getItem('offer-name')||'秋招挑战者'),[tutorialStep,setTutorialStep]=useState(0),[filter,setFilter]=useState('offers'),[cardSearch,setCardSearch]=useState(''),[sound,setSound]=useState(localStorage.getItem('offer-sound')!=='0'),[volume,setVolume]=useState(Number(localStorage.getItem('offer-volume')||'0.35')),[reduced,setReduced]=useState(localStorage.getItem('offer-reduced')==='1'),[connected,setConnected]=useState(true),[intro,setIntro]=useState(true);
 const [account,setAccount]=useState<Account|null>(currentAccount),[authReason,setAuthReason]=useState<string|null>(null),[saveBusy,setSaveBusy]=useState(false),[savedMatch,setSavedMatch]=useState(''),[logoutConfirm,setLogoutConfirm]=useState(false);
 const pendingAccountAction=useRef<(()=>void|Promise<void>)|null>(null),accountGeneration=useRef(0);
 function requireAccount(action:()=>void|Promise<void>,reason:string){if(!isStaticMode||currentAccount()){void action();return}pendingAccountAction.current=action;setAuthReason(reason)}
 function openFriends(){requireAccount(()=>setModal('friends'),'注册或登录后就能和朋友开打；房间邀请会为你保留。游客也可以直接玩人机和教程。')}
 async function accountReady(value:Account){setAccount(value);setNickname(value.nickname);localStorage.setItem('offer-name',value.nickname);setAuthReason(null);const action=pendingAccountAction.current;pendingAccountAction.current=null;if(action)await action()}
 async function signOut(){setBusy(true);accountGeneration.current++;try{await logoutAccount();setAccount(null);setSavedMatch('');setModal(null);setLogoutConfirm(false);if(roomRef.current&&isCloudRoom(roomRef.current.id))exit();else if(page==='history')setPage('home');notify('已退出账号，仍可作为游客练习')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function saveCurrentMatch(){
  const currentRoom=roomRef.current,currentView=view;if(!currentRoom||!currentView||currentView.phase!=='finished'||saveBusy)return;
  requireAccount(async()=>{const owner=currentAccount();if(!owner)return;const generation=accountGeneration.current;setSaveBusy(true);try{const body=isCloudRoom(currentRoom.id)?{roomId:currentRoom.id}:{record:getLocalReplay(currentRoom.id)};await accountApi('/api/matches',body);if(generation===accountGeneration.current&&currentAccount()?.id===owner.id){setSavedMatch(currentView.matchId);notify('已长期保存，可在“我的对局”中回放')}}catch(e){notify((e as Error).message)}finally{setSaveBusy(false)}},'这一局会保留在原处。注册或登录后，立即把完整对局保存到你的账号。');
 }
 const snapshotWatermark=useRef({matchId:'',version:-1});const retiredMatches=useRef(new Set<string>());const effectsRef=useRef<SoundEffects|null>(null);const musicRef=useRef<MusicDirector|null>(null);const [completedLessons,setCompletedLessons]=useState<string[]>(readTutorialProgress);const [musicVolume,setMusicVolume]=useState(Number(localStorage.getItem('offer-music-volume')||'0.26'));
 const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),roomRef=useRef(room),socketRef=useRef<GameSocket|null>(null),audioContext=useRef<AudioContext|null>(null);roomRef.current=room;
 function notify(text:string){setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000)}
 function update(d:RoomResponse){
  if(d.room?.status==='waiting'&&!d.view&&roomRef.current?.id===d.room.id&&roomRef.current.status==='playing')return;
  if(d.view&&retiredMatches.current.has(d.view.matchId))return;
  if(d.room&&d.view?.matchId===snapshotWatermark.current.matchId&&roomRef.current?.id===d.room.id&&d.room.version<roomRef.current.version)return;
  if(d.view&&snapshotWatermark.current.matchId===d.view.matchId&&snapshotWatermark.current.version>d.view.version)return;
  if(d.view){if(snapshotWatermark.current.matchId&&snapshotWatermark.current.matchId!==d.view.matchId)retiredMatches.current.add(snapshotWatermark.current.matchId);snapshotWatermark.current={matchId:d.view.matchId,version:d.view.version}}
  else if(d.room?.status==='waiting'&&snapshotWatermark.current.matchId){retiredMatches.current.add(snapshotWatermark.current.matchId);snapshotWatermark.current={matchId:'',version:-1}}
  if(d.room){roomRef.current=d.room;setRoom(d.room)}if('view' in d)setView(d.view);if(d.room||d.view)setPage('battle');
 }

 useEffect(()=>{
  const generation=++recoveryGeneration.current,controller=new AbortController();let disposed=false;
  recoveryAbort.current=controller;
  const current=()=>!disposed&&generation===recoveryGeneration.current&&!controller.signal.aborted;
  const forget=()=>{if(localStorage.getItem('offer-active-room')===recoveryRoomId)localStorage.removeItem('offer-active-room');setRecoveryRoomId(null);setPage('home')};
  if(recoveryRoomId)setRecoveryError(false);
  void (async()=>{
   try{
    const p=await session();if(!current())return;setProfile(p);
    if(!recoveryRoomId)return;
    const data=await api<RoomResponse>(`/api/rooms/${encodeURIComponent(recoveryRoomId)}`,undefined,'GET',{signal:controller.signal});if(!current())return;
    if(data.room.status==='finished'){forget();return}
    update(data);setRecoveryRoomId(null);
   }catch(e){if(!current())return;if(recoveryRoomId&&e instanceof ApiError&&e.status===404){forget();return}if(recoveryRoomId)setRecoveryError(true);else notify(`服务连接失败：${(e as Error).message}`)}
  })();
  return()=>{disposed=true;controller.abort();if(recoveryAbort.current===controller)recoveryAbort.current=null};
 },[recoveryRoomId,recoveryAttempt]);
 useEffect(()=>{localStorage.setItem('offer-loadout',JSON.stringify(loadout))},[loadout]);useEffect(()=>{document.documentElement.dataset.reduced=String(reduced);localStorage.setItem('offer-reduced',String(Number(reduced)))},[reduced]);
 useEffect(()=>{if(!room?.id)return;localStorage.setItem('offer-active-room',room.id);let stopped=false,retry:ReturnType<typeof setTimeout>;const connect=()=>{if(stopped)return;let ws:GameSocket;try{ws=socket(room.id)}catch(e){setConnected(false);notify((e as Error).message);return}socketRef.current=ws;ws.onopen=()=>setConnected(true);ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='state'&&roomRef.current?.id===room.id)update(d);if(d.type==='error')notify(d.message||'房间连接错误')}catch{}};ws.onclose=()=>{setConnected(false);if(!stopped)retry=setTimeout(connect,1200)}};connect();return()=>{stopped=true;clearTimeout(retry);socketRef.current?.close()}},[room?.id,account?.id]);
 useEffect(()=>{
  if(!effectsRef.current)effectsRef.current=new SoundEffects((level,duration)=>musicRef.current?.duck(level,duration));
  effectsRef.current.set(sound,volume);
  if(view)effectsRef.current.consume(view.matchId,view.visualCues||[],view.selfId);else effectsRef.current.reset();
 },[view?.matchId,view?.version,sound,volume]);
 useEffect(()=>()=>effectsRef.current?.dispose(),[]);
 const musicScene=page==='battle'&&room?.tutorial?.completed?'victory':chooseMusic(page,view,!!room?.tutorial);
 useEffect(()=>{if(!musicRef.current)musicRef.current=new MusicDirector();musicRef.current.set(musicScene,sound,musicVolume)},[musicScene,sound,musicVolume]);
 useEffect(()=>()=>musicRef.current?.dispose(),[]);
 const unlockAudio=()=>{if(!audioContext.current){try{audioContext.current=new AudioContext()}catch{}}if(audioContext.current?.state==='suspended')void audioContext.current.resume();musicRef.current?.unlock()};
 useEffect(()=>{if(room?.tutorial?.completed)setCompletedLessons(old=>{const id=room.tutorial!.lessonId;if(old.includes(id))return old;const next=[...old,id];localStorage.setItem(progressKey,JSON.stringify(next));return next})},[room?.tutorial?.lessonId,room?.tutorial?.completed]);
 useEffect(()=>{let identity=currentAccount()?.id;const sync=()=>{const next=currentAccount();if(identity!==next?.id){identity=next?.id;accountGeneration.current++;setSavedMatch('')}setAccount(next);if(!next){setPage(current=>current==='history'?'home':current);if(roomRef.current&&isCloudRoom(roomRef.current.id))exit()}};window.addEventListener('offer-account-change',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('offer-account-change',sync);window.removeEventListener('storage',sync)}},[]);
 const offers=[...exampleOffers,...(profile?.offers||[]).filter(o=>!exampleOffers.some(x=>x.id===o.id))];
 async function start(mode:'bot'|'friend'){if(mode==='friend'&&isStaticMode&&!currentAccount()){requireAccount(()=>start(mode),'登录后即可创建好友房，当前配队会保留。');return}if(mode==='bot')void enterBattleFullscreen();setBusy(true);try{await session();const data=await api<RoomResponse>('/api/rooms',{mode,strategy,training,skipSetup:mode==='bot',loadout:{...loadout,name:nickname}});update(data);setModal(null);setIntro(false)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function startPractice(id:string){void enterBattleFullscreen();setBusy(true);try{await session();update(await api('/api/rooms',{mode:'bot',training:true,practiceScenario:id,loadout:{...loadout,name:nickname}}));setModal(null)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function startLesson(lessonId:string){void enterBattleFullscreen();setBusy(true);try{await session();update(await api('/api/rooms',{mode:'bot',training:true,lessonId,loadout:{...loadout,name:nickname}}));setModal(null);setIntro(false)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function tutorialExit(){exit();setPage('tutorial')}
 async function join(){if(isStaticMode&&!currentAccount()){requireAccount(join,'登录后即可加入这张牌桌，朋友的房间码会保留。');return}setBusy(true);try{await session();update(await api('/api/rooms/join',{code:joinCode.trim().toUpperCase()}));setModal(null);if(isStaticMode)history.replaceState({},'',location.pathname)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function send(command:Command){
  if(!room||!view||busy)return;setBusy(true);
  try{update(await sendCommand(room,view,command))}
  catch(e){
   let failure=e;
   try{
    const fresh=await api<RoomResponse>(`/api/rooms/${room.id}`);update(fresh);
    const own=fresh.view?.players.find(p=>p.id===fresh.view!.selfId);
    const sameSetup=fresh.view?.matchId===view.matchId&&own&&((command.type==='SELECT_FLEX'&&fresh.view.phase==='flex'&&!own.flexReady)||(command.type==='MULLIGAN'&&fresh.view.phase==='mulligan'&&!own.mulliganReady));
    if(e instanceof ApiError&&e.code==='STALE_VERSION'&&sameSetup&&fresh.view){update(await sendCommand(fresh.room,fresh.view,command));return}
   }catch(retryError){failure=retryError}
   notify((failure as Error).message);
  }finally{setBusy(false)}
 }

 function exit(){void exitBattleFullscreen();recoveryGeneration.current++;recoveryAbort.current?.abort();setRecoveryRoomId(null);roomRef.current=null;setPage('home');setRoom(null);setView(null);localStorage.removeItem('offer-active-room')}
 const nav=(p:Page)=>{setPage(p);window.scrollTo({top:0})};
 const accountPanel=authReason!==null?<AccountPanel reason={authReason} onClose={()=>{setAuthReason(null);pendingAccountAction.current=null;setAccount(currentAccount())}} onAuthenticated={value=>void accountReady(value)}/>:null;
 if(page==='recovering')return <><RecoveryScreen failed={recoveryError} onRetry={()=>setRecoveryAttempt(attempt=>attempt+1)} onLogin={isStaticMode&&recoveryRoomId&&isCloudRoom(recoveryRoomId)&&!account?()=>requireAccount(()=>setRecoveryAttempt(attempt=>attempt+1),'登录原账号后，继续恢复已保留的好友房间。'):undefined} onExit={exit}/>{accountPanel}</>;
 return <div className={`app ${page==='battle'?'in-battle':''}`} onPointerDown={unlockAudio}>
 {page!=='battle'&&<header className="site-header"><button className="brand" onClick={()=>nav('home')} aria-label="返回首页"><span className="brand-emblem"><Icon name="sword" size={27}/></span><span>秋招斗兽棋<small>OFFER BATTLE</small></span></button><nav>{([['home','会客厅'],['collection','我的卡册'],['loadout','双学历配队']] as const).map(([p,label])=><button key={p} className={page===p?'active':''} onClick={()=>nav(p)}>{label}</button>)}{isStaticMode&&account&&<button className={page==='history'?'active':''} onClick={()=>nav('history')}>我的对局</button>}</nav><div className="header-right"><span className="season-label">秋招赛季 <i>·</i> S01</span><button className="icon-btn" aria-label="设置" onClick={()=>setModal('settings')}><Icon name="settings"/></button>{isStaticMode&&<button className="text-btn account-entry" onClick={()=>account?setModal('account'):requireAccount(()=>{},'登录后和朋友开打，也能长期保存完整对局。')}>{account?`账号 · ${account.username}`:'游客 · 登录 / 注册'}</button>}<button className="player-chip" onClick={()=>setModal('settings')}><span>聘</span>{nickname}</button></div></header>}
 {page==='home'&&<main className="home"><div className="home-backdrop"/><div className="home-grid"><section className="hero-copy"><div className="season-kicker"><span/><span>2026 秋招季 · 现在，轮到你出牌</span></div><h1>工资先亮，<br/><em>底牌后出。</em></h1><p className="home-description">把同学群里的 Offer 嘴仗，<br/>打成一场漂亮的翻身仗。</p><div className="home-actions"><button className="btn gold primary-cta" onClick={()=>setModal('play')}><Icon name="sword" size={22}/>先玩一局<Icon name="arrow" size={19}/></button><button className="btn glass" onClick={()=>nav('create')}><Icon name="plus" size={18}/>录入我的 Offer</button></div><div className="home-hint"><Icon name="shield" size={14}/>{isStaticMode?'游客直接开打':'免费本地试玩'}<span>·</span>无需模型密钥<span>·</span>一局 4–7 分钟</div><button className="friend-link" onClick={openFriends}><Icon name="users" size={17}/>和朋友约一场<Icon name="arrow" size={14}/></button>{isStaticMode&&<p className="account-home-note">{account?'已登录 · 好友对局与长期战报，随时开桌。':'游客可玩人机与教程；注册后解锁好友联机与长期对局保存。'}</p>}</section>
 <section className="hero-showcase" aria-label="示例 Offer 卡牌"><div className="showcase-orbit orbit-1"/><div className="showcase-orbit orbit-2"/><span className="floating-note note-top">这份 Offer，有点东西。</span><div className="showcase-card left"><OfferCard offer={exampleOffers[3]} onClick={()=>nav('collection')}/></div><div className="showcase-card right"><OfferCard offer={exampleOffers[1]} onClick={()=>nav('collection')}/></div><div className="showcase-card center"><OfferCard offer={exampleOffers[0]} onClick={()=>nav('collection')}/></div><span className="floating-note note-bottom"><Icon name="spark" size={15}/>年包挺能撑场面，场面呢？</span><div className="showcase-caption"><span>真实薪资编译</span><i>✦</i><span>原创职业角色</span><i>✦</i><span>胜负由你决定</span></div></section></div>
 <section className="home-bottom"><button className="feature-panel" onClick={()=>nav('create')}><span className="feature-number">01</span><Icon name="mail" size={25}/><div><h3>你的 Offer，你的角色</h3><p>年包定身材，岗位定打法。</p></div><Icon name="arrow" size={17}/></button><button className="feature-panel" onClick={()=>nav('loadout')}><span className="feature-number">02</span><Icon name="crown" size={25}/><div><h3>双学历，双重底气</h3><p>主技能打节奏，进修留绝招。</p></div><Icon name="arrow" size={17}/></button><button className="feature-panel" onClick={()=>nav('tutorial')}><span className="feature-number">03</span><Icon name="book" size={25}/><div><h3>跟着前辈，打会第一局</h3><p>五场实战，亲手学会每一招。</p></div><Icon name="arrow" size={17}/></button></section><footer className="home-footer"><span>一款关于职场嘴硬与策略的原创卡牌游戏</span><span>规则 v2.0.0 <i>·</i> {isStaticMode?'在线牌桌 · 游客免注册':'完整自托管版'}</span></footer></main>}
 {page==='history'&&account&&<MatchHistory key={account.id} account={account} onPlay={()=>setModal('play')} notify={notify}/>}
 {page==='tutorial'&&<TutorialHub completed={completedLessons} busy={busy} onStart={id=>void startLesson(id)} onPractice={()=>setModal('play')}/>}
 {page==='loadout'&&<LoadoutPage value={loadout} onChange={l=>{setLoadout(l);if(profile)void api('/api/profile',{loadout:l},'PATCH').catch(()=>{})}} offers={offers} onBattle={()=>setModal('play')} notify={notify}/>}
 {page==='create'&&<CreateOffer onSaved={o=>{setProfile(p=>p?{...p,offers:[...(p.offers||[]).filter(x=>x.id!==o.id),o]}:p)}} onBuild={()=>nav('loadout')} notify={notify}/>}
 {page==='collection'&&<div className="page collection-page"><div className="page-heading"><div><span className="eyebrow">THE OFFER COLLECTION</span><h1>每一张，都有<em>话要说。</em></h1><p>收藏你的职场角色，读懂对手的底牌。</p></div><button className="btn gold" onClick={()=>nav('create')}><Icon name="plus"/>录入新 Offer</button></div><div className="collection-toolbar"><div className="tabs">{[['offers',`Offer · ${offers.length}`],['support','助阵 · 6'],['action','行动 · 21'],['retort','反话 · 3']].map(([id,n])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{n}</button>)}</div><input className="search-input" placeholder="搜索卡牌…" value={cardSearch} onChange={e=>setCardSearch(e.target.value)}/></div>{filter==='offers'?<div className="card-grid">{offers.filter(o=>(o.name+o.company+o.role).includes(cardSearch)).map(o=><div className="collection-card" key={o.id}><OfferCard offer={o} onClick={()=>notify(`${o.role} · ${rules.offer_templates.find(t=>t.id===o.templateId)?.main_effect}`)}/><div className="collection-card-actions"><button className="text-btn" onClick={()=>{setLoadout(l=>l.offers.some(x=>x.id===o.id)?l:({...l,offers:[...l.offers.slice(0,2),o]}));nav('loadout')}}>加入阵容<Icon name="plus" size={12}/></button><button className="icon-btn" title="保存晒卡图" onClick={()=>exportOffer(o).catch(()=>notify('图片加载中，请稍后再试'))}><Icon name="download" size={16}/></button>{!o.id.startsWith('E')&&<button className="text-btn" onClick={async()=>{try{await api(`/api/offers/${o.id}`,undefined,'DELETE');setProfile(p=>p?{...p,offers:p.offers.filter(x=>x.id!==o.id)}:p);setLoadout(l=>({...l,offers:l.offers.filter(x=>x.id!==o.id)}));notify('已从个人收藏移除')}catch(e){notify((e as Error).message)}}}>移除</button>}</div></div>)}</div>:<div className="common-grid">{CARDS.filter(c=>c.type===filter&&(c.name+c.rules_text).includes(cardSearch)).map(c=><CommonCard key={c.id} id={c.id} onClick={()=>notify(c.rules_text)}/>)}</div>}</div>}
 {page==='battle'&&room&&view&&<Battle key={view.matchId} accountRequired={isStaticMode} signedIn={!!account} onSaveMatch={saveCurrentMatch} saveBusy={saveBusy} savedMatch={savedMatch===view.matchId} onSaveReport={download=>requireAccount(download,'登录后才能保存完整 JSON 战报。这局会留在原处，登录后继续导出。')} onSettings={()=>setModal('settings')} onTutorialRestart={()=>void startLesson(room.tutorial!.lessonId)} onTutorialExit={tutorialExit} onTutorialNext={()=>room.tutorial?.nextLessonId?void startLesson(room.tutorial.nextLessonId):(tutorialExit(),setModal('play'))} room={room} view={view} send={send} busy={busy} onExit={exit} onRematch={async()=>{void enterBattleFullscreen();setBusy(true);try{update(await api(`/api/rooms/${room.id}/rematch`,{}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}} notify={notify}/>}
 {page==='battle'&&room&&!view&&<div className="room-lobby page"><span className="eyebrow">THE TABLE IS READY</span><h1>桌已摆好，<em>等你入席。</em></h1><div className="room-code"><span>好友房间码</span><strong>{room.code}</strong><button className="btn subtle" onClick={()=>navigator.clipboard.writeText(invitationUrl(room.code,location.origin)).then(()=>notify('邀请链接已复制')).catch(()=>notify(`房间码：${room.code}`))}>复制邀请链接<Icon name="mail"/></button><button className="btn subtle" onClick={()=>exportInvitation({...loadout,name:nickname},room.code).catch(()=>notify('邀请图生成失败，请稍后重试'))}>保存邀请图<Icon name="download"/></button></div><div className="room-seats">{[0,1].map(i=><div className="room-seat" key={i}><Icon name="users" size={34}/><h3>{room.players[i]?.name||'等待朋友加入'}</h3><Badge>{room.players[i]?.ready?'已准备':room.players[i]?'配队准备中':'空位'}</Badge></div>)}</div><p>双方准备后，公开三张 Offer 并选择应对牌。</p><div className="modal-actions"><button className="btn subtle" onClick={exit}>返回会客厅</button><button className="btn gold" disabled={busy} onClick={async()=>{void enterBattleFullscreen();setBusy(true);try{update(await api(`/api/rooms/${room.id}/ready`,{ready:true,loadout:{...loadout,name:nickname}}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>准备好了<Icon name="check"/></button></div></div>}
 {page==='battle'&&!connected&&<div className="connection-status">连接暂时中断，正在自动重连…</div>}
 {modal==='play'&&<Modal title="这一次，准备怎么赢？" onClose={()=>setModal(null)}><div className="play-mode-heading"><Icon name="sword" size={38}/><div><h3>单人练习</h3><p>带上当前阵容，与三种风格的机器人交手。</p></div></div><div className="strategy-options">{[['aggressive','抢节奏','尽早上桌，主动压低心态。'],['control','拆台控场','保留解牌，等你露出破绽。'],['growth','长期养成','稳定守岗，打到后期兑现。']].map(([id,t,d])=><button key={id} className={strategy===id?'active':''} onClick={()=>setStrategy(id)}><strong>{t}</strong><span>{d}</span></button>)}</div><label className="confirmation"><input type="checkbox" checked={training} onChange={e=>setTraining(e.target.checked)}/><span>慢慢练习：关闭回合计时，可以随时读牌。</span></label><button className="btn gold full" disabled={busy||loadout.offers.length!==3||loadout.baseDeck.length!==12||loadout.flexDeck.length!==3} onClick={()=>start('bot')}>{busy?'正在摆好牌桌…':'就用这套，开始对局'}<Icon name="arrow"/></button><button className="text-btn center-btn" onClick={()=>{setModal(null);nav('tutorial')}}><Icon name="book" size={16}/>第一次玩？跟着前辈完成入职训练</button><button className="text-btn center-btn" onClick={()=>{setModal(null);nav('loadout')}}>先调整我的阵容</button></Modal>}
 {modal==='friends'&&<Modal title="把 Offer，摆到朋友面前。" onClose={()=>setModal(null)}><p>创建好友房，分享链接或六位房间码。双方准备后开始选牌。</p><button className="btn gold full" disabled={busy} onClick={()=>start('friend')}><Icon name="users"/>创建好友房</button><div className="or-divider">或加入朋友的牌桌</div><label className="field">房间码<input maxLength={8} placeholder="输入房间码" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())}/></label><button className="btn subtle full" disabled={busy||joinCode.trim().length<4} onClick={join}>加入房间<Icon name="arrow"/></button></Modal>}
 {modal==='settings'&&<Modal title="按你的习惯开打。" onClose={()=>setModal(null)}><label className="field">牌桌昵称<input value={nickname} maxLength={16} onChange={e=>{setNickname(e.target.value);localStorage.setItem('offer-name',e.target.value);void api('/api/profile',{nickname:e.target.value},'PATCH').catch(()=>{})}}/></label><div className="settings-row"><div><h3>游戏声音</h3><p>原创配乐 · {musicTitles[musicScene]}</p></div><button className={`toggle ${sound?'on':''}`} aria-label="切换音效" onClick={()=>{setSound(!sound);localStorage.setItem('offer-sound',String(Number(!sound)));unlockAudio()}}><i/></button></div><label className="field">音效音量 <input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{setVolume(Number(e.target.value));localStorage.setItem('offer-volume',e.target.value)}}/></label><label className="field">背景音乐音量 <input type="range" min="0" max="1" step=".05" value={musicVolume} onChange={e=>{setMusicVolume(Number(e.target.value));localStorage.setItem('offer-music-volume',e.target.value)}}/></label><div className="settings-row"><div><h3>减少动态效果</h3><p>保留数值变化，缩短卡牌演出</p></div><button className={`toggle ${reduced?'on':''}`} aria-label="减少动态效果" onClick={()=>setReduced(!reduced)}><i/></button></div><button className="text-btn" onClick={()=>{setTutorialStep(0);setModal('tutorial')}}><Icon name="book"/>查看规则速查与进阶演练</button><div className="settings-note"><Icon name="shield"/>配乐随局势自动变化。首次点击后开始播放；关闭声音和音量设置会保存在当前浏览器。</div></Modal>}
 {modal==='tutorial'&&<Modal title={tutorial[tutorialStep].title} onClose={()=>setModal(null)}><div className="tutorial-symbol"><Icon name={tutorial[tutorialStep].icon} size={55}/><span>{String(tutorialStep+1).padStart(2,'0')} / 05</span></div><p className="tutorial-body">{tutorial[tutorialStep].body}</p><div className="tutorial-tip"><Icon name="info"/>{tutorial[tutorialStep].tip}</div><details className="practice-list"><summary>实战演练 · 预置关键场景</summary>{showcaseCatalog.filter(s=>localStorage.getItem('jlu-unlocked')==='1'||s.id==='SC04'||s.id==='SC05').map(s=><button className="btn subtle full" key={s.id} disabled={busy} onClick={()=>startPractice(s.id)}>{s.title}<Icon name="arrow" size={14}/></button>)}</details><div className="tutorial-dots">{tutorial.map((_,i)=><button key={i} aria-label={`教程第${i+1}步`} className={i===tutorialStep?'active':''} onClick={()=>setTutorialStep(i)}/>)}</div><button className="btn gold full" onClick={()=>tutorialStep<4?setTutorialStep(tutorialStep+1):(setTraining(true),setModal('play'))}>{tutorialStep<4?'下一步':'学会了，去练一局'}<Icon name="arrow"/></button></Modal>}
 {modal==='account'&&account&&<Modal title="你的牌桌，有名有姓。" onClose={()=>{if(!busy){setModal(null);setLogoutConfirm(false)}}}><div className="account-status"><Icon name="shield"/><div><strong>{account.nickname}</strong><br/><span>@{account.username}</span></div></div><p>好友联机与长期对局保存在这个账号下。恢复码只在注册或恢复账号时显示，请妥善保管。</p><div className="account-menu"><button className="btn gold" onClick={()=>{setModal(null);nav('history')}}>我的对局<Icon name="replay"/></button><button className="btn subtle" onClick={()=>setLogoutConfirm(true)}>退出账号</button></div>{logoutConfirm&&<div className="account-logout-confirm"><p>{room&&isCloudRoom(room.id)?'退出会断开当前好友牌桌。之后登录原账号可尝试恢复座位；对局计时仍继续。':'退出后回到游客模式。已长期保存的对局仍留在账号中，下次登录可查看。'}</p><div className="modal-actions"><button className="btn subtle" disabled={busy} onClick={()=>setLogoutConfirm(false)}>继续使用</button><button className="btn gold" disabled={busy} onClick={()=>void signOut()}>{busy?'正在退出…':'确认退出账号'}</button></div></div>}</Modal>}
 {accountPanel}
 {toast&&<div className="toast" role="status"><Icon name="info" size={17}/>{toast}</div>}
 <InviteHandler onCode={code=>{setJoinCode(code);openFriends()}}/>
 </div>
}
function InviteHandler({onCode}:{onCode:(s:string)=>void}){const done=useRef(false);useEffect(()=>{if(done.current)return;done.current=true;const code=new URLSearchParams(location.search).get('room');if(code){onCode(code);if(!isStaticMode)history.replaceState({},'',location.pathname)}},[]);return null}
